(function(){
 'use strict';
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let auth,data;
 async function api(action,body){const token=await auth.currentUser.getIdToken();const r=await fetch('/api/paes?action='+action,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const json=await r.json();if(!r.ok)throw new Error(json.error||'No se pudo consultar el panel.');return json;}
 function render(){
  const course=$('course').value;const rows=data.rows.filter(r=>r.curso===course);$('publication').textContent=data.publication.cursos?.[course]?'Resultados publicados para este curso.':'Resultados privados para este curso.';
  $('rows').innerHTML=rows.length?rows.map((r,i)=>`<tr><td>${esc(r.nombre||'Intento reiniciado')}</td><td>${r.resetAt?'Reiniciado':r.submitted&&r.completada?'Completada':'Borrador'}</td><td>${Object.keys(r.answers||{}).length}</td><td>${r.completada?`${r.score} / ${r.total}`:'Pendiente'}</td><td><button type="button" data-detail="${i}">Ver trabajo</button> <button type="button" data-reset="${i}">Reabrir</button></td></tr>`).join(''):'<tr><td colspan="5">Todavía no hay intentos registrados para este curso.</td></tr>';
  $('keys').textContent=Object.entries(data.keys).map(([group,questions])=>`${group==='regular'?'Recorrido completo':'Recorrido con apoyo'}\n`+questions.map(q=>`${q.id.toUpperCase()}. ${q.text}\n${q.skill} · Tarea ${q.task||'—'} · Nivel ${q.level||'—'}\n${q.key}. ${q.reason}\nEvidencia: ${q.evidence||'Disponible al actualizar'}\n${(q.failures||[]).map((f,i)=>f?`${'ABCD'[i]}: ${f}`:'').filter(Boolean).join('\n')}`).join('\n\n')).join('\n\n');
  document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const r=rows[Number(b.dataset.detail)];$('detail').hidden=false;$('detail').textContent=`${r.nombre||'Intento reiniciado'} · ${r.curso}\n${r.completada?'Completada':'Borrador'}\n\nSala: ${r.duel?.code||"Sin sala registrada"}\n\nCitas del duelo:\n${(data.rooms||[]).flatMap(room=>(room.pacts||[]).filter(p=>p.uid===r.uid).map(p=>`${p.mission} · Fragmento ${p.paragraph+1}: ${p.explanation}`)).join("\n")||"Todavía sin citas"}\n\nRespuestas: ${JSON.stringify(r.answers||{})}\n\nDecisiones:\n${data.regular.missions.map(m=>`${m.title}: ${m.choices[r.decisions?.[m.id]]||'Pendiente'}\nEvidencia: ${r.evidence?.[m.id]||'Pendiente'}`).join('\n\n')}\n\nReflexión:\n${Object.entries(r.reflection||{}).map(([k,v])=>`${k}: ${v}`).join('\n')}`;});
  document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=async()=>{const r=rows[Number(b.dataset.reset)];if(!confirm(`¿Reabrir el trabajo de ${r.nombre||'este estudiante'}? Su intento anterior se conserva en el archivo privado; deberá recargar la actividad.`))return;await perform(async()=>{await api('admin-cards-reset',{uid:r.uid,sessionId:r.sessionId});await refresh();});});
 }
 async function refresh(){data=await api('admin-cards-list');$('privatePanel').hidden=false;$('adminLogin').hidden=true;$('adminStatus').textContent='Panel actualizado.';render();}
 async function perform(fn){try{await fn();}catch(e){$('adminStatus').textContent=e.message;}}
 $('adminLogin').onsubmit=e=>{e.preventDefault();perform(async()=>{({auth}=await PaesStudentSession.client());await auth.signInWithEmailAndPassword($('email').value,$('adminPassword').value);$('adminPassword').value='';await refresh();});};
 $('course').onchange=render;$('refresh').onclick=()=>perform(refresh);
 for(const [id,published] of [['publish',true],['hideResults',false]])$(id).onclick=()=>perform(async()=>{await api('admin-cards-release',{curso:$('course').value,published});await refresh();});
 perform(async()=>{({auth}=await PaesStudentSession.client());if(auth.currentUser)await refresh();});
})();
