/* Interfaz accesible. Las respuestas PAES y el duelo real se validan en servidor. */
(function(){
 'use strict';
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const guided=location.pathname.endsWith('guiada.html');if(guided)document.body.classList.add('guided');
 let session,activity,identity,resetAt=null,preview=false,attempt={answers:{},decisions:{},evidence:{},reflection:{},duel:{}},saveQueue=Promise.resolve(),saveTimer,revision=0,busy=false;
 let room=null,demo=null,archetype='guardian',currentMission=0,guidedStep=0,pollTimer,pollEpoch=0,duelBusy=false,displayRevision=-1,soundOn=false,audio=null;
 const completed=()=>attempt.submitted===true&&attempt.completada===true;
 const storageKey=()=>`umbral:${identity.uid}:${activity.sessionId}:${activity.version}:${resetAt||0}`;
 const roomKey=()=>`umbral-room:${identity.uid}:${activity.sessionId}`;
 const payload=()=>({version:activity.version,resetAt,answers:{...attempt.answers},decisions:{...attempt.decisions},evidence:{...attempt.evidence},reflection:{...attempt.reflection},duel:{...attempt.duel}});
 async function api(action,data,query=''){
  const token=await session.user.getIdToken();
  const res=await fetch(`/api/paes?action=${action}&mode=${guided?'guided':'regular'}${query}`,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});
  const json=await res.json();if(!res.ok)throw Object.assign(new Error(json.error||'No se pudo recuperar tu trabajo.'),{status:res.status,alreadySubmitted:json.alreadySubmitted});return json;
 }
 async function load(){
  const data=await api('cards-state');if(data.redirect){location.replace(data.redirect);return false;}
  identity=data.identity;activity=data.activity;resetAt=data.resetAt;preview=false;attempt=data.attempt||{answers:{},decisions:{},evidence:{},reflection:{},duel:{}};
  try{const local=JSON.parse(localStorage.getItem(storageKey())||'null');if(!completed()&&local&&local.localUpdatedAt>(attempt.updatedAt||0))Object.assign(attempt,local);}catch(_){}
  $('identityLabel').textContent=identity.reviewer?`REVISIÓN DOCENTE · ${identity.curso}`:`${identity.nombre} · ${identity.curso}`;$('saveStatus').textContent=completed()?'Entrega confirmada.':'Tu avance está recuperado.';updateProgress();
  return true;
 }
 function updateProgress(){if(!activity)return;const answered=activity.questions.filter(q=>attempt.answers[q.id]).length;$('readingCount').textContent=`${answered}/${activity.questions.length}`;$('progressText').textContent=completed()?'Completada · Entrega confirmada':`${answered} de ${activity.questions.length} respuestas registradas`;$('finish').textContent=completed()?'Ver entrega y resultados':'Revisar y entregar';if(completed())$('saveStatus').textContent='Entrega confirmada.';}
 function remember(){
  updateProgress();if(preview){$('saveStatus').textContent='Entrenamiento individual. No guarda ni entrega trabajo.';return;}if(completed())return;
  revision++;try{localStorage.setItem(storageKey(),JSON.stringify({...payload(),localUpdatedAt:Date.now()}));}catch(_){}
  clearTimeout(saveTimer);saveTimer=setTimeout(()=>queueSave(),600);
 }
 function queueSave(){
  if(preview||completed()||!activity)return saveQueue;const data=payload(),version=revision;$('saveStatus').textContent='Guardando…';
  saveQueue=saveQueue.catch(()=>{}).then(async()=>{try{const result=await api('cards-save',data);if(version===revision){attempt.updatedAt=result.attempt.updatedAt;try{localStorage.removeItem(storageKey());}catch(_){}$('saveStatus').textContent='Avance guardado.';}}catch(e){$('saveStatus').textContent=e.message+' Tu copia local se conserva.';if(e.status===409){await load();renderReading();}throw e;}});
  saveQueue.catch(()=>{});return saveQueue;
 }
 function showView(id){window.speechSynthesis?.cancel();for(const part of ['duelView','readingView','deckView','closing'])$(part).hidden=part!==id;for(const [tab,part] of [['tabDuel','duelView'],['tabReading','readingView'],['tabDeck','deckView'],['finish','closing']]){if(id===part)$(tab).setAttribute('aria-current','page');else $(tab).removeAttribute('aria-current');}if(id==='readingView')renderReading();if(id==='closing')renderClosing();}
 function showGame(){$('inicio').hidden=true;$('game').hidden=false;renderPresets();renderCollection();showView('duelView');window.scrollTo({top:0,behavior:'instant'});}
 async function resumeRoom(){let code=attempt.duel?.code;try{code=localStorage.getItem(roomKey())||code;}catch(_){}if(!code)return;try{const r=await api('cards-room-state',null,'&code='+encodeURIComponent(code));setRoom(r.room);schedulePoll();}catch(e){$('lobbyStatus').textContent=e.message;}}
 $('start').onclick=async()=>{if(busy)return;busy=true;$('start').disabled=true;try{session=await CartasSession.restore();if(!session){$('loginDialog').showModal();return;}if(await load()){showGame();await resumeRoom();}}catch(e){$('entryStatus').textContent=PaesStudentSession.errorMessage(e);}finally{busy=false;$('start').disabled=false;}};
 $('loginForm').onsubmit=async e=>{e.preventDefault();$('loginStatus').textContent='Ingresando…';try{session=await CartasSession.signIn($('rut').value,$('password').value);$('password').value='';if(await load()){$('loginDialog').close();stopPoll();demo=null;room=null;showGame();await resumeRoom();}}catch(e){$('loginStatus').textContent=PaesStudentSession.errorMessage(e);}};
 $('explore').onclick=async()=>{if(busy)return;busy=true;try{const r=await fetch('/api/paes?action=cards-preview');if(!r.ok)throw new Error('No se pudo abrir el entrenamiento.');activity=(await r.json()).activity;preview=true;identity={uid:'demo',nombre:'Entrenamiento individual',curso:''};attempt={answers:{},decisions:{},evidence:{},reflection:{},duel:{}};$('identityLabel').textContent='ENTRENAMIENTO · RIVAL DE PRÁCTICA';showGame();remember();startDemo();$('helpDialog').showModal();}catch(e){$('entryStatus').textContent=e.message;}finally{busy=false;}};
 function renderPresets(){
  $('presets').innerHTML=Object.entries(Umbral.PRESETS).map(([id,p])=>`<button type="button" class="preset" data-preset="${id}" aria-pressed="${archetype===id}"><img src="assets/${p.art}.webp" alt="${esc(p.name)}"><div><strong>${esc(p.name)}</strong><p>${esc(p.description)}</p></div>${archetype===id?'<span class="check" aria-hidden="true">✓</span>':''}</button>`).join('');
  document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{archetype=b.dataset.preset;renderPresets();});
 }
 function cardMarkup(cardId,instance,playable=false){const c=Umbral.CARDS[cardId];return `<button type="button" class="game-card ${playable?'playable':''}" data-card="${cardId}" ${instance?`data-instance="${instance}"`:''} aria-label="${esc(c.name)}, coste ${c.cost}, ${esc(c.type)}"><span class="cost" aria-label="Coste">${c.cost}</span><img src="assets/${c.art}.webp" alt=""><div class="card-info"><strong>${esc(c.name)}</strong><small>${esc(c.type)}${c.guard?' · CUSTODIA':''}</small><p>${esc(c.text)}</p>${c.attack?`<div class="card-footer">⚔ ${c.attack} &nbsp; ♥ ${c.hp}</div>`:''}</div></button>`;}
 function renderCollection(){$('collection').innerHTML=Object.keys(Umbral.CARDS).map(id=>cardMarkup(id)).join('');$('collection').querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>inspectCard(b.dataset.card));}
 function cardHeading(c){return `<img class="dialog-card-art" src="assets/${c.art}.webp" alt="Ilustración de ${esc(c.name)}"><p class="eyebrow">${esc(c.type)} · COSTE ${c.cost}</p><h2 id="cardTitle">${esc(c.name)}</h2><p class="card-detail-description">${esc(c.text)}</p>${c.attack?`<p>Fuerza: ${c.attack} · Vida: ${c.hp}${c.guard?' · Custodia':''}</p>`:''}`;}
 function openCard(html){$('cardDetail').innerHTML=html;$('cardStatus').textContent='';if(!$('cardDialog').open)$('cardDialog').showModal();}
 function inspectCard(id){openCard(cardHeading(Umbral.CARDS[id])+'<p>Las cartas de tu mano se juegan desde el tablero. Las reliquias se aplican a un aliado propio.</p>');}
 function setRoom(next){if(room?.code===next.code&&next.revision<room.revision)return;const previous=room;room=next;if(!preview){attempt.duel={code:room.code};try{localStorage.setItem(roomKey(),room.code);}catch(_){}}renderRoom();if(previous&&previous.revision!==room.revision){for(const [id,key] of [['myHero','me'],['foeHero','foe']])if(previous[key]&&room[key]&&previous[key].hp>room[key].hp){$(id).classList.add('hit');setTimeout(()=>$(id).classList.remove('hit'),700);}for(const unit of room.me.board)if(!previous.me.board.some(b=>b.id===unit.id))$('myBoard').querySelector(`[data-unit="${unit.id}"]`)?.classList.add('arrive');if(!previous.yourTurn&&room.yourTurn)chime();}}
 async function lobbyAction(action){if(duelBusy)return;if(preview){startDemo();return;}duelBusy=true;$('lobbyStatus').textContent='Conectando la sala…';try{const data={version:activity.version,archetype,code:$('roomCode').value.trim().toUpperCase()};const result=await api(action,data);displayRevision=-1;setRoom(result.room);remember();schedulePoll();$('lobbyStatus').textContent='';}catch(e){$('lobbyStatus').textContent=e.message;}finally{duelBusy=false;}}
 $('createRoom').onclick=()=>lobbyAction('cards-room-create');$('joinRoom').onclick=()=>lobbyAction('cards-room-join');
 function heroMarkup(p,own){const preset=Umbral.PRESETS[p.archetype];return `<img src="assets/${preset.art}.webp" alt="${esc(preset.name)}"><div><strong>${esc(p.name)}</strong><small>${own?'TU REFUGIO':'REFUGIO RIVAL'} · ${esc(preset.name)}</small>${own?`<div class="energy" aria-label="Energía disponible ${p.energy}">${'◆'.repeat(p.energy)}${'◇'.repeat(Math.max(0,p.maxEnergy-p.energy))} <span class="energy-text">${p.energy>p.maxEnergy?`${p.energy} · +1 de Cita viva`:`${p.energy}/${p.maxEnergy}`}</span></div>`:''}</div><div class="vitals"><span class="life" aria-label="Vida">♥ ${p.hp}/${p.maxHp}</span><span class="shield" aria-label="Escudo">◈ ${p.block}</span><small>Mazo ${p.deckCount} · Descarte ${p.discardCount}</small></div>`;}
 function unitMarkup(unit,own){const c=Umbral.CARDS[unit.card];return `<button type="button" class="unit ${own&&unit.ready&&room.yourTurn?'ready':''}" data-unit="${unit.id}" data-own="${own}" aria-label="${esc(c.name)}. Fuerza ${unit.attack}. Vida ${unit.hp}. ${own&&unit.ready?'Puede atacar':'Consulta carta'}"><img src="assets/${c.art}.webp" alt=""><span class="stats"><span>⚔ ${unit.attack}</span><span>♥ ${unit.hp}</span></span><strong>${esc(c.name)}</strong><span class="unit-note">${c.guard?'Custodia':own?(unit.ready?'Listo para atacar':'Espera tu siguiente turno'):'Aliado rival'}</span></button>`;}
 function renderRoom(){
  if(!room){$('lobby').hidden=false;$('arena').hidden=true;return;}
  $('lobby').hidden=true;$('arena').hidden=false;$('liveCode').textContent=preview?'PRÁCTICA':room.code;$('connection').textContent=preview?'Entrenamiento individual · sin guardado':'Sala conectada';
  $('waiting').hidden=room.phase!=='waiting';$('waitingCode').textContent=room.code;$('battle').hidden=room.phase==='waiting';$('leaveRoom').hidden=room.phase==='ended';$('leaveRoom').textContent=room.phase==='waiting'?'Cerrar sala':'Retirarme';
  if(room.phase==='waiting')return;
  if(room.revision===displayRevision)return;displayRevision=room.revision;
  $('myHero').innerHTML=heroMarkup(room.me,true);$('foeHero').innerHTML=room.foe?heroMarkup(room.foe,false):'';
  $('foeHand').innerHTML=room.foe?Array.from({length:room.foe.handCount},()=>'<i class="card-back" aria-hidden="true"></i>').join('')+`<span class="eyebrow">&nbsp; ${room.foe.handCount}</span>`:'';
  for(const [id,p,own] of [['myBoard',room.me,true],['foeBoard',room.foe,false]]){$(id).innerHTML=p?p.board.map(b=>unitMarkup(b,own)).join('')+Array.from({length:3-p.board.length},()=>'<div class="empty-slot" aria-hidden="true">✧</div>').join(''):'';$(id).querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>openUnit(b.dataset.unit,own));}
  $('myHand').innerHTML=room.me.hand.map(i=>cardMarkup(i.card,i.id,room.phase==='active'&&room.yourTurn&&Umbral.CARDS[i.card].cost<=room.me.energy)).join('');$('myHand').querySelectorAll('[data-instance]').forEach(b=>b.onclick=()=>openHand(b.dataset.instance));
  $('handCount').textContent=room.me.hand.length;$('turnLabel').textContent=room.phase==='ended'?'DUELO CERRADO':room.yourTurn?'TU TURNO':'TURNO DE TU COMPAÑERO';$('turnHint').textContent=room.phase==='ended'?'Puedes continuar las lecturas y entregar tu crónica.':room.yourTurn?'Juega cartas o ataca con un aliado listo. Al terminar, descartas la mano restante.':'Puedes consultar las lecturas mientras esperas.';$('endTurn').disabled=!room.yourTurn||room.phase!=='active'||duelBusy;
  $('duelResult').hidden=room.phase!=='ended';if(room.phase==='ended'){$('duelResult').innerHTML=`<p class="eyebrow">EL ARCHIVO PERMANECE</p><h2>${room.winner==='me'?'Tu refugio resistió.':room.winner==='foe'?'Una nueva estrategia te espera.':'La sala se cerró.'}</h2><p>La victoria no cambia tu resultado de lectura. Revisa tus decisiones o vuelve a jugar.</p><button id="newDuel" type="button" class="primary">Preparar otro duelo</button>`;$('newDuel').onclick=()=>{stopPoll();room=null;demo=null;displayRevision=-1;try{localStorage.removeItem(roomKey());}catch(_){}renderRoom();if(preview)$('createRoom').textContent='Iniciar entrenamiento';};}
  $('turnLog').innerHTML=room.log.map(t=>`<li>${esc(t)}</li>`).join('');
 }
 function targetButtons(kind,card,ally){const targets=kind==='buff'?room.me.board.map(b=>({id:b.id,label:Umbral.CARDS[b.card].name+` · ${b.attack} fuerza / ${b.hp} vida`})):room.targets.map(id=>({id,label:id==='hero'?'Refugio rival':Umbral.CARDS[room.foe.board.find(b=>b.id===id).card].name}));return `<div class="target-actions">${targets.map(t=>`<button type="button" data-target="${t.id}">${kind==='buff'?'Fortalecer':'Atacar'}: ${esc(t.label)}</button>`).join('')}</div>${!targets.length?'<p>No hay un objetivo disponible.</p>':''}`;}
 function wireTargets(action){$('cardDetail').querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>act({...action,target:b.dataset.target}));}
 function openHand(instance){
  const i=room.me.hand.find(c=>c.id===instance);if(!i)return;const c=Umbral.CARDS[i.card];let html=cardHeading(c);
  if(room.phase!=='active'||!room.yourTurn){openCard(html+'<p>Podrás jugar cuando sea tu turno.</p>');return;}
  if(c.cost>room.me.energy){openCard(html+`<p>Necesitas ${c.cost} de energía. Tienes ${room.me.energy}.</p>`);return;}
  if(c.type==='Aliado'&&room.me.board.length>=3){openCard(html+'<p>Tu fila ya tiene tres aliados.</p>');return;}
  if(c.pact){if(room.me.citedTurn===room.turn){openCard(html+'<p>Ya usaste Cita viva en este turno.</p>');return;}openCard(html+pactMarkup());wirePact(instance);return;}
  if(c.damage||c.buff){openCard(html+targetButtons(c.buff?'buff':'hit'));wireTargets({kind:'play',card:instance});return;}
  openCard(html+`<div class="target-actions"><button id="playCard" type="button" class="primary">${c.type==='Aliado'?'Invocar aliado':'Jugar carta'} · ${c.cost} energía</button></div>`);$('playCard').onclick=()=>act({kind:'play',card:instance});
 }
 function openUnit(id,own){const unit=(own?room.me:room.foe).board.find(b=>b.id===id);if(!unit)return;const c=Umbral.CARDS[unit.card];let html=cardHeading(c)+`<p>Fuerza actual: ${unit.attack} · Vida actual: ${unit.hp}/${unit.maxHp}.</p>`;if(own&&room.yourTurn&&unit.ready&&room.phase==='active'){openCard(html+targetButtons('hit'));wireTargets({kind:'attack',ally:id});}else openCard(html+`<p>${own?'Este aliado podrá atacar en tu siguiente turno.':'Es un aliado del rival.'}</p>`);}
 function pactMarkup(){return `<form id="pactForm" class="pact-form"><label>Documento<select id="pactMission">${activity.missions.map(m=>`<option value="${m.id}">${esc(m.title)}</option>`).join('')}</select></label><label>Fragmento<select id="pactParagraph"></select></label><blockquote id="pactQuote"></blockquote><label>¿Cómo se relaciona esta pista con tu estrategia?<textarea id="pactExplanation" maxlength="1200" placeholder="Esta condición me lleva a…" required></textarea></label><button type="submit" class="primary">Citar y activar la carta</button></form>`;}
 function wirePact(instance){function update(){const m=activity.missions.find(m=>m.id===$('pactMission').value);$('pactParagraph').innerHTML=m.paragraphs.map((p,i)=>`<option value="${i}">Fragmento ${i+1}</option>`).join('');showQuote();}function showQuote(){const m=activity.missions.find(m=>m.id===$('pactMission').value);$('pactQuote').textContent=m.paragraphs[Number($('pactParagraph').value)];}$('pactMission').onchange=update;$('pactParagraph').onchange=showQuote;update();$('pactForm').onsubmit=e=>{e.preventDefault();const explanation=$('pactExplanation').value.trim();if(explanation.length<(guided&&!preview?3:12)){$('cardStatus').textContent='Añade una explicación de la relación con tu estrategia.';return;}act({kind:'play',card:instance,proof:{mission:$('pactMission').value,paragraph:Number($('pactParagraph').value),explanation}});};}
 async function act(action){
  if(duelBusy||!room)return;duelBusy=true;$('endTurn').disabled=true;$('cardStatus').textContent='Confirmando jugada…';
  try{const data={version:activity.version,code:room.code,revision:room.revision,...action};if(preview){demo=Umbral.apply(demo,'demo',data,Date.now(),data.proof);setRoom(Umbral.publicRoom(demo,'demo'));}else{const r=await api('cards-room-act',data);setRoom(r.room);}if($('cardDialog').open)$('cardDialog').close();$('duelStatus').textContent='Jugada confirmada.';chime();if(preview&&!room.yourTurn&&room.phase==='active')setTimeout(botTurn,500);}catch(e){$('cardStatus').textContent=e.message;$('duelStatus').textContent=e.message;if(e.status===409&&!preview)await pollOnce();}finally{duelBusy=false;$('endTurn').disabled=!room?.yourTurn||room?.phase!=='active';}
 }
 $('endTurn').onclick=()=>act({kind:'end'});$('leaveRoom').onclick=()=>{if(confirm(room.phase==='waiting'?'¿Cerrar esta sala?':'¿Retirarte de este duelo? Tu lectura se conserva.'))act({kind:'concede'});};
 $('copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(room.code);$('connection').textContent='Código copiado.';}catch(_) {$('connection').textContent='Comparte el código que aparece en pantalla.';}};
 function stopPoll(){pollEpoch++;clearTimeout(pollTimer);}
 function schedulePoll(){stopPoll();const epoch=pollEpoch;async function tick(){if(epoch!==pollEpoch||preview||!room)return;await pollOnce();if(epoch===pollEpoch&&room?.phase!=='ended')pollTimer=setTimeout(tick,document.hidden?8000:2200);}pollTimer=setTimeout(tick,2200);}
 async function pollOnce(){if(preview||!room)return;const code=room.code;try{const r=await api('cards-room-state',null,'&code='+encodeURIComponent(code));if(room?.code===code)setRoom(r.room);}catch(e){$('connection').textContent='Conexión interrumpida. Reintentando…';}}
 function startDemo(){stopPoll();demo=Umbral.create({uid:'demo',curso:'demo',nombre:'Tu refugio'},archetype,71483,Date.now(),'ABC234');demo=Umbral.join(demo,{uid:'bot',curso:'demo',nombre:'Rival de práctica'},archetype==='guardian'?'exploradora':'guardian',Date.now());displayRevision=-1;setRoom(Umbral.publicRoom(demo,'demo'));}
 function botTurn(){if(!preview||!demo||demo.phase!=='active'||demo.activeUid!=='bot')return;try{
  for(let n=0;n<15&&demo.phase==='active';n++){
   const p=demo.players.bot;let chosen=null;
   for(const i of p.hand){const c=Umbral.CARDS[i.card];if(c.cost>p.energy||(c.type==='Aliado'&&p.board.length>=3)||(c.buff&&!p.board.length)||(c.pact&&p.citedTurn===demo.turn))continue;let target=c.buff?p.board[0].id:Umbral.availableTargets(demo,'bot')[0];if(c.damage&&!target)continue;chosen={kind:'play',card:i.id,target};if(c.pact)chosen.proof={mission:'archivo',paragraph:0,explanation:'La condición del documento invita a planear antes de actuar.'};break;}
   if(!chosen)break;demo=Umbral.apply(demo,'bot',{...chosen,revision:demo.revision},Date.now(),chosen.proof);
  }
  for(const unit of demo.players.bot.board){if(demo.phase!=='active')break;if(unit.ready)demo=Umbral.apply(demo,'bot',{kind:'attack',ally:unit.id,target:Umbral.availableTargets(demo,'bot')[0],revision:demo.revision},Date.now());}
  if(demo.phase==='active')demo=Umbral.apply(demo,'bot',{kind:'end',revision:demo.revision},Date.now());setRoom(Umbral.publicRoom(demo,'demo'));
 }catch(e){$('duelStatus').textContent='No se pudo continuar el entrenamiento. Puedes preparar otro duelo.';}}
 function renderReading(){
  if(!activity)return;window.speechSynthesis?.cancel();const m=activity.missions[currentMission],qs=activity.questions.filter(q=>q.mission===m.id),readonly=completed()?'disabled':'';
  $('missionNav').innerHTML=activity.missions.map((x,i)=>`<button type="button" class="${i===currentMission?'active':''}" data-reading="${i}">${String(i+1).padStart(2,'0')} · ${esc(x.title)}${activity.questions.filter(q=>q.mission===x.id).every(q=>attempt.answers[q.id])?' ✓':''}</button>`).join('');$('missionNav').querySelectorAll('[data-reading]').forEach(b=>b.onclick=()=>{currentMission=Number(b.dataset.reading);guidedStep=0;renderReading();});
  const visible=guided&&!preview?[qs[Math.min(guidedStep,qs.length-1)]]:qs;
  $('readingContent').innerHTML=`<div class="reader"><article class="document"><p class="eyebrow">${esc(m.genre)}</p><h3>${esc(m.title)}</h3><p>${esc(m.introduction)}</p><button id="readAloud" type="button">Escuchar lectura</button> <button id="stopReading" type="button">Detener audio</button>${m.paragraphs.map((p,i)=>`<p><span aria-label="Fragmento ${i+1}">${i+1}.</span> ${esc(p)}</p>`).join('')}<p class="source">Texto original de Estudia CEST. Personajes y documentos ficticios.</p></article><section class="questions"><div class="concept">${esc(m.concept)}</div>${guided&&!preview?`<div class="guided-nav"><button id="previousQ" type="button" ${guidedStep===0?'disabled':''}>← Anterior</button><span>Pregunta ${guidedStep+1} de ${qs.length}</span><button id="nextQ" type="button" ${guidedStep>=qs.length-1?'disabled':''}>Siguiente →</button></div>`:''}${visible.map(q=>`<fieldset><legend>${q.id.replace('q','')}. ${esc(q.text)}</legend>${q.options.map((option,i)=>`<label><input type="radio" name="${q.id}" value="${'ABCD'[i]}" ${attempt.answers[q.id]==='ABCD'[i]?'checked':''} ${readonly}><span>${'ABCD'[i]}. ${esc(option)}</span></label>`).join('')}</fieldset>`).join('')}<div class="decision"><h3>${esc(m.decision)}</h3>${m.choices.map((v,i)=>`<label><input type="radio" name="decision" value="${i}" ${attempt.decisions[m.id]===i?'checked':''} ${readonly}>${esc(v)}</label>`).join('')}<p id="consequence">${esc(m.consequences[attempt.decisions[m.id]]||'Tu elección quedará en tu crónica.')}</p><label for="evidence">${guided?'¿Qué pista te ayudó? Puedes escribir una frase.':'Copia una pista y explica cómo sostiene tu decisión.'}</label><textarea id="evidence" maxlength="2500" ${readonly}>${esc(attempt.evidence[m.id]||'')}</textarea></div><div class="reader-actions"><button id="nextReading" type="button" class="primary">${currentMission<2?'Siguiente lectura →':'Volver al duelo →'}</button></div><p id="readingStatus" role="status" aria-live="polite"></p></section></div>`;
  $('readingContent').querySelectorAll('input[type=radio]').forEach(input=>input.onchange=()=>{if(completed())return;if(input.name==='decision'){attempt.decisions[m.id]=Number(input.value);$('consequence').textContent=m.consequences[Number(input.value)];}else attempt.answers[input.name]=input.value;remember();});
  $('evidence').oninput=()=>{attempt.evidence[m.id]=$('evidence').value;remember();};$('readAloud').onclick=()=>{if(!window.speechSynthesis){$('readingStatus').textContent='Este navegador no ofrece lectura en voz alta.';return;}speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance(m.paragraphs.join('. '));voice.lang='es-CL';voice.rate=guided?.88:1;speechSynthesis.speak(voice);};$('stopReading').onclick=()=>{window.speechSynthesis?.cancel();};
  if(guided&&!preview){$('previousQ').onclick=()=>{guidedStep--;renderReading();};$('nextQ').onclick=()=>{guidedStep++;renderReading();};}
  $('nextReading').onclick=()=>{const complete=qs.every(q=>attempt.answers[q.id])&&attempt.decisions[m.id]!==undefined&&(guided||(attempt.evidence[m.id]||'').trim().length>=12);if(!complete&&!completed()){$('readingStatus').textContent='Completa las preguntas, elige una decisión y añade su pista antes de continuar. Tu avance se conserva.';return;}if(currentMission<2){currentMission++;guidedStep=0;renderReading();$('missionNav').scrollIntoView({behavior:'instant',block:'start'});}else showView('duelView');};
 }
 function renderClosing(){
  const labels={comprendi:'¿Qué relación o idea comprendiste mejor?',evidencia:'¿Qué evidencia sostuvo una de tus decisiones?',mejorare:'¿Qué mejorarás al leer y jugar otra vez?'};
  $('closingFields').innerHTML=Object.entries(labels).map(([key,label])=>`<label>${label}<textarea data-reflection="${key}" maxlength="2500" ${completed()?'disabled':''}>${esc(attempt.reflection[key]||'')}</textarea></label>`).join('');$('closingFields').querySelectorAll('[data-reflection]').forEach(t=>t.oninput=()=>{attempt.reflection[t.dataset.reflection]=t.value;remember();});$('submit').hidden=completed();showResults();
 }
 function showResults(){if(!completed()){$('results').hidden=true;return;}$('results').hidden=false;$('results').innerHTML=attempt.result?`<h3>Resultados publicados</h3><p class="score">${attempt.result.score} de ${attempt.result.total} respuestas.</p>${Object.entries(attempt.result.bySkill).map(([s,v])=>`<p>${esc(s)}: ${v.score}/${v.total}</p>`).join('')}${(attempt.review||[]).map(r=>{const q=activity.questions.find(q=>q.id===r.id);return `<article class="review-item"><strong>${esc(q.text)}</strong><p>Tu respuesta: ${esc(attempt.answers[r.id])}. Respuesta esperada: ${esc(r.key)}.</p><p>${esc(r.reason)}</p><p>Evidencia: ${esc(r.evidence)}</p>${(r.failures||[]).map((f,i)=>f?`<p>${'ABCD'[i]}: ${esc(f)}</p>`:'').join('')}</article>`;}).join('')}`:'<p>Entrega confirmada. El profesor aún no publica los resultados. Puedes volver cuando lo indique.</p>';}
 $('submit').onclick=async()=>{
  if(preview){$('submitStatus').textContent='El entrenamiento no entrega trabajo. Ingresa con tu cuenta para guardar tu crónica.';$('loginDialog').showModal();return;}if(busy||completed())return;
  const missing=activity.questions.filter(q=>!attempt.answers[q.id]),incomplete=activity.missions.filter(m=>attempt.decisions[m.id]===undefined||(!guided&&(attempt.evidence[m.id]||'').trim().length<12));
  if(missing.length||incomplete.length||['comprendi','evidencia','mejorare'].some(k=>(attempt.reflection[k]||'').trim().length<(guided?3:12))){$('submitStatus').textContent='Completa las preguntas de las tres lecturas, las decisiones, sus evidencias y las tres respuestas del cierre.';return;}
  busy=true;$('submit').disabled=true;clearTimeout(saveTimer);$('submitStatus').textContent='Guardando y comprobando la entrega…';
  try{queueSave();await saveQueue;await api('cards-submit',payload());const confirmed=await api('cards-state');if(!confirmed.attempt||confirmed.attempt.completada !== true||confirmed.attempt.submitted!==true)throw new Error('Todavía no se confirmó la entrega. Vuelve a intentarlo.');attempt=confirmed.attempt;try{localStorage.removeItem(storageKey());}catch(_){}updateProgress();renderClosing();$('submitStatus').textContent='Entrega confirmada.';$('confirmation').showModal();}
  catch(e){if(e.status===409){await load();renderClosing();if(completed()){$('submitStatus').textContent='Entrega confirmada.';$('confirmation').showModal();return;}}$('submitStatus').textContent=e.message;}finally{busy=false;$('submit').disabled=false;}
 };
 $('tabDuel').onclick=()=>showView('duelView');$('tabReading').onclick=()=>showView('readingView');$('tabDeck').onclick=()=>showView('deckView');$('finish').onclick=()=>showView('closing');for(const id of ['lobbyRead','duelRead'])$(id).onclick=()=>showView('readingView');$('backGame').onclick=()=>showView('duelView');$('keepPlaying').onclick=()=>{$('confirmation').close();showView('duelView');};$('help').onclick=()=>$('helpDialog').showModal();
 $('credits').onclick=()=>openCard('<h2 id="cardTitle">Créditos</h2><p>Diseño, textos y motor de cartas originales de Estudia CEST. Ilustraciones creadas con Z-Image Turbo local y Nano Banana Pro en Higgsfield. Originales y prompts conservados en el proyecto.</p><p>Referencias de mecánicas: Mitos y Leyendas, Magic y Hearthstone. Sin cartas, personajes, logotipos ni código de esas franquicias.</p>');
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
 function chime(){if(!soundOn)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type='sine';o.frequency.value=room?.yourTurn?523.25:392;g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+.28);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.3);}catch(_) {}}
 $('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'Sonido activado':'Sonido apagado';$('sound').setAttribute('aria-pressed',String(soundOn));chime();};
 window.addEventListener('online',()=>{if(activity&&!preview&&!completed())queueSave();if(room&&!preview)pollOnce();});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&room&&!preview)pollOnce();else window.speechSynthesis?.cancel();});
 window.addEventListener('beforeunload',e=>{if(activity&&!preview&&!completed()){try{if(localStorage.getItem(storageKey())){e.preventDefault();e.returnValue='';}}catch(_) {}}});
})();
