# -*- coding: utf-8 -*-
"""
Generador COMPLETO Educación Parvularia - PARTE 2
Convivencia y Ciudadanía + Corporalidad
"""
import json

ruta = r"c:\Users\fconu\OneDrive\Escritorio\PAGINA WEB\profefranciscopancho-blog\evaluaciones\educacion-parvularia\pruebas\parv-nt\plan.json"

with open(ruta, 'r', encoding='utf-8') as f:
    plan = json.load(f)

# Convivencia y Ciudadanía (10 preguntas)
convivencia = [
    {"id": "parv-11", "numero": 11, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Resolución pacífica de conflictos", "enunciado": "Dos niños/as de NT2 pelean por el mismo juguete. ¿Cuál estrategia es más pedagógica?", "alternativas": [{"letra": "A", "texto": "Quitar el juguete a ambos hasta que se calmen"}, {"letra": "B", "texto": "Ayudarles a expresar sus emociones, escucharse mutuamente, y buscar soluciones juntos (turnarse, usar timer, buscar otro juguete)"}, {"letra": "C", "texto": "Dárselo al niño/a que lo vio primero"}, {"letra": "D", "texto": "Decirles que deben compartir sin mediar"}], "respuesta_correcta": "B", "explicacion": "La resolución de conflictos es una oportunidad de aprendizaje. La educadora media el proceso: (1) ayuda a cada niño/a a nombrar su emoción y necesidad, (2) facilita que se escuchen mutuamente, (3) los guía para generar soluciones (turnarse con timer, encontrar juguete similar, jugar juntos). Esto desarrolla empatía, comunicación, pensamiento crítico y habilidades sociales. El conflicto se transforma en experiencia de aprendizaje colaborativo.", "temas_relacionados": ["Mediación de conflictos", "Comunicación", "Empatía", "Solución colaborativa"]},
    {"id": "parv-12", "numero": 12, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Respeto por la diversidad", "enunciado": "Un niño de NT1 dice que 'las niñas no pueden jugar a los superhéroes'. ¿Cómo aborda la educadora esta situación?", "alternativas": [{"letra": "A", "texto": "Ignorar el comentario para no darle importancia"}, {"letra": "B", "texto": "Conversar con el grupo sobre que todos/as pueden jugar a lo que deseen, mostrando ejemplos de mujeres fuertes y valientes"}, {"letra": "C", "texto": "Separar los juegos: superhéroes para niños, muñecas para niñas"}, {"letra": "D", "texto": "Castigar al niño por ser discriminador"}], "respuesta_correcta": "B", "explicacion": "Los estereotipos de género se cuestionan mediante conversaciones reflexivas y modelos diversos. La educadora aprovecha el momento para hablar sobre que todos/as tienen los mismos derechos, muestra ejemplos de mujeres valientes (deportistas, científicas, bomberas), y promueve que cada persona elija según sus intereses. Esto construye equidad de género, respeto por la diversidad, y amplía las posibilidades de juego y exploración para todos/as.", "temas_relacionados": ["Equidad de género", "Estereotipos", "Diversidad", "Derechos"]},
    {"id": "parv-13", "numero": 13, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Participación democrática", "enunciado": "¿Qué práctica promueve mejor la participación democrática en NT2?", "alternativas": [{"letra": "A", "texto": "La educadora establece todas las normas y las explica claramente"}, {"letra": "B", "texto": "Asambleas semanales donde niños/as proponen ideas, votan, y evalúan acuerdos tomados"}, {"letra": "C", "texto": "Permitir que hagan lo que quieran sin normas"}, {"letra": "D", "texto": "Elegir un 'líder del día' que decide por todos"}], "respuesta_correcta": "B", "explicacion": "Las asambleas son espacios privilegiados de participación democrática. Los niños/as aprenden a: proponer ideas, escuchar opiniones diversas, argumentar, votar, respetar decisiones mayoritarias, evaluar resultados. Experimentan que su voz cuenta, que las decisiones colectivas nos comprometen, y que podemos revisar acuerdos si no funcionan. Desarrolla pensamiento crítico, comunicación, respeto por la diversidad de opiniones, y construcción colectiva de normas.", "temas_relacionados": ["Asamblea", "Participación", "Democracia", "Toma de decisiones colectiva"]},
    {"id": "parv-14", "numero": 14, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Colaboración", "enunciado": "Para fomentar la colaboración, ¿qué tipo de actividad es más efectiva?", "alternativas": [{"letra": "A", "texto": "Cada niño/a completa su propio trabajo individual"}, {"letra": "B", "texto": "Proyectos grupales con meta común: construir una ciudad con bloques, crear un mural colectivo, preparar una obra de teatro"}, {"letra": "C", "texto": "Competencias entre niños/as para ver quién termina primero"}, {"letra": "D", "texto": "Trabajos en paralelo sin interacción"}], "respuesta_correcta": "B", "explicacion": "Los proyectos con meta común requieren colaboración auténtica. Los niños/as deben comunicarse, distribuir roles, coordinarse, resolver problemas juntos, y celebrar logros colectivos. Construir una ciudad necesita planificación conjunta (¿qué edificios?), distribución de tareas (unos hacen casas, otros calles), ajustes colaborativos (¿cómo conectamos las partes?). Esta experiencia desarrolla habilidades sociales, comunicación, pensamiento estratégico, y sentido de comunidad.", "temas_relacionados": ["Colaboración", "Trabajo en equipo", "Proyectos", "Meta común"]},
    {"id": "parv-15", "numero": 15, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Construcción de normas", "enunciado": "¿Cuál es la mejor manera de establecer normas en el aula de NT1?", "alternativas": [{"letra": "A", "texto": "La educadora escribe las normas y las pone en un cartel"}, {"letra": "B", "texto": "Conversar con los niños/as sobre qué necesitamos para convivir bien, co-construir 3-4 normas simples, representarlas con dibujos/fotos"}, {"letra": "C", "texto": "Copiar las normas de otro curso"}, {"letra": "D", "texto": "No tener normas para respetar la libertad infantil"}], "respuesta_correcta": "B", "explicacion": "Las normas co-construidas tienen mayor significado y adherencia. Al conversar sobre '¿qué necesitamos para estar bien todos/as?', los niños/as identifican necesidades (seguridad, respeto, orden), proponen normas, las consensúan. Representarlas con dibujos/fotos las hace comprensibles para no lectores. Las normas deben ser pocas (3-4), positivas (qué hacer, no prohibiciones), simples, y revisables. Este proceso desarrolla reflexión ética, sentido de comunidad, y compromiso personal.", "temas_relacionados": ["Normas", "Co-construcción", "Convivencia", "Representación visual"]},
    {"id": "parv-16", "numero": 16, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Empatía", "enunciado": "¿Qué estrategia pedagógica desarrolla mejor la empatía en NT2?", "alternativas": [{"letra": "A", "texto": "Explicar teóricamente qué es la empatía"}, {"letra": "B", "texto": "Lectura de cuentos con dilemas emocionales, preguntando '¿cómo se siente el personaje?', '¿qué harías tú?', juegos de roles"}, {"letra": "C", "texto": "Obligarlos a compartir siempre"}, {"letra": "D", "texto": "Premiar a los niños/as más empáticos"}], "respuesta_correcta": "B", "explicacion": "La empatía se desarrolla poniéndose en el lugar del otro. Los cuentos permiten explorar emociones ajenas en contexto seguro; preguntas como '¿cómo se siente?' invitan a inferir estados emocionales; '¿qué harías?' promueve pensamiento moral. Los juegos de roles (jugar a la familia, al hospital) permiten experimentar diferentes perspectivas. Esta combinación desarrolla comprensión emocional, toma de perspectiva, y conductas prosociales.", "temas_relacionados": ["Empatía", "Literatura infantil", "Juego simbólico", "Toma de perspectiva"]},
    {"id": "parv-17", "numero": 17, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Cuidado del entorno", "enunciado": "¿Cómo promover el cuidado del entorno en la sala de NT1?", "alternativas": [{"letra": "A", "texto": "Solo la educadora ordena y limpia para dar ejemplo"}, {"letra": "B", "texto": "Rutinas de orden con música, contenedores rotulados, responsabilidades rotativas (regar plantas, ordenar biblioteca)"}, {"letra": "C", "texto": "Castigar a quien deja desorden"}, {"letra": "D", "texto": "Contratar personal de aseo adicional"}], "respuesta_correcta": "B", "explicacion": "El cuidado del entorno se aprende siendo parte activa. Rutinas de orden con música hacen el proceso lúdico; contenedores rotulados facilitan autonomía (saben dónde va cada cosa); responsabilidades rotativas (regar plantas, ordenar libros) generan sentido de pertenencia y compromiso. Los niños/as experimentan que cuidar el espacio beneficia a todos/as, desarrollan autonomía, respeto por lo colectivo, y hábitos de organización.", "temas_relacionados": ["Cuidado del entorno", "Rutinas", "Responsabilidades", "Autonomía"]},
    {"id": "parv-18", "numero": 18, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Aprecio por la diversidad cultural", "enunciado": "Una familia migrante se integra al curso. ¿Cómo enriquecer el currículo con esta diversidad?", "alternativas": [{"letra": "A", "texto": "Tratarlos igual que todos para que no se sientan diferentes"}, {"letra": "B", "texto": "Invitar a la familia a compartir música, comida, cuentos de su cultura; incorporar palabras en su idioma; valorar explícitamente la riqueza de tener diversas culturas"}, {"letra": "C", "texto": "Hacer una actividad especial solo sobre ese país"}, {"letra": "D", "texto": "Pedirles que se adapten a la cultura chilena"}], "respuesta_correcta": "B", "explicacion": "La diversidad cultural es un recurso pedagógico valioso. Invitar a la familia a compartir elementos de su cultura (música, comida, cuentos) valida su identidad, enriquece al grupo, y desarrolla aprecio por la diversidad. Incorporar palabras en su idioma hace el ambiente inclusivo. Valorar explícitamente ('qué suerte tenemos diferentes culturas') transmite que la diferencia suma. Todos/as aprenden sobre otras formas de vivir, desarrollando respeto intercultural y apertura mental.", "temas_relacionados": ["Interculturalidad", "Diversidad cultural", "Inclusión", "Valoración de diferencias"]},
    {"id": "parv-19", "numero": 19, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Solidaridad", "enunciado": "¿Qué situación pedagógica fomenta mejor la solidaridad en NT2?", "alternativas": [{"letra": "A", "texto": "Enseñar explícitamente que deben ayudarse"}, {"letra": "B", "texto": "Proyectos solidarios auténticos: recolectar juguetes para otros niños/as, visitar hogar de ancianos, ayudar a compañeros con dificultades"}, {"letra": "C", "texto": "Competir para ver quién es más solidario"}, {"letra": "D", "texto": "Obligarlos a compartir sus pertenencias"}], "respuesta_correcta": "B", "explicacion": "La solidaridad se desarrolla mediante experiencias auténticas de ayuda mutua. Proyectos como recolectar juguetes conecta con necesidades reales de otros, genera empatía y acción. Visitar ancianos permite compartir alegría, escuchar historias, valorar a personas mayores. Ayudar a compañeros con dificultades desarrolla colaboración cotidiana. Estas experiencias concretas construyen valores prosociales, sentido de comunidad, y comprensión de interdependencia social.", "temas_relacionados": ["Solidaridad", "Proyectos solidarios", "Valores prosociales", "Comunidad"]},
    {"id": "parv-20", "numero": 20, "ambito": "Desarrollo Personal y Social", "nucleo": "Convivencia y Ciudadanía", "habilidad": "Respeto por los derechos", "enunciado": "¿Cómo enseñar sobre derechos de los niños/as en NT2?", "alternativas": [{"letra": "A", "texto": "Leer la Declaración de Derechos completa"}, {"letra": "B", "texto": "Conversar sobre situaciones concretas: '¿todos pueden jugar?', '¿qué necesitamos para estar bien?', representar derechos con dibujos (derecho a jugar, aprender, ser cuidados)"}, {"letra": "C", "texto": "Solo hablar de deberes, no de derechos"}, {"letra": "D", "texto": "Es muy complejo para esta edad"}], "respuesta_correcta": "B", "explicacion": "Los derechos se comprenden desde experiencias concretas. Conversar sobre '¿todos pueden jugar?' introduce el derecho a la participación; '¿qué necesitamos?' explora derechos básicos (cuidado, alimentación, cariño). Representarlos con dibujos los hace tangibles. Situaciones cotidianas ('¿es justo que no lo dejen jugar?') desarrollan sentido de justicia. Los niños/as comprenden que tienen derechos que deben respetarse, y que ellos/as también deben respetar derechos ajenos, construyendo ciudadanía desde temprana edad.", "temas_relacionados": ["Derechos del niño/a", "Justicia", "Ciudadanía", "Equidad"]}
]

# Corporalidad y Movimiento (5 preguntas)
corporalidad = [
    {"id": "parv-21", "numero": 21, "ambito": "Desarrollo Personal y Social", "nucleo": "Corporalidad y Movimiento", "habilidad": "Motricidad gruesa", "enunciado": "¿Cuál actividad desarrolla mejor la motricidad gruesa en NT1?", "alternativas": [{"letra": "A", "texto": "Permanecer sentados coloreando"}, {"letra": "B", "texto": "Circuitos motrices: saltar aros, caminar sobre líneas, trepar, lanzar pelotas, reptar"}, {"letra": "C", "texto": "Ver videos de deportes"}, {"letra": "D", "texto": "Explicar teóricamente los movimientos del cuerpo"}], "respuesta_correcta": "B", "explicacion": "Los circuitos motrices integran diversos movimientos que desarrollan coordinación, equilibrio, fuerza y control corporal. Saltar aros trabaja impulsión y aterrizaje; caminar sobre líneas desarrolla equilibrio; trepar fortalece extremidades; lanzar pelotas coordina ojo-mano; reptar moviliza todo el cuerpo. La variedad de desafíos motrices, el carácter lúdico, y la repetición con ajuste progresivo favorecen el desarrollo motor integral.", "temas_relacionados": ["Motricidad gruesa", "Coordinación", "Equilibrio", "Circuitos motrices"]},
    {"id": "parv-22", "numero": 22, "ambito": "Desarrollo Personal y Social", "nucleo": "Corporalidad y Movimiento", "habilidad": "Motricidad fina", "enunciado": "¿Qué actividad fortalece la motricidad fina necesaria para la escritura en NT2?", "alternativas": [{"letra": "A", "texto": "Planas de letras repetitivas"}, {"letra": "B", "texto": "Juegos de pinzas (pasar objetos pequeños con pinzas), enhebrar, modelar plasticina, rasgar papel, apilar bloques pequeños"}, {"letra": "C", "texto": "Usar solo lápices desde el inicio"}, {"letra": "D", "texto": "Dejarlos sin actividades manipulativas"}], "respuesta_correcta": "B", "explicacion": "La motricidad fina se desarrolla progresivamente mediante experiencias manipulativas variadas. Usar pinzas fortalece músculos de dedos y coordinación ojo-mano; enhebrar requiere precisión y coordinación bimanual; modelar plasticina ejercita manos y dedos; rasgar papel desarrolla fuerza y control; apilar bloques pequeños trabaja coordinación. Estas experiencias lúdicas preparan naturalmente para el trazo, sin forzar la escritura prematuramente.", "temas_relacionados": ["Motricidad fina", "Prensión", "Coordinación ojo-mano", "Pre-escritura"]},
    {"id": "parv-23", "numero": 23, "ambito": "Desarrollo Personal y Social", "nucleo": "Corporalidad y Movimiento", "habilidad": "Conciencia corporal", "enunciado": "¿Cómo promover la conciencia corporal en NT1?", "alternativas": [{"letra": "A", "texto": "Dibujar láminas del cuerpo humano"}, {"letra": "B", "texto": "Juegos de exploración corporal: 'Simón dice toca tu rodilla', yoga infantil, danzas, autorretrato en espejo, dibujo de silueta"}, {"letra": "C", "texto": "Memorizar nombres de huesos"}, {"letra": "D", "texto": "Solo actividades sedentarias"}], "respuesta_correcta": "B", "explicacion": "La conciencia corporal se construye mediante experiencia directa del propio cuerpo. 'Simón dice' enfoca atención en partes corporales; yoga infantil desarrolla control, respiración y atención corporal; danzas exploran movimientos y expresión; el espejo permite observarse en movimiento; dibujar silueta representa el propio cuerpo. Estas experiencias integran movimiento, atención, representación y expresión, construyendo imagen corporal integrada.", "temas_relacionados": ["Conciencia corporal", "Esquema corporal", "Expresión corporal", "Autorrepresentación"]},
    {"id": "parv-24", "numero": 24, "ambito": "Desarrollo Personal y Social", "nucleo": "Corporalidad y Movimiento", "habilidad": "Bienestar y cuidado del cuerpo", "enunciado": "¿Qué práctica pedagógica promueve mejor el bienestar físico en NT2?", "alternativas": [{"letra": "A", "texto": "Actividad física solo una vez a la semana"}, {"letra": "B", "texto": "Movimiento integrado al día: bailes, juegos activos al aire libre, pausas de estiramiento, hidratación regular, colaciones saludables"}, {"letra": "C", "texto": "Priorizar actividades sedentarias para mantener orden"}, {"letra": "D", "texto": "Prohibir correr para evitar accidentes"}], "respuesta_correcta": "B", "explicacion": "El bienestar físico requiere movimiento regular integrado naturalmente al día. Bailes brindan actividad cardiovascular lúdica; juegos al aire libre ofrecen movimiento variado y contacto con naturaleza; pausas de estiramiento previenen tensión muscular; hidratación y colaciones saludables nutren el cuerpo. Esta integración transmite que el movimiento es parte natural de la vida, no una actividad especial aislada, promoviendo hábitos de vida activa y saludable.", "temas_relacionados": ["Bienestar físico", "Vida activa", "Hábitos saludables", "Movimiento"]},
    {"id": "parv-25", "numero": 25, "ambito": "Desarrollo Personal y Social", "nucleo": "Corporalidad y Movimiento", "habilidad": "Coordinación visomotora", "enunciado": "¿Cuál secuencia de actividades es más apropiada para desarrollar coordinación visomotora?", "alternativas": [{"letra": "A", "texto": "Comenzar directamente con escritura de letras"}, {"letra": "B", "texto": "Progresión: trazos libres amplios (pizarrón vertical), trazos dirigidos (caminos anchos), trazos más precisos (laberintos), finalmente grafomotricidad (líneas, curvas, pre-letras)"}, {"letra": "C", "texto": "Solo actividades digitales (tablet)"}, {"letra": "D", "texto": "Copiar textos extensos"}], "respuesta_correcta": "B", "explicacion": "La coordinación visomotora se desarrolla progresivamente desde lo global a lo fino. Trazos libres amplios en vertical (pizarra, caballete) fortalecen hombro y brazos; caminos anchos introducen direccionalidad; laberintos requieren mayor precisión; grafomotricidad (líneas, curvas, zigzag) prepara específicamente para letras. Esta secuencia respeta el desarrollo madurativo, evita frustración, y construye habilidades de forma natural y lúdica.", "temas_relacionados": ["Coordinación visomotora", "Grafomotricidad", "Progresión madurativa", "Pre-escritura"]}
]

plan["exam"]["preguntas"].extend(convivencia)
plan["exam"]["preguntas"].extend(corporalidad)

with open(ruta, 'w', encoding='utf-8') as f:
    json.dump(plan, f, ensure_ascii=False, indent=2)

print(f"✅ Total preguntas: {len(plan['exam']['preguntas'])}")
