# -*- coding: utf-8 -*-
"""Parte 6: Pensamiento Matemático (7 preguntas)"""
import json
ruta = r"c:\Users\fconu\OneDrive\Escritorio\PAGINA WEB\profefranciscopancho-blog\evaluaciones\educacion-parvularia\pruebas\parv-nt\plan.json"
with open(ruta, 'r', encoding='utf-8') as f:
    plan = json.load(f)

matematico = [
    {"id": "parv-69", "numero": 69, "ambito": "Interacción y Comprensión del Entorno", "nucleo": "Pensamiento Matemático", "habilidad": "Cuantificación", "enunciado": "¿Cómo desarrollar el sentido numérico en NT1?", "alternativas": [{"letra": "A", "texto": "Memorizar números sin contexto"}, {"letra": "B", "texto": "Contar objetos reales con propósito (¿cuántos platos necesitamos?), juegos de correspondencia uno-a-uno, comparar cantidades"}, {"letra": "C", "texto": "Solo escribir números"}, {"letra": "D", "texto": "Evitar situaciones numéricas"}], "respuesta_correcta": "B", "explicacion": "El sentido numérico se construye mediante uso funcional. Contar con propósito (poner mesa, repartir materiales) hace significativo el conteo; correspondencia uno-a-uno (un vaso por persona) construye base de cuantificación; comparar cantidades (¿dónde hay más?) desarrolla sentido relativo de cantidad. Estas experiencias concretas construyen comprensión profunda del número antes de simbolización abstracta.", "temas_relacionados": ["Sentido numérico", "Conteo", "Correspondencia", "Cantidad"]},
    {"id": "parv-70", "numero": 70, "ambito": "Interacción y Comprensión del Entorno", "nucleo": "Pensamiento Matemático", "habilidad": "Patrones", "enunciado": "¿Qué actividad desarrolla mejor el reconocimiento de patrones en NT2?", "alternativas": [{"letra": "A", "texto": "Solo mostrar patrones hechos"}, {"letra": "B", "texto": "Crear patrones con materiales variados (bloques, cuentas, sonidos, movimientos), identificar patrón en naturaleza (hojas, caracoles), continuar y crear patrones"}, {"letra": "C", "texto": "Memorizar secuencias sin comprender"}, {"letra": "D", "texto": "No trabajar patrones"}], "respuesta_correcta": "B", "explicacion": "Los patrones son fundamento del pensamiento algebraico. Crear patrones (AB AB: rojo-azul-rojo-azul) desarrolla comprensión de regularidad; identificar patrones naturales (pétalos de flores, espirales de caracol) muestra que existen en el mundo; variar materiales (visual, auditivo, corporal) generaliza el concepto; crear patrones propios ejercita pensamiento abstracto. Esta habilidad fundamenta álgebra futura y desarrolla pensamiento predictivo.", "temas_relacionados": ["Patrones", "Regularidad", "Pensamiento algebraico", "Predicción"]},
    {"id": "parv-71", "numero": 71, "ambito": "Interacción y Comprensión del Entorno", "nucleo": "Pensamiento Matemático", "habilidad": "Formas geométricas", "enunciado": "¿Cómo enseñar formas geométricas en NT1?", "alternativas": [{"letra": "A", "texto": "Solo mostrar láminas de figuras"}, {"letra": "B", "texto": "Explorar formas en objetos reales, construir con bloques geométricos, buscar formas en el entorno (ventanas=rectángulos), clasificar por forma"}, {"letra": "C", "texto": "Memorizar nombres sin manipular"}, {"letra": "D", "texto": "Solo dibujar formas"}], "respuesta_correcta": "B", "explicacion": "La geometría se comprende mediante exploración tridimensional y conexión con el mundo. Manipular bloques geométricos desarrolla percepción espacial; buscar formas en entorno (señales de tránsito, ventanas) conecta geometría con realidad; clasificar por forma desarrolla categorización; construir con formas ejercita visualización espacial. Partir de 3D (objetos) antes que 2D (dibujos) respeta desarrollo perceptual infantil.", "temas_relacionados": ["Formas geométricas", "Geometría", "Percepción espacial", "Clasificación"]},
    {"id": "parv-72", "numero": 72, "ambito": "Interacción y Comprensión del Entorno", "nucleo": "Pensamiento Matemático", "habilidad": "Medición", "enunciado": "¿Qué actividad introduce la medición en NT2?", "alternativas": [{"letra": "A", "texto": "Usar solo unidades convencionales (metros, kilos)"}, {"letra": "B", "texto": "Medición no convencional: medir altura con bloques, peso comparando 'más pesado/liviano', capacidad llenando recipientes, tiempo con canciones"}, {"letra": "C", "texto": "No abordar medición"}, {"letra": "D", "texto": "Solo teoría de medición"}], "respuesta_correcta": "B", "explicacion": "La medición no convencional construye concepto de medir antes de unidades estándar. Medir con bloques ('cuántos bloques mide la mesa') introduce idea de unidad; comparar pesos desarrolla sentido de peso; llenar recipientes explora capacidad; usar canciones como timer desarrolla sentido temporal. Estas experiencias concretas construyen comprensión de que medir es comparar con una unidad, preparando para unidades convencionales posteriores.", "temas_relacionados": ["Medición no convencional", "Comparación", "Unidades", "Sentido de magnitud"]},
    {"id": "parv-73", "numero": 73, "ambito": "Interacción y Comprensión del Entorno", "nucleo": "Pensamiento Matemático", "habilidad": "Resolución de problemas", "enunciado": "¿Cómo promover resolución de problemas matemáticos en NT1?", "alternativas": [{"letra": "A", "texto": "Dar la solución inmediatamente"}, {"letra": "B", "texto": "Plantear problemas reales ('¿alcanzan las sillas?', '¿cómo repartimos equitativamente?'), usar materiales concretos, probar estrategias, validar soluciones diversas"}, {"letra": "C", "texto": "Solo problemas abstractos en papel"}, {"letra": "D", "texto": "Evitar situaciones problemáticas"}], "respuesta_correcta": "B", "explicacion": "La resolución de problemas se aprende resolviendo. Problemas reales (¿alcanzan galletas para todos?) motivan; usar materiales concretos (contar galletas, personas) hace tangible el problema; probar estrategias desarrolla perseverancia; validar soluciones diversas (contar de uno en uno, hacer grupos) muestra que hay múltiples caminos. Este enfoque desarrolla pensamiento matemático flexible, estratégico, y útil para la vida cotidiana.", "temas_relacionados": ["Resolución de problemas", "Estrategias", "Pensamiento flexible", "Matemática cotidiana"]},
    {"id": "parv-74", "numero": 74, "ambito": "Interacción y Comprensión del Entorno", "nucleo": "Pensamiento Matemático", "habilidad": "Relaciones espaciales", "enunciado": "¿Qué práctica desarrolla mejor noción espacial en NT2?", "alternativas": [{"letra": "A", "texto": "Solo láminas bidimensionales"}, {"letra": "B", "texto": "Juegos de ubicación (arriba/abajo, dentro/fuera, cerca/lejos), circuitos motrices, construcciones con bloques, mapas simples del aula"}, {"letra": "C", "texto": "Memorizar vocabulario espacial"}, {"letra": "D", "texto": "No moverse del lugar"}], "respuesta_correcta": "B", "explicacion": "La noción espacial se construye mediante movimiento y experiencia tridimensional. Juegos de ubicación ('esconde el objeto arriba/debajo') vivencian relaciones espaciales; circuitos motrices (pasar por túnel, sobre puente) experimentan posiciones; construir con bloques desarrolla visualización espacial; mapas simples representan espacio bidimensionalmente. Esta progresión de experiencia corporal a representación construye comprensión espacial sofisticada.", "temas_relacionados": ["Relaciones espaciales", "Ubicación", "Orientación", "Representación espacial"]},
    {"id": "parv-75", "numero": 75, "ambito": "Interacción y Comprensión del Entorno", "nucleo": "Pensamiento Matemático", "habilidad": "Clasificación matemática", "enunciado": "¿Cómo desarrollar clasificación matemática en NT1?", "alternativas": [{"letra": "A", "texto": "Clasificar solo según criterio adulto"}, {"letra": "B", "texto": "Clasificar materiales según criterios propios y luego sugeridos (color, tamaño, forma, función), verbalizar criterios, cambiar criterios"}, {"letra": "C", "texto": "Solo una clasificación posible"}, {"letra": "D", "texto": "No clasificar"}], "respuesta_correcta": "B", "explicacion": "La clasificación es habilidad cognitiva fundamental. Comenzar con criterios propios respeta pensamiento infantil; introducir criterios específicos (color, tamaño) enseña atributos; verbalizar criterios ('estos son rojos, estos azules') desarrolla lenguaje matemático; cambiar criterios (reclasificar por tamaño lo clasificado por color) muestra flexibilidad. Esta práctica desarrolla pensamiento categorial, atención a atributos, y flexibilidad cognitiva esenciales para matemática.", "temas_relacionados": ["Clasificación", "Atributos", "Categorización", "Flexibilidad cognitiva"]}
]

plan["exam"]["preguntas"].extend(matematico)
with open(ruta, 'w', encoding='utf-8') as f:
    json.dump(plan, f, ensure_ascii=False, indent=2)
print(f"✅ Pensamiento Matemático: {len(matematico)} preguntas")
print(f"📊 Total: {len(plan['exam']['preguntas'])} preguntas")
