# -*- coding: utf-8 -*-
"""Parte 4: Lenguajes Artísticos (10 preguntas)"""
import json

ruta = r"c:\Users\fconu\OneDrive\Escritorio\PAGINA WEB\profefranciscopancho-blog\evaluaciones\educacion-parvularia\pruebas\parv-nt\plan.json"
with open(ruta, 'r', encoding='utf-8') as f:
    plan = json.load(f)

lenguajes_artisticos = [
    {"id": "parv-41", "numero": 41, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Expresión plástica", "enunciado": "¿Cuál enfoque es más apropiado para artes visuales en NT1?", "alternativas": [{"letra": "A", "texto": "Modelos para copiar exactamente"}, {"letra": "B", "texto": "Exploración libre de materiales diversos (témperas, arcilla, collage, telas), sin modelo, valorando el proceso creativo y la expresión personal"}, {"letra": "C", "texto": "Solo pintar dentro de líneas pre-dibujadas"}, {"letra": "D", "texto": "Evaluar solo por parecido al modelo"}], "respuesta_correcta": "B", "explicacion": "En parvularia, el arte es expresión personal y exploración sensorial, no reproducción. Ofrecer materiales diversos (témperas, arcilla, materiales reciclados) invita a experimentar texturas, colores, formas. Sin modelo, cada creación es única y auténtica. Valorar el proceso ('cuéntame sobre tu trabajo') más que el producto desarrolla creatividad, autoexpresión, y confianza. El arte es lenguaje para comunicar ideas, emociones y experiencias de formas no verbales.", "temas_relacionados": ["Expresión plástica", "Creatividad", "Exploración sensorial", "Proceso creativo"]},
    {"id": "parv-42", "numero": 42, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Expresión musical", "enunciado": "¿Qué práctica desarrolla mejor la musicalidad en NT2?", "alternativas": [{"letra": "A", "texto": "Solo escuchar música grabada pasivamente"}, {"letra": "B", "texto": "Cantar canciones variadas, experimentar instrumentos, crear ritmos con cuerpo y objetos, improvisar melodías, moverse con música"}, {"letra": "C", "texto": "Memorizar partituras"}, {"letra": "D", "texto": "Silencio absoluto"}], "respuesta_correcta": "B", "explicacion": "La musicalidad se desarrolla mediante experiencia activa. Cantar fortalece control vocal y memoria; experimentar instrumentos (maracas, tambores, metalófonos) explora timbres; crear ritmos desarrolla sentido temporal; improvisar melodías fomenta creatividad musical; moverse con música integra cuerpo y sonido. Esta riqueza de experiencias desarrolla sensibilidad auditiva, coordinación, expresión emocional, y apreciación musical.", "temas_relacionados": ["Expresión musical", "Ritmo", "Exploración sonora", "Coordinación audio-motriz"]},
    {"id": "parv-43", "numero": 43, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Expresión corporal", "enunciado": "¿Cuál actividad promueve mejor la expresión corporal en NT1?", "alternativas": [{"letra": "A", "texto": "Copiar movimientos coreografiados rígidamente"}, {"letra": "B", "texto": "Propuestas abiertas: 'muévete como un árbol con viento', 'muestra con tu cuerpo cómo te sientes', danza libre con telas, mímica"}, {"letra": "C", "texto": "Solo sentarse quietos"}, {"letra": "D", "texto": "Movimientos repetitivos sin exploración"}], "respuesta_correcta": "B", "explicacion": "La expresión corporal es comunicar con el cuerpo. Propuestas metafóricas ('como un árbol') invitan a interpretar creativamente; expresar emociones corporalmente conecta sentimiento y movimiento; danza libre con telas explora movimiento fluido; mímica comunica sin palabras. Estas experiencias desarrollan conciencia corporal, creatividad, expresión emocional, y amplían el repertorio expresivo más allá del lenguaje verbal.", "temas_relacionados": ["Expresión corporal", "Danza creativa", "Comunicación no verbal", "Movimiento expresivo"]},
    {"id": "parv-44", "numero": 44, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Juego dramático", "enunciado": "¿Cómo enriquecer el juego dramático en NT2?", "alternativas": [{"letra": "A", "texto": "Prohibir los juegos de roles"}, {"letra": "B", "texto": "Rincones temáticos con materiales abiertos (cocina, hospital, tienda), vestuario variado, tiempo amplio para desarrollar juegos, documentar y conversar sobre lo jugado"}, {"letra": "C", "texto": "Solo juegos dirigidos por el adulto"}, {"letra": "D", "texto": "Un solo rincón sin materiales"}], "respuesta_correcta": "B", "explicacion": "El juego dramático (juego simbólico) es crucial para desarrollo socioemocional y cognitivo. Rincones temáticos invitan a asumir roles; materiales abiertos (telas, cajas, utensilios) permiten creatividad; vestuario facilita transformación; tiempo amplio (30-40 min) permite desarrollar narrativas complejas; conversar después reflexiona sobre lo vivido. Este juego desarrolla empatía, lenguaje, pensamiento simbólico, resolución de problemas, y comprensión del mundo social.", "temas_relacionados": ["Juego dramático", "Juego simbólico", "Asunción de roles", "Desarrollo socioemocional"]},
    {"id": "parv-45", "numero": 45, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Apreciación estética", "enunciado": "¿Cómo desarrollar apreciación artística en NT1?", "alternativas": [{"letra": "A", "texto": "Solo decir qué es 'bonito' o 'feo'"}, {"letra": "B", "texto": "Observar obras de arte variadas (pinturas, esculturas, tejidos), conversar: '¿qué ves?, ¿cómo crees que lo hizo?, ¿qué sientes?', conectar con creaciones propias"}, {"letra": "C", "texto": "Memorizar nombres de artistas"}, {"letra": "D", "texto": "No mostrar arte"}], "respuesta_correcta": "B", "explicacion": "La apreciación estética se educa mediante observación atenta y conversación. Preguntas como '¿qué ves?' desarrollan observación; '¿cómo lo hizo?' reflexiona sobre técnicas; '¿qué sientes?' valida respuesta emocional. Variar tipos de arte (pintura, escultura, arte textil, fotografía) amplía referentes. Conectar con creaciones propias ('ellos también son artistas') valida su expresión. Esto desarrolla sensibilidad estética, pensamiento crítico, y apreciación de diversas expresiones culturales.", "temas_relacionados": ["Apreciación estética", "Observación de arte", "Sensibilidad artística", "Diversidad cultural"]},
    {"id": "parv-46", "numero": 46, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Creatividad", "enunciado": "¿Qué práctica pedagógica fomenta mejor la creatividad en NT2?", "alternativas": [{"letra": "A", "texto": "Actividades con un solo resultado correcto"}, {"letra": "B", "texto": "Problemas abiertos: 'construye algo que vuela', 'crea un instrumento con materiales reciclados', valorar soluciones diversas"}, {"letra": "C", "texto": "Copiar siempre modelos adultos"}, {"letra": "D", "texto": "Criticar ideas no convencionales"}], "respuesta_correcta": "B", "explicacion": "La creatividad requiere problemas abiertos con múltiples soluciones. 'Construye algo que vuela' invita a imaginar, planificar, probar; 'crea un instrumento' transforma materiales cotidianos en herramientas expresivas. Valorar soluciones diversas transmite que hay muchas formas válidas de resolver. Esta apertura desarrolla pensamiento divergente, innovación, perseverancia ante desafíos, y confianza para proponer ideas originales.", "temas_relacionados": ["Creatividad", "Pensamiento divergente", "Resolución creativa", "Innovación"]},
    {"id": "parv-47", "numero": 47, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Integración de lenguajes artísticos", "enunciado": "¿Cuál proyecto integra mejor diversos lenguajes artísticos en NT1?", "alternativas": [{"letra": "A", "texto": "Enseñar música, plástica y danza por separado"}, {"letra": "B", "texto": "Crear una obra de teatro: inventar historia, hacer escenografía (plástica), crear canciones (música), actuar (dramática), diseñar vestuario"}, {"letra": "C", "texto": "Solo una disciplina artística aislada"}, {"letra": "D", "texto": "Arte solo como relleno de tiempo"}], "respuesta_correcta": "B", "explicacion": "Los lenguajes artísticos se enriquecen mutuamente en proyectos integrados. Crear una obra requiere narrativa (lenguaje verbal), escenografía (plástica), música (composición de canciones), actuación (expresión corporal y dramática), vestuario (diseño). Esta integración muestra que el arte es multidimensional, promueve colaboración, y permite que cada niño/a aporte desde sus fortalezas. El resultado colectivo es más rico que partes individuales.", "temas_relacionados": ["Integración artística", "Proyectos", "Trabajo colaborativo", "Multidimensionalidad"]},
    {"id": "parv-48", "numero": 48, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Arte y naturaleza", "enunciado": "¿Cómo vincular arte y naturaleza en NT2?", "alternativas": [{"letra": "A", "texto": "Solo usar materiales comerciales"}, {"letra": "B", "texto": "Land art: crear con elementos naturales (hojas, piedras, ramas), observar colores/formas en naturaleza, pintar con elementos naturales (betarragas, flores)"}, {"letra": "C", "texto": "No salir al exterior"}, {"letra": "D", "texto": "Considerar naturaleza solo en ciencias"}], "respuesta_correcta": "B", "explicacion": "Land art conecta arte, naturaleza y conciencia ambiental. Crear con elementos naturales (mandalas de hojas, esculturas con piedras) usa la naturaleza como material y lienzo; observar colores/texturas naturales sensibiliza estéticamente; pintar con betarragas o flores muestra pigmentos naturales. Esto desarrolla apreciación de belleza natural, creatividad con recursos del entorno, y respeto por la naturaleza como fuente de inspiración y materiales.", "temas_relacionados": ["Land art", "Arte natural", "Conciencia ambiental", "Creatividad ecológica"]},
    {"id": "parv-49", "numero": 49, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Documentación artística", "enunciado": "¿Cómo documentar el proceso artístico en NT1?", "alternativas": [{"letra": "A", "texto": "Solo guardar el producto final"}, {"letra": "B", "texto": "Fotografiar proceso, registrar comentarios de los niños/as, crear portafolios con obras y reflexiones, exhibir con cédulas escritas por ellos/as"}, {"letra": "C", "texto": "Tirar todas las creaciones"}, {"letra": "D", "texto": "No valorar el trabajo infantil"}], "respuesta_correcta": "B", "explicacion": "La documentación hace visible el aprendizaje artístico. Fotografías del proceso muestran experimentación y progreso; registrar comentarios ('hice un castillo para mi familia') captura intenciones y significados; portafolios recopilan trayectoria; exhibiciones con cédulas ('Paula, 5 años: Mi familia en el parque') validan autoría. Esta práctica transmite que sus creaciones son valiosas, desarrolla metacognición ('cómo ha cambiado mi dibujo'), y comunica el aprendizaje a familias.", "temas_relacionados": ["Documentación pedagógica", "Portafolio", "Valoración del proceso", "Metacognición"]},
    {"id": "parv-50", "numero": 50, "ambito": "Comunicación Integral", "nucleo": "Lenguajes Artísticos", "habilidad": "Arte y emociones", "enunciado": "¿Cómo usar el arte para expresión emocional en NT2?", "alternativas": [{"letra": "A", "texto": "Prohibir expresar emociones 'negativas' en arte"}, {"letra": "B", "texto": "Invitar a pintar 'cómo te sientes', usar colores para emociones, crear máscaras de emociones, dramatizar situaciones emocionales"}, {"letra": "C", "texto": "Solo hacer arte 'bonito' y 'alegre'"}, {"letra": "D", "texto": "Censurar expresiones emocionales"}], "respuesta_correcta": "B", "explicacion": "El arte es canal privilegiado para expresión emocional. Pintar 'cómo me siento' externaliza estados internos; asociar colores con emociones (rojo=rabia, azul=tranquilo) desarrolla vocabulario emocional; máscaras de emociones permiten 'ponerse' emociones; dramatizar situaciones explora emociones en contexto seguro. Validar toda expresión emocional (incluyendo tristeza, enojo) enseña que todas las emociones son legítimas y que hay formas constructivas de expresarlas.", "temas_relacionados": ["Arte y emoción", "Expresión emocional", "Vocabulario emocional", "Canalización saludable"]}
]

plan["exam"]["preguntas"].extend(lenguajes_artisticos)
with open(ruta, 'w', encoding='utf-8') as f:
    json.dump(plan, f, ensure_ascii=False, indent=2)
print(f"✅ Lenguajes Artísticos: {len(lenguajes_artisticos)} preguntas")
print(f"📊 Total: {len(plan['exam']['preguntas'])} preguntas")
