# -*- coding: utf-8 -*-
"""
Script para agregar contextos pedagógicos extensos a las preguntas 11-20
Incluye: nombres de educadoras, situaciones reales, OAs BCEP 2018
"""

import json

# Contextos pedagógicos mejorados para preguntas 11-20
contextos_mejorados = {
    "parv-11": {
        "contexto": "En el jardín infantil 'Los Aromos' de Viña del Mar, la educadora Andrea observa una situación conflictiva durante el juego libre. Martina y Sebastián, ambos de NT1 (4 años), están disputándose un camión de juguete en el rincón de construcción. Martina lo tomó primero para construir un 'camino', pero Sebastián insiste en que él lo vio antes. Ambos niños comienzan a subir el tono de voz, Martina abraza el camión fuertemente y Sebastián intenta quitárselo. Andrea reflexiona sobre el Objetivo de Aprendizaje 4 del núcleo Convivencia y Ciudadanía de las BCEP 2018: 'Apreciar el significado que tienen para las personas y las comunidades, diversas manifestaciones culturales que se desarrollan en su entorno'. También considera el OA 1: 'Participar en actividades y juegos grupales con sus pares, conversando, intercambiando perceptivamente opiniones e ideas, acordando estrategias comunes para resolver problemas, y lidiar colaborativamente con situaciones que implican alcanzar acuerdos'. Este tipo de conflictos son oportunidades valiosas para desarrollar habilidades de comunicación, empatía y resolución colaborativa de problemas. Andrea debe decidir si intervenir directamente o mediar el proceso.",
        "numero": 11
    },
    "parv-12": {
        "contexto": "En el jardín infantil municipal de Talca, la educadora Lorena trabaja con un grupo de NT1. Durante el juego en el rincón de disfraces, escucha a Ignacio (4 años) decirle a Camila: 'las niñas no pueden jugar a los superhéroes, solo a las princesas'. Camila baja la mirada y se aleja del rincón. Lorena identifica inmediatamente un estereotipo de género que debe abordar. Reflexiona sobre el Objetivo de Aprendizaje 3 del núcleo Convivencia y Ciudadanía de las BCEP 2018: 'Reconocer, y progresivamente hacer respetar el derecho a expresarse libremente, a ser escuchado y a que su opinión sea tomada en cuenta'. También considera el OA 5: 'Reconocer progresivamente requerimientos esenciales de las prácticas de convivencia democrática, tales como: escucha de opiniones divergentes, el respeto por los demás, de los turnos, de los acuerdos de las mayorías'. Lorena sabe que los estereotipos de género se construyen socialmente desde la primera infancia y que su rol es ampliar las posibilidades de exploración para todos los niños y niñas, sin limitaciones basadas en el género. Debe intervenir pedagógicamente de forma respetuosa pero clara.",
        "numero": 12
    },
    "parv-13": {
        "contexto": "El educador Mauricio trabaja en un jardín infantil de Antofagasta con un grupo de NT2. Ha implementado asambleas semanales todos los viernes por la mañana, donde los niños y niñas conversan sobre temas que les interesan o preocupan. Sin embargo, Mauricio nota que estas asambleas se han vuelto espacios donde él habla la mayor parte del tiempo, algunos niños interrumpen constantemente, y las decisiones finalmente las toma él 'para avanzar más rápido'. Reflexionando críticamente sobre su práctica, recuerda el Objetivo de Aprendizaje 2 del núcleo Convivencia y Ciudadanía de las BCEP 2018: 'Participar en actividades y juegos colaborativos, planificando, acordando estrategias para un propósito común y asumiendo progresivamente responsabilidades en ellos'. También considera el OA 6: 'Respetar normas y acuerdos creados colaborativamente con pares y adultos, para el bienestar del grupo'. Mauricio quiere transformar las asambleas en verdaderos espacios democráticos donde los niños experimenten participación auténtica, aprendan a escuchar opiniones diversas, argumenten sus ideas, voten, y se comprometan con las decisiones colectivas. Necesita replantear la estructura y dinámica de estos encuentros.",
        "numero": 13
    },
    "parv-14": {
        "contexto": "En el jardín infantil 'Semillitas' de Osorno, la educadora Daniela planifica una experiencia de aprendizaje sobre 'la ciudad donde vivimos'. Quiere que sea una experiencia colaborativa significativa. Su grupo de NT2 tiene 28 niños y niñas de 5 años con diferentes intereses: algunos aman construir, otros dibujar, algunos prefieren dramatizar. Daniela reflexiona sobre el Objetivo de Aprendizaje 2 del núcleo Convivencia y Ciudadanía de las BCEP 2018: 'Participar en actividades y juegos colaborativos, planificando, acordando estrategias para un propósito común y asumiendo progresivamente responsabilidades en ellos'. También considera el OA 1 del núcleo Lenguajes Artísticos: 'Apreciar producciones artísticas de diversos contextos (en forma directa o a través de medios tecnológicos), describiendo y comparando algunas características visuales, musicales o escénicas (desplazamiento, ritmo, carácter expresivo, colorido, formas, diseño, entre otros)'. Daniela imagina un proyecto donde construyan una maqueta colectiva de Osorno, pero necesita estructurarlo para que realmente promueva colaboración auténtica, donde los niños se distribuyan roles, coordinen acciones, resuelvan problemas juntos, y celebren un logro compartido, no solo trabajen en paralelo.",
        "numero": 14
    },
    "parv-15": {
        "contexto": "La educadora Soledad trabaja en un jardín infantil de Copiapó con un grupo de NT1. Es marzo, inicio del año escolar, y necesita establecer las normas de convivencia para el grupo. El año anterior, simplemente escribió 4 normas en un cartel y las pegó en la pared: 'No gritar', 'No pegar', 'Ordenar', 'Escuchar'. Este año quiere hacer las cosas diferente. Reflexiona sobre el Objetivo de Aprendizaje 6 del núcleo Convivencia y Ciudadanía de las BCEP 2018: 'Respetar normas y acuerdos creados colaborativamente con pares y adultos, para el bienestar del grupo'. También considera el OA 7 de Identidad y Autonomía: 'Comunicar sus preferencias, opiniones, ideas, en diversas situaciones cotidianas y juegos'. Soledad ha leído sobre construcción participativa de normas, sobre formularlas en positivo (qué hacer, no qué NO hacer), sobre hacerlas pocas y comprensibles, sobre representarlas visualmente para niños no lectores. Quiere que las normas de su sala sean realmente significativas para los niños, que las sientan propias, que las comprendan profundamente. Debe diseñar un proceso de co-construcción de normas apropiado para niños de 4 años.",
        "numero": 15
    },
    "parv-16": {
        "contexto": "En el jardín infantil de Coyhaique, la educadora Pamela trabaja con un grupo de NT2. Está leyendo el cuento 'El pájaro del alma' y observa las reacciones de los niños ante los dilemas emocionales de la historia. Nota que algunos niños hacen comentarios empáticos ('el pájaro está triste porque perdió a su amigo'), mientras otros parecen no conectar emocionalmente con la narrativa. Pamela reflexiona sobre el Objetivo de Aprendizaje 3 del núcleo Identidad y Autonomía de las BCEP 2018: 'Reconocer emociones y sentimientos en otras personas, observadas en forma directa o a través de TICs'. También considera el OA 1: 'Comunicar a los demás, emociones y sentimientos tales como: amor, miedo, alegría, ira, que le provocan diversas narraciones o situaciones observadas en forma directa o a través de TICs'. Pamela sabe que la empatía —la capacidad de comprender y resonar con los estados emocionales de otros— es fundamental para el desarrollo socioemocional y moral. Quiere diseñar experiencias sistemáticas que desarrollen esta capacidad: lectura de cuentos con preguntas inferenciales, juegos de roles que permitan experimentar diferentes perspectivas, conversaciones sobre emociones. Necesita seleccionar las estrategias más efectivas.",
        "numero": 16
    },
    "parv-17": {
        "contexto": "El educador Felipe trabaja en un jardín infantil de La Serena con un grupo de NT1. Observa que al final de cada jornada, la sala queda desordenada: bloques esparcidos, libros fuera de lugar, materiales mezclados. Algunos niños ayudan voluntariamente, pero la mayoría espera que el adulto ordene. Felipe reflexiona sobre el Objetivo de Aprendizaje 8 del núcleo Convivencia y Ciudadanía de las BCEP 2018: 'Comprender que algunas de sus acciones y decisiones respecto al desarrollo de juegos y proyectos colectivos, influyen en las de sus pares'. También considera el OA 9: 'Reconocer, y progresivamente hacer respetar el derecho a expresarse libremente, a ser escuchado y a que su opinión sea tomada en cuenta; y en situaciones cotidianas y juegos'. Felipe quiere desarrollar en los niños un sentido de responsabilidad compartida por el espacio común, entendiendo que cuidar el entorno beneficia a todos. Ha investigado sobre rutinas de orden musicalizadas, contenedores rotulados con fotos, sistemas de responsabilidades rotativas. Quiere implementar un sistema que sea lúdico, que desarrolle autonomía, que no se sienta como castigo, sino como parte natural de la vida en comunidad.",
        "numero": 17
    },
    "parv-18": {
        "contexto": "En el jardín infantil 'Rayito de Luna' de Santiago centro, la educadora Carmen recibe la noticia de que una familia venezolana se integrará al grupo de NT1. Los padres de María José (4 años) están preocupados por la adaptación de su hija, quien habla con acento caribeño y extraña mucho su país. Carmen reflexiona sobre el Objetivo de Aprendizaje 4 del núcleo Convivencia y Ciudadanía de las BCEP 2018: 'Apreciar el significado que tienen para las personas y las comunidades, diversas manifestaciones culturales que se desarrollan en su entorno'. También considera el OA 3: 'Reconocer, y progresivamente hacer respetar el derecho a expresarse libremente, a ser escuchado y a que su opinión sea tomada en cuenta'. Carmen ve esta situación como una oportunidad pedagógica invaluable para trabajar interculturalidad, valoración de la diversidad, y enriquecimiento mutuo. Ha pensado en invitar a la familia a compartir música, comidas, cuentos de Venezuela; en incorporar palabras en diferentes acentos del español; en mostrar que la diversidad cultural suma. Necesita diseñar una estrategia de inclusión que valore la identidad de María José mientras enriquece a todo el grupo.",
        "numero": 18
    },
    "parv-19": {
        "contexto": "La educadora Rosa trabaja en un jardín infantil de Quilpué con un grupo de NT2. Durante una reunión de equipo, surge la idea de realizar un proyecto solidario con los niños. Rosa propone recolectar juguetes para donar a un jardín infantil de una comunidad más vulnerable. Sin embargo, se cuestiona: ¿cómo hacer que esto sea una experiencia de aprendizaje auténtica de solidaridad y no solo un gesto adulto donde los niños son instrumentos? Reflexiona sobre el Objetivo de Aprendizaje 7 del núcleo Convivencia y Ciudadanía de las BCEP 2018: 'Identificar objetos, comportamientos y situaciones de riesgo que pueden atentar contra su bienestar y seguridad, o la de los demás, proponiendo alternativas para enfrentarlas'. También considera el OA 2: 'Participar en actividades y juegos colaborativos, planificando, acordando estrategias para un propósito común y asumiendo progresivamente responsabilidades en ellos'. Rosa quiere que los niños comprendan por qué ayudar es importante, que conecten empáticamente con las necesidades de otros niños, que participen activamente en planificar y ejecutar el proyecto, que reflexionen sobre la experiencia. Necesita diseñar experiencias solidarias auténticas, no performativas.",
        "numero": 19
    },
    "parv-20": {
        "contexto": "El educador Gonzalo trabaja en un jardín infantil de Punta Arenas con un grupo de NT2. Durante el período de educación física al aire libre, nota que algunos niños tienen habilidades motrices muy desarrolladas (corren ágilmente, trepan con confianza), mientras otros son más cautelosos o tienen menor coordinación. En un juego de 'pilla-pilla', observa que los niños más lentos siempre son atrapados primero y algunos comienzan a frustrarse o a evitar participar. Gonzalo reflexiona sobre el Objetivo de Aprendizaje 1 del núcleo Corporalidad y Movimiento de las BCEP 2018: 'Manifestar iniciativa para resguardar el autocuidado de su cuerpo y su confortabilidad, en función de su propio bienestar'. También considera el OA 3: 'Tomar conciencia de su cuerpo, de algunas de sus características internas (tales como: ritmo cardíaco, de respiración), de su esquema y progresivamente de su tono corporal y lateralidad, por medio de juegos'. Gonzalo quiere diseñar experiencias motrices que sean inclusivas, que celebren los logros de cada niño según su propio punto de partida, que desarrollen habilidades sin generar comparaciones dañinas. Necesita repensar cómo estructura las actividades motrices.",
        "numero": 20
    }
}

# Guardar en JSON
with open('contextos_mejorados_11_20.json', 'w', encoding='utf-8') as f:
    json.dump(contextos_mejorados, f, ensure_ascii=False, indent=2)

print(f"✓ Creados {len(contextos_mejorados)} contextos pedagógicos mejorados")
print("✓ Guardado en: contextos_mejorados_11_20.json")

# Mostrar estadísticas
for key, data in contextos_mejorados.items():
    palabras = len(data['contexto'].split())
    print(f"  - {key}: {palabras} palabras")
