/* Contenido exclusivamente ficticio de la edición didáctica. */
const guide = require('./book-guide.js');
const section = (id, extra={}) => ({id,title:guide.find(s=>s.id===id).title,text:guide.find(s=>s.id===id).example,...extra});
const patio = 'assets/modelo-patio.png';
const taller = 'assets/modelo-taller.png';
const portada = 'assets/modelo-portada.png';
const voices = [
  {name:'Emilia',role:'Compañera 1',theme:'Aprender a pedir ayuda',answers:[
    'Recuerdo la primera prueba de impresión del cuadernillo. La imagen quedó muy oscura y pensamos que todo el trabajo se había perdido. Al comparar las pruebas descubrimos que podíamos corregirla. Me gustó que nadie tuviera que resolverlo solo.',
    'Aprendí a pedir ayuda antes de que el problema fuera más grande. En el taller comprendí que consultar no significa dejar de hacerse responsable. Después de recibir una explicación, yo debía probar y revisar mi parte.',
    'Nos describiría como un curso que aprende haciendo. Cuando organizamos la mesa de trabajo, cada uno mostró una manera distinta de ordenar los materiales. Terminamos eligiendo lo que funcionaba mejor para todos.',
    'Me ayudó una compañera que revisó conmigo los márgenes del primer diseño. No lo hizo por mí: me mostró cómo comprobarlos. Esa diferencia me permitió intentarlo después sin depender de ella.',
    'No esperen a saber hacerlo todo para comenzar. Empiecen, escuchen las observaciones y vuelvan a probar. A veces el avance se nota cuando uno compara el primer intento con el último.'
  ]},
  {name:'Diego',role:'Compañero 2',theme:'El valor de revisar',answers:[
    'Recuerdo una actividad de aniversario en la que debíamos preparar un cartel. Ensayamos varias composiciones y nos costó elegir. Cuando lo vimos desde lejos entendimos que una idea sencilla podía comunicar mejor que muchas cosas juntas.',
    'Me llevo la costumbre de revisar antes de entregar. Antes confiaba en que, si algo se veía bien en pantalla, estaba listo. Ahora miro los nombres, las medidas y la legibilidad en una prueba impresa.',
    'Somos un curso con bastante humor. Eso nos ayudaba cuando una tarea se hacía larga, aunque también tuvimos que aprender a detener la conversación para terminar. En una entrega repartimos tiempos de trabajo y de revisión.',
    'Un profesor nos pidió explicar nuestras decisiones en lugar de decir solamente que el diseño nos gustaba. Me hizo pensar en el lector y en lo que necesitaba encontrar primero en la página.',
    'Guarden sus primeros trabajos. Ver los errores antiguos ayuda a reconocer lo aprendido. No todo merece publicarse, pero cada intento puede mostrar una parte del camino.'
  ]},
  {name:'Sofía',role:'Compañera 3',theme:'Encontrar una voz propia',answers:[
    'Recuerdo cuando entrevisté a una compañera con la que casi no conversaba. Yo pensaba que conocía su experiencia escolar, pero me contó que un proyecto pequeño había sido muy importante para ella. Escucharla cambió la página que quería escribir.',
    'Aprendí que comunicar no es llenar un espacio. Hay que elegir qué merece estar ahí. En el anuario quité frases repetidas para que se entendiera mejor la idea principal y comprobé los cambios con la entrevistada.',
    'Nuestra generación tiene intereses diferentes. En un mismo equipo había quien prefería dibujar, quien escribía y quien revisaba medidas. Cuando reconocimos esas diferencias pudimos repartir mejor las tareas.',
    'Me influyó una devolución donde el docente señaló una idea que sí funcionaba antes de pedir cambios. Me ayudó a revisar sin pensar que todo estaba mal y a defender las decisiones que tenían sentido.',
    'Ojalá conservemos la curiosidad por las historias de los demás. Una pregunta hecha con atención puede acercarnos más que una fotografía donde todos aparecemos, pero nadie dice nada.'
  ]},
  {name:'Elena',role:'Docente 1',theme:'Escuchar para construir comunidad',answers:[
    'Distingo su disposición a probar cuando el trabajo tiene un propósito claro. En una actividad de memoria escolar observaron que sus recuerdos no eran idénticos. En vez de elegir una sola versión, buscaron qué aportaba cada mirada.',
    'Recuerdo una conversación en la que un estudiante corrigió con respeto un dato de una entrevista. El grupo volvió al registro y comprobó la información. Fue una buena muestra de que revisar también es cuidar a otros.',
    'Espero que conserven la capacidad de preguntar y de reconocer cuando no saben algo. En el estudio y en el trabajo encontrarán problemas nuevos. Saber buscar ayuda y evaluar una respuesta seguirá siendo necesario.',
    'Les aconsejaría cumplir los acuerdos pequeños. Llegar a una reunión, avisar si hay una dificultad y entregar lo comprometido construyen confianza. Esa confianza se forma con acciones repetidas, no con una sola promesa.',
    'Lleven sus aprendizajes con orgullo y con disposición a seguir aprendiendo. Un oficio cambia y las personas también. Lo importante es mantener el cuidado por el trabajo y por quienes lo reciben.'
  ]},
  {name:'Tomás',role:'Docente 2',theme:'Un oficio que se aprende con otros',answers:[
    'Esta generación ha aprendido a mostrar el proceso. Al principio muchos querían enseñar solamente el resultado final. Después comprendieron que un boceto, una prueba fallida y una corrección permiten explicar mejor una decisión.',
    'Recuerdo una jornada de encuadernación en la que algunos terminaron antes y ayudaron a revisar el orden de los pliegos de sus compañeros. Lo valioso fue que orientaron sin reemplazar el trabajo de cada uno.',
    'Quisiera que conservaran la atención a los detalles. Una medida equivocada puede afectar una pieza completa. Revisar a tiempo cuida materiales, esfuerzo y la confianza de quien encargó el trabajo.',
    'Antes de aceptar una tarea, pregunten qué se necesita y para cuándo. Luego revisen si cuentan con los recursos. Si aparece una dificultad, comuníquenla de inmediato y propongan una alternativa posible.',
    'Un buen trabajo lleva la huella de muchas personas. Reconozcan a quienes les enseñaron, compartan lo que saben y no dejen de practicar. La experiencia crece cuando se trabaja con atención.'
  ]}
];
const questions = [
  ['¿Qué experiencia recuerdas y por qué?','¿Qué aprendizaje te llevas?','¿Cómo describirías a nuestra generación?','¿Qué persona o momento influyó en ti?','¿Qué mensaje dejarías en el anuario?'],
  ['¿Qué distingue a esta generación?','¿Qué momento compartido recuerda?','¿Qué aprendizaje deberían conservar?','¿Qué consejo les daría para la próxima etapa?','¿Qué mensaje dejaría en el anuario?']
];
const interviews = voices.map((voice,i)=>({id:i===0?'entrevistas':'entrevista-'+(i+1),title:voice.theme,kicker:`Entrevista ${i+1} · ${voice.role}`,text:`Persona entrevistada: ${voice.name}, personaje ficticio.\nRegistro escrito simulado: no existe audio de esta conversación. En tu trabajo debes conservar la grabación real y transcribirla fielmente.\n\n`+voice.answers.map((answer,j)=>`${questions[i<3?0:1][j]}\n${voice.name}: ${answer}`).join('\n\n')}));
const memory = `La mañana del aniversario, nuestro cartel seguía sobre una mesa y todavía faltaba pegar algunas letras. Afuera comenzaban las actividades, pero nosotros discutíamos qué color usar para que el mensaje se leyera desde el patio. Alguien propuso mirarlo a varios metros de distancia. Esa prueba sencilla terminó la discusión.\n\nMientras un grupo ajustaba las letras, otros buscaron materiales y ordenaron lo que sobraba. No todo salió como esperábamos: una esquina se despegó y hubo que reforzarla antes de llevar el cartel afuera. La dificultad nos obligó a repartir mejor las tareas. Esta vez preguntamos quién necesitaba ayuda en lugar de asumir que cada uno ya sabía qué hacer.\n\nCuando finalmente lo instalamos, nos quedamos un momento observándolo. No era el trabajo más complejo que habíamos hecho, pero reconocíamos decisiones de todos. La fotografía que elegí para esta página representa esa pausa después del esfuerzo, cuando ya no estábamos apurados y podíamos conversar.\n\nCon el tiempo olvidé algunos detalles de la actividad, pero conservé esa sensación de haber resuelto algo juntos. El aniversario me enseñó que pertenecer a un curso no depende solamente de compartir una sala. También se construye cuando una tarea nos obliga a escuchar, colaborar y cuidar lo que hacemos.`;
const project = `EL DESAFÍO\nCrear un cuadernillo que pudiera abrirse con facilidad y conservar sus páginas ordenadas. Queríamos que la encuadernación acompañara el contenido y resistiera la lectura.\n\nCÓMO LO HICIMOS\nPrimero dibujamos una maqueta y distribuimos los textos. Después imprimimos una prueba para comprobar el orden de lectura, los márgenes y el tamaño de las letras. Al doblar los pliegos descubrimos que algunas páginas no coincidían: corregimos la organización antes de continuar.\n\nMarcamos los puntos de costura sobre una guía y practicamos el recorrido del hilo. Durante el montaje revisamos la tensión para que el libro pudiera abrirse sin deformarse. Un compañero comprobó la secuencia de páginas y otro observó la terminación.\n\nLO QUE APRENDIMOS\nAprendimos que la calidad no aparece solamente al final. Cada decisión afecta la siguiente: si la maqueta está desordenada, la encuadernación no puede arreglarla. La prueba de impresión y la revisión compartida nos permitieron corregir a tiempo y explicar cómo habíamos construido el objeto.`;
const farewell = `Llegamos a cuarto medio con experiencias distintas y terminamos compartiendo una mesa de trabajo. En ella quedaron conversaciones, papeles, pruebas y errores que nos enseñaron más de lo que imaginábamos. No todos recordaremos los mismos momentos, pero cada uno lleva una parte de lo que vivimos juntos.\n\nMe despido agradeciendo las ayudas pequeñas: una explicación antes de entregar, una pregunta hecha a tiempo y la paciencia de quien esperaba mientras yo terminaba. También me llevo las dificultades, porque nos obligaron a hablar con más claridad y a hacernos responsables de nuestros acuerdos.\n\nNo sé dónde estaremos dentro de algunos años. Espero que podamos mirar estas páginas y reconocer algo nuestro: el humor, el esfuerzo y la disposición a volver a intentar. El colegio termina como etapa; lo que aprendimos con otros sigue acompañándonos.`;
module.exports = [
  section('portada',{title:'Huellas en papel',kicker:'Anuario 2026 · 4°D TP · CEST',image:portada,cover:true}),
  section('dedicatoria'),section('indice'),section('presentacion',{image:patio,caption:'Una conversación imaginada en el patio. Ilustración generada con IA para este modelo.'}),
  ...interviews,
  {id:'editada',title:'«Consultar no significa dejar de hacerse responsable»',kicker:'Entrevista editada · Emilia',text:'Emilia es una estudiante ficticia de cuarto medio de la especialidad de Gráfica. En esta entrevista de ejemplo recuerda una prueba de impresión y explica cómo cambió su manera de pedir ayuda. Su experiencia permite observar la relación entre el trabajo individual y la colaboración, una idea que recorre este anuario.\n\n'+[0,1,4].map(j=>`${questions[0][j]}\n${voices[0].answers[j]}`).join('\n\n'),image:patio,caption:'Escena de conversación escolar creada con IA; no retrata a una entrevistada real.'},
  {id:'aniversario',title:'El cartel que terminamos juntos',kicker:'Aniversarios del colegio · Memoria escolar',text:memory,image:patio,caption:'Patio y preparación de una celebración imaginaria. Ilustración con IA, 2026.'},
  section('jefes'),section('jefeactual'),section('curso',{image:patio,caption:'Grupo escolar ficticio. Sustituye esta ilustración con IA por una fotografía autorizada de tu curso.'}),
  {id:'especialidad',title:'Un libro hecho por nuestras manos',kicker:'Algo creado en la especialidad · Gráfica',text:project,image:taller,caption:'Proceso de encuadernación imaginado. Ilustración generada con IA para la edición de ejemplo.'},
  {id:'ficha',title:'Del primer pliego a la última puntada',kicker:'Proyecto de especialidad · Ficha y proceso',text:'PRODUCTO\nCuadernillo de memoria escolar con encuadernación cosida.\n\nEQUIPO FICTICIO\nAlex: textos y revisión; Emilia: diseño; Diego: pruebas; Sofía: orden de páginas y pies de imagen.\n\nMATERIALES DEL EJEMPLO\nPapel para interiores, cartulina para cubierta, hilo de encuadernación, aguja adecuada, plegadera, regla y base de trabajo.\n\nSECUENCIA\n1. Diseñar la maqueta.\n2. Imprimir una prueba y comprobar el orden.\n3. Doblar y reunir los pliegos.\n4. Marcar los puntos con la guía del taller.\n5. Coser con supervisión docente y comprobar la apertura.\n6. Revisar y corregir la terminación.\n\nCONTROL DE CALIDAD\nTexto legible, páginas completas y ordenadas, costura estable y cubierta alineada. Las medidas y los materiales definitivos se acuerdan en Gráfica.',image:taller},
  section('comun'),section('favorita',{image:taller,caption:'Taller ficticio de producción gráfica. Ilustración con IA, 2026.'}),
  {id:'amigos',title:'Las pausas también son parte de la historia',kicker:'Fotos con amigos · Galería de ejemplo 1',text:'Imagen 1. Alex, Emilia, Diego y Sofía, personajes ficticios, comparten una entrevista en el patio. Ilustración con IA, 2026.\n\nEscucharnos también fue una forma de conocernos. En el anuario real, este espacio lleva una fotografía propia con nombres verificados y permiso para publicarla.\n\nImagen 2. Colaboración en un taller de Gráfica imaginario. Ilustración con IA, 2026.\n\nPedir ayuda hizo que el trabajo avanzara.',image:patio,secondImage:taller},
  {id:'galeria',title:'Lo que cabe en un recuerdo',kicker:'Fotos con amigos · Galería de ejemplo 2',text:'Imagen 3. Libro abierto y aves de papel en un patio imaginario. Ilustración con IA, 2026.\n\nLos recuerdos toman otra forma cuando los compartimos.\n\nImagen 4. Conversación entre personajes ficticios, reutilizada para cerrar la galería. Ilustración con IA, 2026.\n\nUna pausa compartida también merece una página.\n\nEsta galería muestra cómo escribir pies completos. En tu versión selecciona cuatro fotografías diferentes, autorizadas y relacionadas con tu historia.',image:portada,secondImage:patio},
  {id:'despedida',title:'Lo que sigue con nosotros',kicker:'Despedida · Cierre personal',text:farewell},
  section('agradecimientos'),section('creditos'),section('contraportada',{image:portada,back:true})
];
