/* Catálogo de muebles de Mi casa. Generado por herramientas de carga.
 * Arte: Furniture Kit de Kenney (kenney.nl), licencia CC0.
 * Las variantes de color se obtienen rotando el matiz del PNG original.
 * No editar a mano: se regenera.
 */
window.CATALOGO_CASA = [
  {id:"bedSingle",nom:"Cama",fam:"dormitorio",xp:0,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"bedDouble",nom:"Cama de dos plazas",fam:"dormitorio",xp:0,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"bedBunk",nom:"Camarote",fam:"dormitorio",xp:0,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"bookcaseClosedWide",nom:"Estante ancho",fam:"estudio",xp:0,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"bookcaseClosedDoors",nom:"Estante con puertas",fam:"estudio",xp:0,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"bookcaseClosed",nom:"Repisa cerrada",fam:"estudio",xp:0,motivo:"Primeras clases",sup:46,apila:false,plano:false},
  {id:"cardboardBoxClosed",nom:"Caja cerrada",fam:"deco",xp:120,motivo:"Primeras clases",sup:0,apila:true,plano:false},
  {id:"books",nom:"Libros",fam:"deco",xp:120,motivo:"Primeras clases",sup:0,apila:true,plano:false},
  {id:"bear",nom:"Peluche",fam:"deco",xp:120,motivo:"Primeras clases",sup:0,apila:true,plano:false},
  {id:"cabinetBed",nom:"Cómoda",fam:"dormitorio",xp:150,motivo:"Tres clases completas",sup:34,apila:false,plano:false},
  {id:"cabinetBedDrawer",nom:"Cómoda con cajón",fam:"dormitorio",xp:150,motivo:"Tres clases completas",sup:34,apila:false,plano:false},
  {id:"cabinetBedDrawerTable",nom:"Cómoda con mesa",fam:"dormitorio",xp:150,motivo:"Tres clases completas",sup:34,apila:false,plano:false},
  {id:"rugRectangle",nom:"Alfombra rectangular",fam:"alfombra",xp:180,motivo:"Primeras clases",sup:0,apila:false,plano:true},
  {id:"rugRectangle__naranja",nom:"Alfombra rectangular naranja",fam:"alfombra",xp:180,motivo:"Primeras clases",sup:0,apila:false,plano:true},
  {id:"rugRectangle__rojo",nom:"Alfombra rectangular rojo",fam:"alfombra",xp:180,motivo:"Primeras clases",sup:0,apila:false,plano:true},
  {id:"bookcaseOpen",nom:"Estante",fam:"estudio",xp:200,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"bookcaseOpenLow",nom:"Estante bajo",fam:"estudio",xp:200,motivo:"Tres clases completas",sup:34,apila:false,plano:false},
  {id:"chair",nom:"Silla",fam:"estudio",xp:200,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"cardboardBoxOpen",nom:"Caja abierta",fam:"deco",xp:260,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"coatRack",nom:"Perchero de pared",fam:"deco",xp:260,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"ceilingFan",nom:"Ventilador",fam:"deco",xp:260,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"sideTable",nom:"Velador",fam:"dormitorio",xp:300,motivo:"Ensayo rendido",sup:36,apila:false,plano:false},
  {id:"sideTableDrawers",nom:"Velador con cajones",fam:"dormitorio",xp:300,motivo:"Ensayo rendido",sup:36,apila:false,plano:false},
  {id:"rugRectangle__amarillo",nom:"Alfombra rectangular amarillo",fam:"alfombra",xp:360,motivo:"Tres clases completas",sup:0,apila:false,plano:true},
  {id:"rugRectangle__celeste",nom:"Alfombra rectangular celeste",fam:"alfombra",xp:360,motivo:"Tres clases completas",sup:0,apila:false,plano:true},
  {id:"rugRectangle__verde",nom:"Alfombra rectangular verde",fam:"alfombra",xp:360,motivo:"Tres clases completas",sup:0,apila:false,plano:true},
  {id:"chairCushion",nom:"Silla con cojín",fam:"estudio",xp:380,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"chairDesk",nom:"Silla de escritorio",fam:"estudio",xp:380,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"chairRounded",nom:"Silla redondeada",fam:"estudio",xp:380,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"lampRoundTable",nom:"Lamparita",fam:"deco",xp:420,motivo:"Ensayo rendido",sup:0,apila:true,plano:false},
  {id:"lampRoundFloor",nom:"Lámpara de pie redonda",fam:"deco",xp:420,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"coatRackStanding",nom:"Perchero",fam:"deco",xp:420,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"bench",nom:"Banca",fam:"living",xp:500,motivo:"Primeras clases",sup:24,apila:false,plano:false},
  {id:"benchCushionLow",nom:"Banca baja",fam:"living",xp:500,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"benchCushion",nom:"Banca con cojín",fam:"living",xp:500,motivo:"Primeras clases",sup:26,apila:false,plano:false},
  {id:"rugRectangle__azul",nom:"Alfombra rectangular azul",fam:"alfombra",xp:560,motivo:"Ensayo rendido",sup:0,apila:false,plano:true},
  {id:"rugRectangle__morado",nom:"Alfombra rectangular morado",fam:"alfombra",xp:560,motivo:"Ensayo rendido",sup:0,apila:false,plano:true},
  {id:"rugRectangle__rosa",nom:"Alfombra rectangular rosa",fam:"alfombra",xp:560,motivo:"Ensayo rendido",sup:0,apila:false,plano:true},
  {id:"lampSquareTable",nom:"Lámpara de mesa",fam:"deco",xp:600,motivo:"Unidad terminada",sup:0,apila:true,plano:false},
  {id:"lampSquareFloor",nom:"Lámpara de pie",fam:"deco",xp:600,motivo:"Unidad terminada",sup:0,apila:false,plano:false},
  {id:"lampSquareCeiling",nom:"Lámpara de techo",fam:"deco",xp:600,motivo:"Unidad terminada",sup:0,apila:false,plano:false},
  {id:"computerScreen",nom:"Monitor",fam:"estudio",xp:600,motivo:"Unidad terminada",sup:0,apila:true,plano:false},
  {id:"computerMouse",nom:"Mouse",fam:"estudio",xp:600,motivo:"Unidad terminada",sup:0,apila:true,plano:false},
  {id:"computerKeyboard",nom:"Teclado",fam:"estudio",xp:600,motivo:"Unidad terminada",sup:0,apila:true,plano:false},
  {id:"cabinetTelevision",nom:"Mueble de TV",fam:"living",xp:750,motivo:"Tres clases completas",sup:32,apila:false,plano:false},
  {id:"cabinetTelevisionDoors",nom:"Mueble de TV con puertas",fam:"living",xp:750,motivo:"Tres clases completas",sup:32,apila:false,plano:false},
  {id:"loungeChair",nom:"Sillón",fam:"living",xp:750,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"rugRound",nom:"Alfombra redonda",fam:"alfombra",xp:780,motivo:"Unidad terminada",sup:0,apila:false,plano:true},
  {id:"rugRound__naranja",nom:"Alfombra redonda naranja",fam:"alfombra",xp:780,motivo:"Unidad terminada",sup:0,apila:false,plano:true},
  {id:"rugRound__rojo",nom:"Alfombra redonda rojo",fam:"alfombra",xp:780,motivo:"Unidad terminada",sup:0,apila:false,plano:true},
  {id:"plantSmall3",nom:"Cactus",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow",nom:"Cojín",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow__amarillo",nom:"Cojín amarillo",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow__azul",nom:"Cojín azul",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow__celeste",nom:"Cojín celeste",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong",nom:"Cojín largo",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong__amarillo",nom:"Cojín largo amarillo",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong__azul",nom:"Cojín largo azul",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong__celeste",nom:"Cojín largo celeste",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong__morado",nom:"Cojín largo morado",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong__naranja",nom:"Cojín largo naranja",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong__rojo",nom:"Cojín largo rojo",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong__rosa",nom:"Cojín largo rosa",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillowLong__verde",nom:"Cojín largo verde",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow__morado",nom:"Cojín morado",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow__naranja",nom:"Cojín naranja",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow__rojo",nom:"Cojín rojo",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow__rosa",nom:"Cojín rosa",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pillow__verde",nom:"Cojín verde",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"trashcan",nom:"Papelero",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"speaker",nom:"Parlante",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"speakerSmall",nom:"Parlante chico",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"pottedPlant",nom:"Planta",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"plantSmall2",nom:"Planta chica",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"radio",nom:"Radio",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"plantSmall1",nom:"Suculenta",fam:"deco",xp:820,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"kitchenBar",nom:"Barra",fam:"cocina",xp:900,motivo:"Primeras clases",sup:42,apila:false,plano:false},
  {id:"kitchenBarEnd",nom:"Punta de barra",fam:"cocina",xp:900,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"dryer",nom:"Secadora",fam:"cocina",xp:900,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"desk",nom:"Escritorio",fam:"estudio",xp:900,motivo:"Nivel alto",sup:42,apila:false,plano:false},
  {id:"deskCorner",nom:"Escritorio esquinero",fam:"estudio",xp:900,motivo:"Nivel alto",sup:42,apila:false,plano:false},
  {id:"laptop",nom:"Notebook",fam:"estudio",xp:900,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"loungeChairRelax",nom:"Sillón reclinable",fam:"living",xp:1000,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"loungeSofa",nom:"Sofá",fam:"living",xp:1000,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"loungeSofaCorner",nom:"Sofá esquinero",fam:"living",xp:1000,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"rugSquare",nom:"Alfombra cuadrada",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugSquare__amarillo",nom:"Alfombra cuadrada amarillo",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugSquare__azul",nom:"Alfombra cuadrada azul",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugSquare__celeste",nom:"Alfombra cuadrada celeste",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugSquare__morado",nom:"Alfombra cuadrada morado",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugSquare__naranja",nom:"Alfombra cuadrada naranja",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugSquare__rojo",nom:"Alfombra cuadrada rojo",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugSquare__rosa",nom:"Alfombra cuadrada rosa",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugSquare__verde",nom:"Alfombra cuadrada verde",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded",nom:"Alfombra ovalada",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded__amarillo",nom:"Alfombra ovalada amarillo",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded__azul",nom:"Alfombra ovalada azul",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded__celeste",nom:"Alfombra ovalada celeste",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded__morado",nom:"Alfombra ovalada morado",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded__naranja",nom:"Alfombra ovalada naranja",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded__rojo",nom:"Alfombra ovalada rojo",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded__rosa",nom:"Alfombra ovalada rosa",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRounded__verde",nom:"Alfombra ovalada verde",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRound__amarillo",nom:"Alfombra redonda amarillo",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRound__azul",nom:"Alfombra redonda azul",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRound__celeste",nom:"Alfombra redonda celeste",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRound__morado",nom:"Alfombra redonda morado",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRound__rosa",nom:"Alfombra redonda rosa",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"rugRound__verde",nom:"Alfombra redonda verde",fam:"alfombra",xp:1020,motivo:"Nivel alto",sup:0,apila:false,plano:true},
  {id:"kitchenBlender",nom:"Juguera",fam:"cocina",xp:1200,motivo:"Tres clases completas",sup:0,apila:true,plano:false},
  {id:"kitchenCabinet",nom:"Mueble de cocina",fam:"cocina",xp:1200,motivo:"Tres clases completas",sup:38,apila:false,plano:false},
  {id:"kitchenCabinetCornerInner",nom:"Mueble esquinero",fam:"cocina",xp:1200,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"table",nom:"Mesa",fam:"living",xp:1300,motivo:"Unidad terminada",sup:44,apila:false,plano:false},
  {id:"loungeSofaOttoman",nom:"Sofá con otomana",fam:"living",xp:1300,motivo:"Unidad terminada",sup:0,apila:false,plano:false},
  {id:"loungeSofaLong",nom:"Sofá largo",fam:"living",xp:1300,motivo:"Unidad terminada",sup:0,apila:false,plano:false},
  {id:"bathroomMirror",nom:"Espejo",fam:"baño",xp:1400,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"bathroomSink",nom:"Lavamanos",fam:"baño",xp:1400,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"bathroomCabinet",nom:"Mueble de baño",fam:"baño",xp:1400,motivo:"Primeras clases",sup:0,apila:false,plano:false},
  {id:"kitchenCabinetDrawer",nom:"Cajonera",fam:"cocina",xp:1500,motivo:"Ensayo rendido",sup:38,apila:false,plano:false},
  {id:"kitchenCabinetDrawer 1",nom:"Cajonera doble",fam:"cocina",xp:1500,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"kitchenCabinetCornerRound",nom:"Mueble curvo",fam:"cocina",xp:1500,motivo:"Ensayo rendido",sup:0,apila:false,plano:false},
  {id:"tableCloth",nom:"Mesa con mantel",fam:"living",xp:1650,motivo:"Nivel alto",sup:44,apila:false,plano:false},
  {id:"tableCrossCloth",nom:"Mesa cruzada con mantel",fam:"living",xp:1650,motivo:"Nivel alto",sup:44,apila:false,plano:false},
  {id:"tableCoffee",nom:"Mesa de centro",fam:"living",xp:1650,motivo:"Nivel alto",sup:30,apila:false,plano:false},
  {id:"tableCoffeeSquare",nom:"Mesa de centro cuadrada",fam:"living",xp:1650,motivo:"Nivel alto",sup:30,apila:false,plano:false},
  {id:"tableCross",nom:"Mesa de patas cruzadas",fam:"living",xp:1650,motivo:"Nivel alto",sup:44,apila:false,plano:false},
  {id:"tableCoffeeGlass",nom:"Mesa de vidrio",fam:"living",xp:1650,motivo:"Nivel alto",sup:30,apila:false,plano:false},
  {id:"tableCoffeeGlassSquare",nom:"Mesa de vidrio cuadrada",fam:"living",xp:1650,motivo:"Nivel alto",sup:30,apila:false,plano:false},
  {id:"tableGlass",nom:"Mesa de vidrio grande",fam:"living",xp:1650,motivo:"Nivel alto",sup:44,apila:false,plano:false},
  {id:"tableRound",nom:"Mesa redonda",fam:"living",xp:1650,motivo:"Nivel alto",sup:44,apila:false,plano:false},
  {id:"televisionVintage",nom:"Tele antigua",fam:"living",xp:1650,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"televisionAntenna",nom:"Tele con antena",fam:"living",xp:1650,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"televisionModern",nom:"Televisor",fam:"living",xp:1650,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"shower",nom:"Ducha",fam:"baño",xp:1700,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"bathtub",nom:"Tina",fam:"baño",xp:1700,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"toilet",nom:"WC",fam:"baño",xp:1700,motivo:"Tres clases completas",sup:0,apila:false,plano:false},
  {id:"kitchenCabinetUpperDouble",nom:"Alto doble",fam:"cocina",xp:1850,motivo:"Unidad terminada",sup:0,apila:false,plano:false},
  {id:"kitchenCabinetUpperCorner",nom:"Alto esquinero",fam:"cocina",xp:1850,motivo:"Unidad terminada",sup:0,apila:false,plano:false},
  {id:"kitchenCabinetUpper",nom:"Mueble alto",fam:"cocina",xp:1850,motivo:"Unidad terminada",sup:0,apila:false,plano:false},
  {id:"kitchenCabinetUpperLow",nom:"Alto bajo",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"kitchenCoffeeMachine",nom:"Cafetera",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"kitchenStove",nom:"Cocina",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"kitchenStoveElectric",nom:"Cocina eléctrica",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"kitchenFridgeSmall",nom:"Frigobar",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:34,apila:false,plano:false},
  {id:"washer",nom:"Lavadora",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"kitchenSink",nom:"Lavaplatos",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"kitchenMicrowave",nom:"Microondas",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:true,plano:false},
  {id:"stoolBar",nom:"Piso alto",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:30,apila:false,plano:false},
  {id:"stoolBarSquare",nom:"Piso cuadrado",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:30,apila:false,plano:false},
  {id:"kitchenFridge",nom:"Refrigerador",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"kitchenFridgeBuiltIn",nom:"Refrigerador empotrado",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:false,plano:false},
  {id:"washerDryerStacked",nom:"Torre de lavado",fam:"cocina",xp:2200,motivo:"Nivel alto",sup:0,apila:false,plano:false}
];
