window.SIMCE_U3S7_DATA = {
  concepts: [
    { id:'c1', case:'La presidenta del centro de estudiantes presenta una propuesta ante el consejo escolar.', prompt:'¿Quién cumple el papel de emisor?', options:['La presidenta del centro de estudiantes','El consejo escolar','La propuesta presentada','La comunidad completa'] },
    { id:'c2', case:'Un dirigente vecinal habla en una audiencia municipal para solicitar cambios al proyecto de una plaza.', prompt:'¿Cuál es la audiencia inmediata?', options:['Los habitantes que no asistieron','Las autoridades de la audiencia','Los arquitectos de otras comunas','Los lectores de un periódico'] },
    { id:'c3', case:'“Les propongo probar esta medida durante un mes y revisar juntos sus resultados”.', prompt:'¿Cuál es el propósito principal?', options:['Narrar una experiencia pasada','Explicar el origen de un problema','Convencer de aplicar una propuesta','Entretener mediante una anécdota'] },
    { id:'c4', case:'“La biblioteca debe ampliar su horario porque muchos estudiantes salen de talleres cuando ya está cerrada”.', prompt:'¿Qué elemento del discurso expresa la idea defendida?', options:['La tesis','La audiencia','El tono','La cita'] },
    { id:'c5', case:'“En una encuesta respondida por 280 estudiantes, 173 indicaron que usan la biblioteca después de las 16:00”.', prompt:'¿Qué recurso se utiliza?', options:['Una evidencia cuantitativa','Una pregunta retórica','Una generalización','Una amenaza'] },
    { id:'c6', case:'“Es cierto que abrir más tiempo exige organización; sin embargo, podemos comenzar dos días a la semana”.', prompt:'¿Qué estrategia se reconoce?', options:['Una concesión seguida de respuesta','Una repetición sin información','Una descalificación personal','Un cambio completo de tema'] },
    { id:'c7', case:'“¿Queremos un patio en el que nadie converse aunque todos estén juntos?”.', prompt:'¿Qué función cumple la pregunta?', options:['Solicitar un dato desconocido','Invitar a revisar una situación','Comprobar una fecha exacta','Presentar una definición'] },
    { id:'c8', case:'El orador reconoce límites, evita burlas y propone evaluar la medida antes de volverla permanente.', prompt:'¿Qué tono predomina?', options:['Dialogante y prudente','Burlesco y agresivo','Indiferente y distante','Alarmista y autoritario'] }
  ],
  conceptAnswers: { c1:0,c2:1,c3:2,c4:0,c5:0,c6:0,c7:1,c8:0 },
  model: {
    text:'Compañeros, algunos creen que pedir diez minutos sin teléfonos al comenzar la reunión resolverá todas nuestras distracciones. No será así. Sin embargo, una pausa breve puede ayudarnos a leer la tabla de acuerdos antes de opinar. Propongo probarla en las próximas tres reuniones y comparar cuántos acuerdos debemos aclarar después. Si no mejora el trabajo, la retiramos. No les pido confiar en una promesa, sino aceptar una prueba que podremos evaluar juntos.',
    prompt:'¿Qué rasgo vuelve prudente la propuesta del emisor?',
    options:['Afirma que la pausa eliminará cualquier distracción.','Limita la medida, define cómo observarla y acepta retirarla.','Reemplaza los acuerdos por opiniones de los participantes.','Descalifica a quienes prefieren usar teléfonos en la reunión.'],
    answer:'B',
    explanation:'La propuesta es acotada y comprobable: dura tres reuniones, tiene un indicador y puede retirarse. La respuesta integra esas tres pistas; no se queda con una frase aislada.'
  },
  units: [
    {
      id:'t1', label:'Texto 1 · Discurso escolar', title:'El patio que no queremos vaciar',
      source:'Discurso original para práctica de comprensión lectora.',
      body:`
        <p><strong>Compañeros, profesores y representantes del consejo escolar:</strong></p>
        <p>Durante las últimas semanas hemos discutido si el teléfono debería desaparecer por completo de los recreos. La preocupación no es inventada. En el patio vemos grupos sentados juntos que apenas se hablan, estudiantes que atraviesan una conversación para mirar una notificación y partidos que se detienen porque alguien quiere grabar una jugada. Sería cómodo concluir que el aparato es el único responsable y que basta con prohibirlo para recuperar la convivencia. Pero una explicación cómoda no siempre es una explicación suficiente.</p>
        <p>El centro de estudiantes observó los tres recreos durante cinco días y aplicó una encuesta voluntaria respondida por 312 alumnos. Según ese registro, 198 dijeron que usan el teléfono principalmente para escuchar música, coordinar trabajos o avisar a su familia; 147 reconocieron que a veces lo revisan sin una razón concreta. Los datos no prueban que el teléfono sea inofensivo ni que cause por sí solo el aislamiento. Sí muestran que su uso cumple funciones diferentes. Una norma que trate todas esas situaciones como si fueran iguales puede ser sencilla de vigilar, pero difícil de considerar justa.</p>
        <p>Por eso no proponemos elegir entre un patio dominado por pantallas y otro vigilado mediante castigos. Proponemos organizar durante seis semanas tres zonas visibles. En la primera habrá mesas para conversar, jugar ajedrez o compartir colación sin teléfonos sobre la mesa. En la segunda se mantendrá el uso personal, siempre que no se fotografíe ni grabe a otros sin autorización. La tercera ocupará parte de la multicancha y tendrá materiales prestables para actividades breves. Nadie será obligado a participar en una zona, pero cada estudiante deberá respetar la regla del lugar que elija.</p>
        <p>Algunos profesores han advertido que dividir el patio puede trasladar el problema en vez de resolverlo. Tienen razón en una parte: pintar límites no crea por sí solo una conversación ni evita un conflicto. Por eso la propuesta incluye mediadores estudiantiles, un registro semanal de incidentes y una consulta corta al finalizar la cuarta semana. Si las zonas se usan poco, si aumentan las discusiones o si la mayoría declara que no ayudan, habrá que modificarlas. Presentar una idea no significa defenderla incluso cuando la experiencia la contradice.</p>
        <p>También nos preguntaron por qué no empezamos directamente con una prohibición total. Porque una prohibición impediría ciertas conductas, pero no enseñaría a decidir cuándo una tecnología aporta y cuándo interrumpe. Fuera del colegio nadie instalará una caja para guardar nuestros teléfonos antes de cada conversación. Aprender a regular el uso puede ser más lento que obedecer una orden, pero es una habilidad que podremos trasladar a otros espacios.</p>
        <p>No afirmamos que esta propuesta resolverá la convivencia. Afirmamos algo más limitado: permite probar una organización, reunir evidencia y corregirla sin convertir una sospecha en una regla permanente. Les pedimos autorizar las seis semanas y nombrar una comisión con estudiantes, asistentes y profesores que revise los resultados. La pregunta no es si estamos a favor o en contra del teléfono. La pregunta es qué condiciones necesitamos para volver a mirarnos cuando compartimos el mismo patio.</p>`
    },
    {
      id:'t2', label:'Texto 2 · Intervención ciudadana', title:'Antes de construir el paseo',
      source:'Intervención original ante una audiencia municipal.',
      body:`
        <p><strong>Señora alcaldesa, integrantes del concejo y vecinos:</strong></p>
        <p>Quienes vivimos junto al estero conocemos el atractivo del proyecto presentado esta tarde. Un paseo con luminarias, bancas y una ciclovía puede recuperar un borde que hoy parece abandonado. Los comerciantes esperan más visitantes; varias familias quieren una ruta segura para caminar; los estudiantes de la escuela cercana necesitan un trayecto separado de los automóviles. No venimos a negar esas necesidades. Venimos a pedir que el municipio cambie el orden de sus decisiones: primero estudiar cómo se mueve el agua y luego definir qué se construye.</p>
        <p>La presentación técnica atribuye las inundaciones principalmente a la basura acumulada. El comité revisó las actas de emergencia de los últimos doce años. En dieciocho episodios el agua llegó a viviendas o interrumpió una calle. Nueve actas mencionan residuos junto con desagües estrechos; seis registran lluvias intensas y aumento del caudal, aunque no describen basura; tres no precisan una causa. Estos datos no permiten absolver a quienes arrojan residuos. Tampoco permiten afirmar que limpiar el cauce bastará para proteger el paseo.</p>
        <p>Hay otra información que el diseño muestra solo como decoración. En el plano, la vegetación de la ribera aparece reemplazada por una franja continua de pavimento y pequeños jardines elevados. Sin embargo, las raíces estabilizan parte del suelo y los sectores sin pavimentar absorben agua. No aseguramos que cada árbol deba conservarse ni que toda superficie dura sea peligrosa. Pedimos un estudio que compare escenarios: cuánto agua retiene hoy el borde, cuánto retendría con el proyecto y qué ocurriría si coinciden una lluvia intensa y un caudal alto.</p>
        <p>Sabemos que un nuevo estudio cuesta dinero y puede retrasar la obra. Ese costo debe compararse con otro: reparar un paseo construido en un lugar que se inunda o levantar barreras después de que las viviendas hayan recibido agua. Los comerciantes temen perder la temporada de verano. Una alternativa es ejecutar primero los tramos alejados de las zonas críticas y mantener accesos provisorios, mientras se estudia el sector bajo. Así, la precaución no se convierte en inmovilidad.</p>
        <p>También pedimos que los vecinos participen en la observación. No para reemplazar a ingenieros ni para decidir mediante una votación cómo funciona el agua. Los relatos de quienes han visto crecer el estero pueden orientar dónde medir y qué fechas revisar. Una vecina recuerda que el agua entró por una calle que el mapa actual considera segura; un antiguo trabajador municipal sabe dónde se cerró un canal hace veinte años. Esos testimonios no son conclusiones técnicas, pero sí preguntas que un estudio serio debería comprobar.</p>
        <p>El paseo puede ser una buena obra. Precisamente por eso no debe depender de una explicación incompleta. Solicitamos publicar los antecedentes usados para atribuir las inundaciones a la basura, financiar un estudio hidráulico independiente y dividir la construcción en etapas. Si los resultados confirman el diseño, la comunidad tendrá razones más firmes para apoyarlo. Si muestran un riesgo, todavía estaremos a tiempo de corregir. Construir rápido puede producir una fotografía inaugural; construir después de preguntar puede producir un espacio que siga sirviendo cuando termine la ceremonia.</p>`
    },
    {
      id:'t3', label:'Texto 3 · Discurso de cierre', title:'Aprender a pedir ayuda',
      source:'Discurso original de una estudiante al cerrar su práctica de taller.',
      body:`
        <p><strong>Profesores, compañeros y estudiantes que el próximo año entrarán al taller:</strong></p>
        <p>Cuando comenzamos la especialidad, muchos imaginábamos que ser competente significaba trabajar sin detenerse y no necesitar a nadie. Yo también lo creía. Pensaba que la persona más segura era la que respondía rápido, usaba las herramientas con soltura y nunca levantaba la mano para preguntar. Hoy quiero defender una idea distinta: en un trabajo técnico, pedir ayuda a tiempo no demuestra falta de capacidad; puede ser una de las formas más responsables de usarla.</p>
        <p>Lo entendí durante una práctica de medición. Debíamos preparar una pieza a partir de un plano y registrar cada control. En la segunda medida obtuve un valor diferente al de mi compañero. Revisé el instrumento y repetí el procedimiento, pero anoté el número que esperaba encontrar. No inventé conscientemente un resultado; simplemente confié más en mi primera idea que en la señal que tenía delante. Mi compañero vio la diferencia y preguntó si podíamos detenernos. Mi reacción fue decir que no era necesario porque faltaba poco para terminar.</p>
        <p>El profesor no tomó la herramienta para resolverlo por nosotros. Nos pidió explicar la secuencia, comparar las dos mediciones y señalar en qué punto habíamos dejado de verificar. El problema no estaba solo en una cifra. Estaba en que yo había tratado la duda como una demora y no como información. Corregimos la pieza antes de continuar y dejamos anotado el error. Esa anotación sirvió después a otro grupo, que agregó un control antes del mismo paso.</p>
        <p>No cuento esta experiencia para convertir una equivocación común en una hazaña. La cuento porque permite distinguir entre depender siempre de otros y solicitar una segunda mirada cuando la evidencia no coincide. Trabajar con autonomía no significa actuar aislado. Significa saber qué puedes decidir, qué debes comprobar y en qué momento el riesgo exige consultar. Una pregunta hecha a tiempo puede ahorrar material, evitar un accidente o impedir que un error pequeño pase a la siguiente etapa.</p>
        <p>Es posible objetar que, si todos se detienen a preguntar, el trabajo se vuelve lento. Sería cierto si cada duda reemplazara la preparación personal. Por eso pedir ayuda también exige responsabilidad: primero revisar el plano, repetir el procedimiento, registrar lo observado y formular una pregunta precisa. “No entiendo nada” traslada el trabajo completo a otra persona. “Obtuve dos valores distintos después de calibrar; ¿puedes revisar dónde cambia mi procedimiento?” muestra qué se hizo y qué falta resolver.</p>
        <p>Durante estos años no aprendimos solo a ejecutar tareas. Aprendimos a dejar evidencia para quien continúa, a escuchar una advertencia aunque contradiga nuestra seguridad y a explicar por qué tomamos una decisión. Ninguna de esas acciones se luce tanto como una pieza terminada, pero todas sostienen su calidad. A quienes entrarán al taller les diría esto: no intenten parecer seguros ocultando cada duda. Aprendan a convertir la duda en una pregunta comprobable. Y a mis compañeros les propongo que recordemos la misma regla cuando salgamos del colegio: una persona competente no es la que nunca necesita apoyo, sino la que reconoce a tiempo cuándo una decisión no debería tomarla sola.</p>`
    },
    {
      id:'t4', label:'Texto 4 · Dos posiciones', title:'Inteligencia artificial y escritura escolar',
      source:'Intervenciones originales en un consejo ampliado.',
      body:`
        <section class="voice"><h4>Intervención A · Directora académica</h4>
        <p>La discusión sobre inteligencia artificial en tareas de escritura suele quedar atrapada entre dos extremos: fingir que estas herramientas no existen o permitirlas sin condiciones. Ninguna opción ayuda a aprender. Una prohibición total es difícil de sostener fuera de la sala y puede ocultar el uso en vez de volverlo responsable. La ausencia de reglas, en cambio, impide saber qué parte de un texto representa las decisiones del estudiante.</p>
        <p>Propongo un protocolo común. En tareas extensas, cada estudiante debe producir primero un esquema o borrador propio. Si luego consulta una herramienta, registrará para qué la usó: buscar objeciones, revisar claridad, proponer ejemplos u otra función. Finalmente, deberá conservar los cambios realizados y explicar oralmente una decisión importante de su texto. No se trata de vigilar cada palabra, sino de hacer visible el proceso que permite atribuir el aprendizaje.</p>
        <p>Algunos señalan que esta exigencia agregará trabajo a profesores y estudiantes. Es una preocupación válida. Por eso el registro puede ser breve y aplicarse solo a tareas seleccionadas. Sin embargo, renunciar a cualquier evidencia del proceso porque revisarla toma tiempo equivale a evaluar únicamente el producto final, incluso cuando no sabemos cómo se construyó. El propósito del protocolo no es detectar culpables: es asegurar que la herramienta apoye una decisión que el estudiante todavía pueda comprender y defender.</p></section>
        <section class="voice"><h4>Intervención B · Delegado estudiantil</h4>
        <p>Compartimos la necesidad de transparentar el uso, pero el protocolo puede volverse injusto si supone que todos parten del mismo lugar. Algunos estudiantes usan asistentes para ordenar ideas; otros los necesitan para convertir instrucciones extensas en pasos, escuchar un texto o revisar errores que dificultan mostrar lo que saben. Si el registro se interpreta como señal de sospecha, quienes requieren más apoyos quedarán obligados a justificar constantemente su manera de aprender.</p>
        <p>Proponemos distinguir entre sustituir y asistir. Si una herramienta produce la respuesta que luego se entrega sin comprenderla, sustituye el trabajo evaluado. Si ayuda a formular preguntas, organizar información propia o revisar una versión que el estudiante puede explicar, asiste el proceso. La diferencia no se descubre contando cuántas palabras cambió una aplicación. Se observa cuando el estudiante compara versiones, decide qué aceptar y puede responder por el resultado.</p>
        <p>También necesitamos instrucciones compatibles entre asignaturas. No es razonable que una misma acción sea aceptada en una clase y sancionada en otra sin que el propósito de la tarea explique la diferencia. Sugerimos que cada consigna indique qué usos están permitidos, cuáles deben declararse y qué evidencia del proceso se solicitará. La defensa oral puede servir, pero no debería convertirse siempre en un examen adicional. A veces bastará una nota de decisiones o la comparación de dos fragmentos. La transparencia funciona cuando ayuda a entender el aprendizaje, no cuando obliga a demostrar inocencia.</p></section>
        <p><strong>Cierre de la moderadora:</strong> Ambas intervenciones aceptan que una herramienta puede apoyar o reemplazar decisiones y que el producto final, por sí solo, no siempre permite distinguirlo. El desacuerdo está en cómo reunir evidencia sin imponer la misma carga a tareas y estudiantes diferentes. El consejo deberá decidir un protocolo que haga visible el proceso y, al mismo tiempo, permita apoyos justificados.</p>`
    },
    {
      id:'t5', label:'Texto 5 · Discurso ante una comisión', title:'Más sombra, no menos recreo',
      source:'Intervención original ante una comisión de infraestructura escolar.',
      body:`
        <p><strong>Integrantes de la comisión, equipo directivo y representantes de los cursos:</strong></p>
        <p>El informe sobre exposición al calor propone acortar diez minutos el recreo de mediodía durante septiembre y octubre. Comprendemos su intención: evitar que los estudiantes permanezcan bajo el sol en las horas de mayor temperatura. Sin embargo, reducir el tiempo disponible no elimina la exposición; solo obliga a concentrar en menos minutos el almuerzo, el descanso y el traslado. Una medida de cuidado puede terminar debilitando aquello que pretende proteger si no considera cómo se usa realmente el patio.</p>
        <p>Durante dos semanas registramos la ocupación de seis sectores. A las 13:15, los dos espacios con sombra reunían en promedio a 184 estudiantes, aunque sus bancas tenían capacidad para 72. En los cuatro sectores sin sombra había espacio libre, pero una permanencia promedio inferior a cuatro minutos. El dato no demuestra por sí solo que todos eviten el calor: algunos estudiantes se trasladan por otras razones. Sí revela una distribución muy desigual que el recorte horario no modifica.</p>
        <p>Proponemos instalar cubiertas temporales en dos zonas, trasladar cuatro mesas y habilitar el gimnasio abierto cuando la temperatura supere el límite definido por el establecimiento. La prueba duraría ocho semanas. Compararíamos ocupación, incidentes atendidos en enfermería y percepción de comodidad antes y después. Si la sombra adicional no cambia esos indicadores, la comisión podrá reconsiderar la reducción del recreo con más antecedentes que los disponibles hoy.</p>
        <p>Se ha objetado que las cubiertas temporales pueden dañarse con el viento. No pedimos improvisar lonas entre árboles. Existen estructuras certificadas y desmontables cuyo anclaje debe revisar un profesional. También se ha dicho que abrir el gimnasio dificulta la limpieza antes de las clases de la tarde. Ese problema puede resolverse delimitando un sector y ajustando el turno de aseo en los días de mayor temperatura. Son costos y tareas reales; por eso deben calcularse, no usarse como razones automáticas para descartar la alternativa.</p>
        <p>El recreo no es un tiempo vacío. Allí los estudiantes comen, conversan, se mueven y recuperan atención antes del bloque siguiente. Defender su duración no significa negar el riesgo del calor. Significa preguntar si la primera respuesta debe ser quitar tiempo a quienes tienen menos opciones para protegerse. Quien puede comprar almuerzo preparado pierde algunos minutos; quien debe hacer fila, calentar comida y buscar un lugar disponible puede perder casi todo su descanso.</p>
        <p>Solicitamos que la comisión suspenda el recorte mientras se realiza la prueba y publique cada dos semanas los tres indicadores acordados. Al finalizar, podremos decidir con evidencia común. El objetivo no es conservar cada rutina por costumbre. Es diseñar un recreo que siga cumpliendo su función incluso cuando cambian las condiciones del clima.</p>`
    },
    {
      id:'t6', label:'Texto 6 · Mensaje radial comunitario', title:'Cuando la alerta llega al teléfono',
      source:'Transcripción original de un mensaje de prevención comunitaria.',
      body:`
        <p><strong>Vecinas y vecinos que nos escuchan:</strong></p>
        <p>Esta mañana circuló un audio que anuncia un corte total de agua desde las seis de la tarde y pide llenar cualquier recipiente disponible. El mensaje nombra a “personal de emergencia”, pero no identifica a una institución, no señala la zona afectada y tampoco indica una fecha. Antes de reenviarlo, detengámonos. Una advertencia que parece urgente puede provocar un problema nuevo si cientos de personas almacenan más agua de la que necesitan.</p>
        <p>La empresa sanitaria informó una reparación programada entre las 22:00 y las 02:00 en tres calles del sector norte. Según el comunicado publicado a las 10:30, solo esas calles podrían presentar baja presión. La municipalidad confirmó la información y habilitó un número para personas electrodependientes o con movilidad reducida. Esto puede cambiar si ocurre una falla imprevista, pero el audio viral no aporta datos que permitan anticiparla.</p>
        <p>¿Significa eso que nunca debemos compartir una alerta enviada por un conocido? No. Significa que debemos buscar dos elementos antes de hacerlo: una fuente identificable y datos que permitan actuar. Si el mensaje dice quién informa, qué zona afecta, desde cuándo y dónde se actualizará, podemos contrastarlo. Si solo exige “difundir a todos” y aumenta el miedo sin precisar una acción, reenviarlo no es ayudar.</p>
        <p>Sabemos que algunas personas desconfían de los canales oficiales porque en otras ocasiones la información llegó tarde. Esa experiencia merece una respuesta: las instituciones deben actualizar con rapidez y reconocer cuando aún no conocen el alcance de una emergencia. Pero una falla anterior no convierte cualquier audio anónimo en evidencia. Podemos exigir mejores comunicaciones y, al mismo tiempo, revisar lo que compartimos.</p>
        <p>Durante esta tarde, consulten la página municipal o llamen al número anunciado en esta radio. Quienes vivan en las tres calles señaladas pueden almacenar una cantidad razonable para cuatro horas. El resto no necesita modificar su rutina por ahora. Si aparece información nueva, indicaremos su origen y la hora en que fue verificada.</p>
        <p>La calma no consiste en ignorar un riesgo. Consiste en actuar según lo que sabemos, distinguirlo de lo que todavía no sabemos y mantener abierto un canal para corregir. Antes de reenviar, preguntemos: ¿quién lo dice?, ¿a quién afecta?, ¿qué acción concreta pide? Esas preguntas toman menos de un minuto y pueden evitar horas de confusión.</p>`
    },
    {
      id:'t7', label:'Texto 7 · Carta abierta', title:'Una biblioteca que también se escucha',
      source:'Carta abierta original dirigida a la comunidad escolar.',
      body:`
        <p><strong>A la comunidad del liceo:</strong></p>
        <p>Durante años hemos pensado la biblioteca como un lugar silencioso en el que cada persona trabaja por separado. Ese espacio sigue siendo necesario. Una lectura extensa requiere atención y muchos estudiantes encuentran allí la única mesa tranquila de su jornada. Sin embargo, convertir el silencio en la única forma válida de aprender deja fuera otras prácticas que también dependen de libros, documentos y conversación.</p>
        <p>En abril realizamos seis actividades de lectura compartida en el pasillo exterior: un club de novela gráfica, dos tutorías entre pares, una búsqueda de fuentes para Historia y dos ensayos de lectura dramatizada. Participaron 96 estudiantes. La cifra no demuestra que todos aprendieran más ni que debamos transformar toda la biblioteca. Muestra que existe una demanda por trabajar con textos de maneras que el espacio actual no admite.</p>
        <p>Por eso proponemos conservar la sala principal como zona silenciosa y convertir el depósito contiguo, hoy usado solo para mobiliario en desuso, en una sala de conversación con doce puestos. La puerta entre ambos espacios debería incorporar aislamiento básico y la reserva se haría por bloques breves. Si una actividad requiere hablar, tendrá un lugar definido; si una persona necesita silencio, no dependerá de pedir a otros que bajen la voz una y otra vez.</p>
        <p>Algunos usuarios temen que abrir una sala conversada sea el primer paso para perder el carácter de la biblioteca. La preocupación es comprensible, porque una regla difícil de vigilar puede extenderse. Precisamente por eso planteamos límites observables: capacidad máxima, horario, reserva y evaluación después de un semestre. No proponemos reemplazar el silencio por ruido, sino evitar que una sola condición de uso represente todas las formas de lectura.</p>
        <p>La transformación exige retirar muebles, mejorar iluminación y asignar a alguien que gestione las reservas. Antes de aprobarla, necesitamos un presupuesto y una prueba acústica. También debemos consultar a quienes usan diariamente la sala principal, no solo a quienes participaron en las actividades del pasillo. Una propuesta que busca incluir no puede decidirse escuchando únicamente a quienes ya están convencidos.</p>
        <p>Invitamos al consejo escolar a autorizar el estudio técnico y una consulta abierta. Si el depósito no puede aislarse o si la comunidad identifica un uso mejor, deberemos revisar la idea. Pero si las condiciones son viables, tendremos la oportunidad de proteger el silencio sin confundirlo con inmovilidad. Una biblioteca puede enseñar a concentrarse y también a construir una interpretación con otros. La pregunta es cómo diseñar el espacio para que ninguna de esas experiencias borre a la otra.</p>`
    },
    {
      id:'t8', label:'Texto 8 · Debate público', title:'¿Debe el municipio transmitir todas sus reuniones?',
      source:'Intervenciones originales en una sesión municipal.',
      body:`
        <section class="voice"><h4>Intervención A · Representante de una organización ciudadana</h4>
        <p>Transmitir las reuniones municipales permitiría que quienes trabajan, cuidan a otras personas o viven lejos conozcan decisiones que también los afectan. Hoy las actas aparecen días después y resumen acuerdos, pero no siempre muestran qué argumentos se discutieron. Una cámara no garantiza transparencia completa; sí amplía la posibilidad de observar y comparar.</p>
        <p>Proponemos transmitir en directo, publicar la grabación con capítulos y mantener las actas escritas. Los capítulos permitirían llegar al tema buscado sin revisar horas de video. Las actas seguirían siendo necesarias para localizar acuerdos y votaciones. No se trata de reemplazar un formato por otro, sino de combinar sus funciones.</p>
        <p>Reconocemos que algunas reuniones contienen datos personales. En esos casos debe cerrarse temporalmente la transmisión, explicar el motivo y registrar qué tramo quedó reservado. La protección de una persona no puede transformarse en una fórmula vaga para ocultar cualquier conversación difícil.</p></section>
        <section class="voice"><h4>Intervención B · Secretaria municipal</h4>
        <p>Compartimos el objetivo, pero transmitir sin recursos de archivo puede producir una apariencia de acceso. Un video de cuatro horas, sin subtítulos ni índice, está técnicamente disponible y prácticamente escondido. Además, si la conexión falla y no existe una copia local, parte de la reunión desaparece.</p>
        <p>Antes del directo necesitamos asegurar grabación local, subtítulos revisables, un índice por temas y un protocolo para datos personales. Sugiero comenzar con tres reuniones ordinarias, medir cuántas personas consultan el directo, la grabación y las actas, y preguntar si encuentran lo que buscan. Después podremos calcular costos y ajustar.</p>
        <p>Mi diferencia con la propuesta anterior no está en si debemos abrir las reuniones, sino en qué significa abrirlas de verdad. Publicar un archivo no basta si nadie puede navegarlo, comprenderlo o recuperar una parte cuando falla la transmisión. La transparencia requiere continuidad, contexto y formas de búsqueda.</p></section>
        <p><strong>Síntesis de la presidencia:</strong> Existe acuerdo en conservar actas y ampliar el acceso audiovisual. La decisión pendiente es si comenzar inmediatamente con todas las sesiones o realizar primero una experiencia acotada que asegure condiciones de consulta y resguardo.</p>`
    }
  ],
  questions: [
    {id:'q1',unit:'t1',skill:'INTERPRETAR',prompt:'¿Cuál es la idea central que el emisor busca defender?',options:{A:'Los teléfonos deben permanecer fuera del colegio durante toda la jornada.',B:'Conviene probar zonas con reglas distintas y evaluar sus resultados antes de fijar una norma.',C:'Los estudiantes usan el teléfono principalmente para hablar con sus familias.',D:'La convivencia mejorará solo si los profesores vigilan cada recreo.'}},
    {id:'q2',unit:'t1',skill:'REFLEXIONAR',prompt:'¿Qué limitación reconoce el emisor respecto de los datos de la encuesta?',options:{A:'La encuesta fue contestada únicamente por profesores del establecimiento.',B:'Los datos impiden conocer cualquier función que tenga el teléfono.',C:'La observación se realizó durante un periodo demasiado extenso.',D:'Los datos no demuestran por sí solos que el teléfono sea inocuo o cause aislamiento.'}},
    {id:'q3',unit:'t1',skill:'INTERPRETAR',prompt:'¿Qué función cumple el cuarto párrafo en la argumentación?',options:{A:'Reconoce un límite y añade formas de comprobar y corregir la propuesta.',B:'Abandona la propuesta inicial y acepta la prohibición completa de teléfonos.',C:'Enumera sanciones para quienes no participen en las actividades del patio.',D:'Demuestra que las zonas resolverán de manera definitiva todos los conflictos.'}},
    {id:'q4',unit:'t1',skill:'INTERPRETAR',prompt:'¿Por qué el emisor menciona que fuera del colegio no habrá una caja para guardar teléfonos?',options:{A:'Para afirmar que las reglas escolares nunca tienen utilidad fuera del establecimiento.',B:'Para demostrar que los estudiantes no pueden obedecer una prohibición.',C:'Para destacar que autorregular el uso es una habilidad transferible a otros contextos.',D:'Para señalar que las familias deberían confiscar los teléfonos en sus hogares.'}},
    {id:'q5',unit:'t1',skill:'LOCALIZAR',prompt:'¿Qué medida permitirá revisar la propuesta antes de terminar las seis semanas?',options:{A:'Una votación obligatoria al terminar cada recreo.',B:'Una consulta breve al finalizar la cuarta semana.',C:'Un informe elaborado solo por los mediadores estudiantiles.',D:'Una prohibición temporal aplicada durante los primeros días.'}},
    {id:'q6',unit:'t1',skill:'REFLEXIONAR',prompt:'¿Qué evidencia adicional permitiría evaluar mejor si las zonas mejoran la convivencia?',options:{A:'La cantidad total de teléfonos vendidos durante el año en la comuna.',B:'La opinión de una persona que nunca ha visitado el patio del colegio.',C:'El color preferido por los estudiantes para pintar cada zona.',D:'Una comparación de interacciones e incidentes antes y durante la prueba.'}},

    {id:'q7',unit:'t2',skill:'INTERPRETAR',prompt:'¿Qué cambio en el orden de las decisiones solicita el comité?',options:{A:'Estudiar el movimiento del agua antes de definir la construcción.',B:'Construir primero el paseo y estudiar sus efectos después.',C:'Consultar a los comerciantes y reemplazar los estudios técnicos.',D:'Eliminar definitivamente cualquier obra cercana al estero.'}},
    {id:'q8',unit:'t2',skill:'REFLEXIONAR',prompt:'¿Por qué las actas revisadas no sostienen completamente la explicación municipal?',options:{A:'Porque ninguna de las dieciocho actas menciona residuos ni problemas de desagüe en ese sector.',B:'Porque las dieciocho actas identifican una misma causa, pero el municipio decidió no considerarla.',C:'Porque solo nueve casos vinculan residuos y desagües; los demás registran otros factores o no precisan causa.',D:'Porque las actas estudiadas describen inundaciones ocurridas exclusivamente en comunas distintas.'}},
    {id:'q9',unit:'t2',skill:'INTERPRETAR',prompt:'¿Qué propósito cumple la alternativa de construir primero los tramos menos críticos?',options:{A:'Reemplazar el estudio hidráulico por la experiencia de los comerciantes.',B:'Responder al temor por la demora sin abandonar la precaución solicitada.',C:'Asegurar que la inauguración ocurra antes de la temporada de lluvias.',D:'Demostrar que las zonas críticas no forman parte del proyecto.'}},
    {id:'q10',unit:'t2',skill:'INTERPRETAR',prompt:'¿Cómo valora el emisor los testimonios de los vecinos?',options:{A:'Como conclusiones que deben imponerse sobre cualquier medición.',B:'Como recuerdos sin utilidad para una investigación técnica.',C:'Como pruebas suficientes para cancelar de inmediato la construcción.',D:'Como antecedentes que pueden orientar preguntas que luego deben comprobarse.'}},
    {id:'q11',unit:'t2',skill:'LOCALIZAR',prompt:'¿Cuántos de los dieciocho episodios mencionan residuos junto con desagües estrechos?',options:{A:'Nueve episodios.',B:'Seis episodios.',C:'Tres episodios.',D:'Dieciocho episodios.'}},
    {id:'q12',unit:'t2',skill:'REFLEXIONAR',prompt:'¿Cuál de los siguientes antecedentes fortalecería más la propuesta del comité?',options:{A:'Una colección de fotografías de paseos construidos en otras ciudades.',B:'Una encuesta sobre el tipo de banca preferido por los visitantes.',C:'Una modelación que compare la absorción y el caudal antes y después del proyecto.',D:'Una lista de comercios que esperan aumentar sus ventas en verano.'}},

    {id:'q13',unit:'t3',skill:'INTERPRETAR',prompt:'¿Qué tesis sostiene principalmente la estudiante?',options:{A:'El trabajo técnico debe realizarse siempre bajo supervisión directa.',B:'La rapidez es el mejor indicador de competencia profesional.',C:'Registrar errores impide que un grupo termine a tiempo una tarea.',D:'Pedir ayuda oportunamente puede ser una conducta competente y responsable.'}},
    {id:'q14',unit:'t3',skill:'INTERPRETAR',prompt:'¿Qué demuestra la experiencia de la medición?',options:{A:'Que el instrumento estaba dañado y debía reemplazarse.',B:'Que una expectativa previa puede hacer ignorar una señal contradictoria.',C:'Que el compañero buscaba retrasar el trabajo del grupo.',D:'Que anotar un resultado basta para impedir cualquier error posterior.'}},
    {id:'q15',unit:'t3',skill:'INTERPRETAR',prompt:'¿Qué diferencia establece el quinto párrafo entre dos formas de pedir ayuda?',options:{A:'Una ocurre en el taller y la otra solo puede ocurrir fuera del colegio.',B:'Una se dirige a compañeros y la otra se dirige exclusivamente al profesor.',C:'Una traslada todo el problema; la otra muestra revisión previa y formula una duda precisa.',D:'Una se expresa oralmente y la otra debe quedar registrada por escrito.'}},
    {id:'q16',unit:'t3',skill:'LOCALIZAR',prompt:'¿Qué hizo el profesor antes de que el grupo corrigiera la pieza?',options:{A:'Pidió explicar la secuencia, comparar mediciones e identificar dónde dejaron de verificar.',B:'Tomó la herramienta, repitió cada paso y completó él mismo la medición que faltaba.',C:'Ordenó desechar la pieza y comenzar desde el inicio con materiales y medidas nuevas.',D:'Calificó el trabajo inmediatamente, sin permitir que el grupo revisara el origen del error.'}},
    {id:'q17',unit:'t3',skill:'REFLEXIONAR',prompt:'¿Cuál situación aplica mejor el criterio de competencia defendido en el discurso?',options:{A:'Ocultar una diferencia para no parecer inseguro ante el equipo.',B:'Preguntar antes de revisar cualquier instrucción o procedimiento.',C:'Continuar una tarea porque detenerse podría afectar el ritmo del grupo.',D:'Revisar, registrar la discrepancia y solicitar otra mirada antes de una etapa riesgosa.'}},
    {id:'q18',unit:'t3',skill:'INTERPRETAR',prompt:'¿Por qué el discurso se dirige también a quienes entrarán al taller el próximo año?',options:{A:'Porque ellos deben evaluar las calificaciones de quienes egresan.',B:'Porque la experiencia se presenta como una orientación para decisiones futuras.',C:'Porque fueron responsables del error ocurrido durante la medición.',D:'Porque deberán repetir exactamente la misma práctica con la misma pieza.'}},

    {id:'q19',unit:'t4',skill:'INTERPRETAR',prompt:'¿Qué relación existe entre las dos intervenciones?',options:{A:'Defienden protocolos totalmente opuestos y no comparten ningún criterio.',B:'La segunda rechaza que las herramientas puedan apoyar el aprendizaje.',C:'Comparten la transparencia del proceso, pero difieren sobre cómo evitar cargas injustas.',D:'La primera se refiere a docentes y la segunda a una situación sin relación escolar.'}},
    {id:'q20',unit:'t4',skill:'LOCALIZAR',prompt:'¿Qué propone la directora antes de consultar una herramienta?',options:{A:'Producir un esquema o borrador propio.',B:'Realizar siempre una defensa oral completa.',C:'Solicitar autorización individual a la dirección.',D:'Entregar una lista de todas las palabras modificadas.'}},
    {id:'q21',unit:'t4',skill:'INTERPRETAR',prompt:'¿Qué criterio usa el delegado para distinguir asistir de sustituir?',options:{A:'La cantidad de minutos durante los que se utilizó la herramienta.',B:'El porcentaje exacto de palabras que permaneció sin cambios.',C:'La asignatura en que se realizó la actividad escrita.',D:'La capacidad de comparar, decidir y responder por el resultado.'}},
    {id:'q22',unit:'t4',skill:'REFLEXIONAR',prompt:'¿Qué problema tendría una regla idéntica para todas las asignaturas según el delegado?',options:{A:'Impediría que los profesores conozcan cualquier herramienta disponible.',B:'Ignoraría que el propósito de cada tarea puede justificar usos y evidencias diferentes.',C:'Haría imposible conservar borradores escritos antes de usar una aplicación.',D:'Obligaría a todos los estudiantes a entregar textos de la misma extensión.'}},
    {id:'q23',unit:'t4',skill:'INTERPRETAR',prompt:'¿Qué función cumple el cierre de la moderadora?',options:{A:'Declara ganadora a la directora y elimina la propuesta estudiantil.',B:'Introduce un tema nuevo que no fue mencionado por los participantes.',C:'Sintetiza el acuerdo común y precisa el punto que todavía debe resolverse.',D:'Demuestra que ningún protocolo puede aplicarse en el contexto escolar.'}},
    {id:'q24',unit:'t4',skill:'REFLEXIONAR',prompt:'¿Cuál regla integraría mejor las preocupaciones de ambas intervenciones?',options:{A:'Cada tarea explicita usos permitidos y pide evidencia proporcional que el estudiante pueda explicar.',B:'Toda herramienta queda prohibida, excepto cuando el producto final tiene buena calidad.',C:'Cada estudiante decide sus reglas y no necesita informar cómo construyó el texto.',D:'Todas las tareas exigen el mismo registro y una defensa oral extensa, sin excepciones.'}},

    {id:'q25',unit:'t5',skill:'INTERPRETAR',prompt:'¿Qué propone principalmente la intervención?',options:{A:'Eliminar el recreo de mediodía durante los meses de mayor temperatura.',B:'Probar medidas de sombra y evaluar indicadores antes de reducir el recreo.',C:'Trasladar todas las actividades escolares al gimnasio durante ocho semanas.',D:'Mantener el patio sin cambios porque el calor no representa un riesgo.'}},
    {id:'q26',unit:'t5',skill:'REFLEXIONAR',prompt:'¿Qué precaución expresa el emisor al interpretar el registro de ocupación?',options:{A:'Reconoce que las bancas fueron contadas en una estación distinta.',B:'Admite que ningún estudiante respondió preguntas sobre el patio.',C:'Señala que los espacios de sombra no fueron observados al mediodía.',D:'Aclara que la distribución observada puede deberse también a otras razones.'}},
    {id:'q27',unit:'t5',skill:'INTERPRETAR',prompt:'¿Qué función cumple el cuarto párrafo?',options:{A:'Responde objeciones mostrando condiciones concretas para aplicar la propuesta.',B:'Presenta resultados definitivos obtenidos después de instalar las cubiertas.',C:'Descalifica a quienes consideran los costos y las tareas de mantención.',D:'Reemplaza la propuesta por el cierre permanente de los espacios abiertos.'}},
    {id:'q28',unit:'t5',skill:'INTERPRETAR',prompt:'¿Por qué se compara a quien compra almuerzo con quien debe hacer fila y calentarlo?',options:{A:'Para demostrar que todos usan el recreo de la misma manera, aunque realicen actividades distintas.',B:'Para sostener que el servicio de alimentación debe suspenderse durante los meses de mayor temperatura.',C:'Para mostrar que el recorte afecta de modo desigual según las condiciones de cada estudiante.',D:'Para explicar que la mayoría prefiere comer rápidamente y permanecer en espacios sin sombra.'}},
    {id:'q29',unit:'t5',skill:'LOCALIZAR',prompt:'¿Cuál era la capacidad conjunta de bancas en los dos espacios con sombra?',options:{A:'Cuarenta puestos.',B:'Setenta y dos puestos.',C:'Ciento ochenta y cuatro puestos.',D:'Doscientos cincuenta y seis puestos.'}},
    {id:'q30',unit:'t5',skill:'REFLEXIONAR',prompt:'¿Qué resultado apoyaría con mayor fuerza la propuesta del emisor?',options:{A:'Tras instalar sombra aumenta el uso de las zonas y disminuyen atenciones asociadas al calor.',B:'Los estudiantes eligen colores distintos para las nuevas estructuras.',C:'La duración del recreo se mantiene igual durante una semana de bajas temperaturas.',D:'Las mesas antiguas son trasladadas sin registrar cómo se usan después.'}},
    {id:'q31',unit:'t5',skill:'INTERPRETAR',prompt:'¿Qué relación establece el título “Más sombra, no menos recreo”?',options:{A:'Opone cualquier medida de infraestructura a la protección de la salud.',B:'Afirma que ampliar el recreo es la única solución posible al calor.',C:'Sostiene que la temperatura puede ignorarse si hay tiempo suficiente.',D:'Contrasta la solución propuesta por el emisor con el recorte planteado en el informe.'}},

    {id:'q32',unit:'t6',skill:'INTERPRETAR',prompt:'¿Cuál es el propósito principal del mensaje radial?',options:{A:'Convencer a toda la comuna de almacenar agua para una semana.',B:'Criticar a quienes alguna vez compartieron información no confirmada.',C:'Orientar cómo verificar una alerta y actuar según información identificable.',D:'Demostrar que los comunicados institucionales nunca contienen errores.'}},
    {id:'q33',unit:'t6',skill:'LOCALIZAR',prompt:'¿Qué información fue confirmada por la empresa sanitaria?',options:{A:'Una reparación de cuatro horas que podría causar baja presión en tres calles.',B:'Un corte total desde las seis de la tarde en toda la comuna.',C:'Una falla imprevista que afectaría a las personas electrodependientes.',D:'La necesidad de llenar cualquier recipiente disponible durante la mañana.'}},
    {id:'q34',unit:'t6',skill:'INTERPRETAR',prompt:'¿Qué función cumple la pregunta “¿Significa eso que nunca debemos compartir una alerta enviada por un conocido?”?',options:{A:'Solicita a los auditores que llamen y respondan en directo.',B:'Introduce un posible extremo para luego precisar el criterio del mensaje.',C:'Reconoce que el audio anónimo contiene datos suficientes para actuar.',D:'Cambia el tema desde el abastecimiento hacia la vida privada de los vecinos.'}},
    {id:'q35',unit:'t6',skill:'INTERPRETAR',prompt:'¿Cómo responde el emisor a la desconfianza hacia los canales oficiales?',options:{A:'Afirma que las experiencias anteriores deben olvidarse por completo.',B:'Acepta que cualquier mensaje informal es válido cuando hay temor.',C:'Sostiene que la rapidez importa aunque no se identifique la fuente.',D:'Reconoce fallas anteriores, pero niega que vuelvan verdadero un audio anónimo.'}},
    {id:'q36',unit:'t6',skill:'REFLEXIONAR',prompt:'¿Cuál mensaje sería más confiable según los criterios del discurso?',options:{A:'“Urgente: mañana habrá un corte total en varios sectores; comparte ahora antes de que eliminen este aviso”.',B:'“Guarden toda el agua posible desde esta tarde; todavía no puedo decir quién entregó la información”.',C:'“Sanitaria local: baja presión de 22:00 a 02:00 en calles Norte, Lago y Uno; actualización a las 20:00”.',D:'“Un vecino del sector asegura que el corte será total, aunque el municipio publicó una versión diferente”.'}},
    {id:'q37',unit:'t6',skill:'INTERPRETAR',prompt:'¿Qué tono predomina a lo largo del mensaje?',options:{A:'Alarmista, porque exagera las consecuencias de cada reenvío.',B:'Preventivo y sereno, porque reconoce riesgos y propone pasos verificables.',C:'Burlesco, porque ridiculiza a las personas que recibieron el audio.',D:'Indiferente, porque evita recomendar cualquier acción concreta.'}},
    {id:'q38',unit:'t6',skill:'REFLEXIONAR',prompt:'¿Qué rasgo del audio viral debilita más su utilidad para tomar decisiones?',options:{A:'No identifica fuente, zona ni fecha que permitan contrastarlo y actuar.',B:'Fue recibido durante la mañana y no durante la tarde.',C:'Se difundió mediante voz en lugar de utilizar un texto escrito.',D:'Menciona un posible corte en vez de referirse a baja presión.'}},

    {id:'q39',unit:'t7',skill:'INTERPRETAR',prompt:'¿Qué idea central defiende la carta?',options:{A:'El silencio debe eliminarse porque impide cualquier aprendizaje compartido.',B:'Toda actividad con textos debería realizarse en el pasillo exterior.',C:'El depósito debe convertirse inmediatamente, sin estudio ni consulta.',D:'La biblioteca puede proteger el silencio y habilitar otra zona para usos conversados.'}},
    {id:'q40',unit:'t7',skill:'REFLEXIONAR',prompt:'¿Qué límite reconoce la carta respecto de las 96 participaciones?',options:{A:'Corresponden solo a estudiantes que nunca habían usado la biblioteca.',B:'Fueron registradas fuera del periodo anunciado por el establecimiento.',C:'No prueban mayor aprendizaje ni justifican transformar todo el espacio.',D:'Impiden conocer si existe demanda por formas compartidas de lectura.'}},
    {id:'q41',unit:'t7',skill:'LOCALIZAR',prompt:'¿Cómo se organizarían los dos espacios según la propuesta?',options:{A:'Sala principal silenciosa y depósito adaptado como sala de conversación.',B:'Sala principal para conversar y depósito reservado únicamente a docentes.',C:'Ambos espacios silenciosos, pero con horarios de entrada diferentes.',D:'Pasillo exterior con doce puestos y biblioteca cerrada durante los talleres.'}},
    {id:'q42',unit:'t7',skill:'INTERPRETAR',prompt:'¿Cómo responde el emisor al temor de perder el carácter de la biblioteca?',options:{A:'Niega que el temor tenga alguna relación con la propuesta presentada.',B:'Plantea límites observables y una evaluación para contener ese riesgo.',C:'Promete que nunca habrá ruido aunque se habilite una sala conversada.',D:'Propone que solo participen quienes ya apoyan la transformación.'}},
    {id:'q43',unit:'t7',skill:'INTERPRETAR',prompt:'¿Qué principio expresa la frase “Una propuesta que busca incluir no puede decidirse escuchando únicamente a quienes ya están convencidos”?',options:{A:'Las decisiones técnicas deben quedar exclusivamente en manos de estudiantes.',B:'Toda consulta debe aprobar la idea que motivó su realización.',C:'La opinión mayoritaria reemplaza el presupuesto y la prueba acústica.',D:'La participación debe incorporar también a quienes podrían verse afectados o discrepan.'}},
    {id:'q44',unit:'t7',skill:'REFLEXIONAR',prompt:'¿Qué evidencia permitiría decidir mejor si ambos usos pueden convivir?',options:{A:'La cantidad de libros comprados por la biblioteca durante el año anterior.',B:'Una lista de actividades realizadas fuera del horario escolar.',C:'Una prueba acústica del depósito y una consulta a usuarios de ambos tipos de espacio.',D:'La opinión de un único grupo que participó en la lectura dramatizada.'}},

    {id:'q45',unit:'t8',skill:'INTERPRETAR',prompt:'¿Cuál es la principal diferencia entre las dos intervenciones?',options:{A:'Una quiere eliminar las actas y la otra propone conservar exclusivamente los documentos escritos.',B:'Una propone acceso audiovisual amplio; la otra pide un piloto con condiciones de consulta.',C:'Una busca proteger todos los datos personales y la otra propone publicarlos sin límite alguno.',D:'Una defiende la transparencia de las sesiones y la otra rechaza abrir las reuniones al público.'}},
    {id:'q46',unit:'t8',skill:'INTERPRETAR',prompt:'¿Por qué la secretaria afirma que un video disponible puede estar “prácticamente escondido”?',options:{A:'Porque sin subtítulos ni índice resulta difícil localizar y comprender su contenido.',B:'Porque toda grabación municipal debe permanecer en una plataforma privada.',C:'Porque las personas prefieren siempre leer documentos extensos.',D:'Porque el directo impide conservar una copia local de la reunión.'}},
    {id:'q47',unit:'t8',skill:'LOCALIZAR',prompt:'¿Qué propone la representante cuando se traten datos personales?',options:{A:'Cancelar la reunión y eliminar cualquier registro de sus acuerdos.',B:'Mantener la transmisión y ocultar solo los nombres al finalizar.',C:'Sustituir la sesión por una votación sin intervención pública.',D:'Cerrar temporalmente la transmisión y dejar constancia del tramo reservado.'}},
    {id:'q48',unit:'t8',skill:'INTERPRETAR',prompt:'¿Para qué propone la secretaria comenzar con tres reuniones?',options:{A:'Para demostrar que las actas escritas ya no serán necesarias.',B:'Para limitar permanentemente el acceso a las sesiones ordinarias.',C:'Para medir usos, detectar dificultades y ajustar antes de ampliar el sistema.',D:'Para seleccionar solo reuniones en las que no exista desacuerdo.'}},
    {id:'q49',unit:'t8',skill:'INTERPRETAR',prompt:'¿Qué supuesto comparten ambas posiciones?',options:{A:'Transmitir en directo resuelve por sí solo el problema de acceso.',B:'La transparencia requiere más acceso, sin eliminar actas ni resguardos.',C:'Los costos técnicos no deberían influir en ninguna decisión pública.',D:'Las reuniones reservadas deben permanecer completamente secretas.'}},
    {id:'q50',unit:'t8',skill:'REFLEXIONAR',prompt:'¿Qué decisión integraría mejor las dos posturas?',options:{A:'Realizar un piloto con grabación, índice, subtítulos y actas, y ampliar tras evaluar el acceso.',B:'Transmitir todas las reuniones de inmediato sin grabación local ni protocolos.',C:'Mantener únicamente las actas y descartar cualquier recurso audiovisual.',D:'Publicar videos completos, pero eliminar los documentos que permiten localizar acuerdos.'}}
  ],
  openQuestions: [
    {id:'o1',unit:'t2',prompt:'Evalúa si el comité presenta una solicitud razonable. Formula un juicio y utiliza dos evidencias distintas del discurso para explicarlo.',min:180},
    {id:'o2',unit:'t4',prompt:'Compara ambas intervenciones y propone una regla para el colegio. Debes usar una idea de la directora y una del delegado para justificarla.',min:220}
  ],
  metaQuestions: [
    {id:'m1',prompt:'¿Qué diferencia comprendiste hoy entre tema, propósito y tesis?',min:25},
    {id:'m2',prompt:'¿Qué evidencia del texto te ayudó a descartar una alternativa?',min:25},
    {id:'m3',prompt:'¿Qué revisarás primero la próxima vez que leas un discurso?',min:25}
  ]
};
