window.SIMCE_U3S9_DATA = {
  session: 'sesion-u3-8',
  reviewOf: {
    titulo: 'Unidad 3 · Clase 9 — Corrección del ensayo',
    fuente: 'Ensayo parcial de la Clase 8 (7 textos, 36 preguntas).'
  },
  items: [
    { id:'q1', correcta:'B', explicacion:'El texto lo dice de forma literal: "la guardó en el bolsillo sin preguntar qué película se había exhibido". No hay fotografía ni comparación con otras entradas; ese dato se inventa.' },
    { id:'q2', correcta:'D', explicacion:'Todo el relato gira en torno al cierre del cine y su transformación en farmacia: la última función es una despedida. La falla técnica (A) es un episodio, no el conflicto completo, y el abuelo no muestra dificultad para aceptar el cambio (C).' },
    { id:'q3', correcta:'A', explicacion:'Cuando se corta el sonido, el público inventa diálogos, imita puertas y marca el ritmo con palmas: convierte la falla en una experiencia compartida y creativa, no en un rechazo ni en una queja hacia don Rafael.' },
    { id:'q4', correcta:'C', explicacion:'El letrero "Estrella" incompleto abre y cierra el relato como símbolo de un lugar deteriorado que igual conserva valor para los vecinos, que se fotografían bajo él y se quedan conversando debajo.' },
    { id:'q5', correcta:'B', explicacion:'Emilia señala el letrero y a la gente que sigue reunida bajo él: la experiencia del cine estuvo también en los vínculos entre las personas, no en la pantalla ni en la calle escuchando la función.' },
    { id:'q6', correcta:'D', explicacion:'"Una despedida que reúne voces" resume el cierre del cine, la última función y el momento en que el público improvisa diálogos juntos; los otros títulos se quedan en un detalle (la entrada, la farmacia, la falla técnica).' },
    { id:'q7', correcta:'A', explicacion:'El artículo completo argumenta que la calidad de la iluminación depende de la orientación, continuidad y distribución de la luz, no solo de su potencia; esa es la idea que organiza todos los párrafos.' },
    { id:'q8', correcta:'C', explicacion:'El texto lo entrega directo: "los puntos oscuros disminuyeron aunque el consumo eléctrico total fue menor". No se afirma una baja sostenida de delitos (A): el propio texto aclara que eso no se puede concluir.' },
    { id:'q9', correcta:'D', explicacion:'La aclaración funciona como un límite explícito a la evidencia: el proyecto piloto no alcanza para probar una reducción de delitos, y el texto lo dice para no exagerar sus propios resultados.' },
    { id:'q10', correcta:'B', explicacion:'Los vecinos identifican árboles, cruces y un paradero con poca luz: información sobre usos y horarios reales del espacio que un plano técnico no registra por sí solo.' },
    { id:'q11', correcta:'A', explicacion:'La conclusión del proyecto es puntual (menos puntos oscuros, menor consumo, mismos pasajes); lo que más la refuerza es medir antes y después en esos mismos lugares, no una encuesta nacional de preferencias.' },
    { id:'q12', correcta:'C', explicacion:'El poema pide no buscar "la casa en la fotografía" sino la piedra, el olor, la voz: reconocer el lugar por huellas cotidianas y aceptar que cambió, no reconstruirlo intacto ni evitarlo.' },
    { id:'q13', correcta:'B', explicacion:'"La puerta aprendió otro color" es una imagen del paso del tiempo: algo que se recordaba de una manera ahora es distinto. No hay ocultamiento deliberado ni reemplazo literal por una ventana.' },
    { id:'q14', correcta:'D', explicacion:'El río que mueve el puente mientras el puente "finge sostenerlo" cuestiona la apariencia de estabilidad frente a un cambio que sigue ocurriendo; no es una descripción literal de una construcción.' },
    { id:'q15', correcta:'A', explicacion:'La primera estrofa busca lo intacto ("no busques la casa en la fotografía") y la última acepta ser reconocido distinto ("algo también te reconoce distinto"): de la búsqueda a la aceptación mutua del cambio.' },
    { id:'q16', correcta:'C', explicacion:'Todo el poema trabaja la tensión entre recordar y aceptar el cambio: el regreso como encuentro entre la memoria y las transformaciones del tiempo, no como la imposibilidad de recordar.' },
    { id:'q17', correcta:'D', explicacion:'El gráfico marca junio con la barra más alta y el valor 630, el máximo del periodo abril–julio.' },
    { id:'q18', correcta:'A', explicacion:'630 (junio) menos 420 (abril) es 210 visitas de diferencia; hay que restar los valores del gráfico, no los de otra columna de la tabla.' },
    { id:'q19', correcta:'B', explicacion:'Calculando con la tabla: 126/420, 153/510, 189/630 y 180/600 dan 30 % cada mes. Los préstamos a domicilio equivalen de forma estable al 30 % de las visitas, no a la mitad de los talleres.' },
    { id:'q20', correcta:'C', explicacion:'La nota metodológica indica que en julio hubo una semana de vacaciones escolares, dato que explica directamente la baja de visitas respecto a junio.' },
    { id:'q21', correcta:'D', explicacion:'La nota metodológica lo advierte: "los registros cuentan ingresos, no personas únicas: un mismo estudiante puede aparecer varias veces". Por eso 630 es un conteo de ingresos, no de estudiantes distintos.' },
    { id:'q22', correcta:'B', explicacion:'La columna propone trazabilidad: declarar el uso, comparar con fuentes y explicar correcciones. No defiende usar IA en todo (A) ni prohibirla (C); busca un término medio con criterios.' },
    { id:'q23', correcta:'C', explicacion:'La autora reconoce primero la objeción ("es cierto, revisar tarda más") y recién después explica por qué esa revisión también enseña: es un movimiento concesivo, no un abandono de su postura.' },
    { id:'q24', correcta:'A', explicacion:'El texto lo enumera de forma explícita: "declarar cuándo se usó una herramienta, comparar su propuesta con fuentes y explicar qué se corrigió".' },
    { id:'q25', correcta:'D', explicacion:'La autora cuestiona dos extremos (prohibir o celebrar sin criterio) y propone una postura intermedia con condiciones de uso: es un tono crítico y propositivo, no alarmista ni nostálgico.' },
    { id:'q26', correcta:'B', explicacion:'Comparar la respuesta generada con fuentes, corregir errores y declarar el apoyo usado es exactamente la trazabilidad que defiende la columna; entregar sin cambios (A) es lo que la autora critica.' },
    { id:'q27', correcta:'A', explicacion:'Elena lo dice directamente: antes de trasladar aves hay que "controlar residuos, recuperar flujos de agua y disminuir perturbaciones"; los animales deberían llegar solos si el hábitat funciona.' },
    { id:'q28', correcta:'D', explicacion:'"Una decoración" se opone a que la presencia de fauna sea consecuencia de un hábitat que realmente funciona, no un adorno para la foto o las visitas.' },
    { id:'q29', correcta:'C', explicacion:'Cada pregunta del periodista (juncos, aves, comerciantes) obliga a Elena a matizar su postura con un caso concreto, precisando su argumento en vez de repetirlo en abstracto.' },
    { id:'q30', correcta:'B', explicacion:'Elena responde "cuidar no equivale a cerrar" y propone horarios y zonas de uso: coincide con los comerciantes en que el uso público importa, pero condicionándolo a no dañar los procesos ecológicos.' },
    { id:'q31', correcta:'A', explicacion:'Elena cierra afirmando que el éxito exige medir calidad del agua, vegetación, especies y comportamiento de las visitas durante varios años; un indicador coherente combina esas variables en el tiempo.' },
    { id:'q32', correcta:'C', explicacion:'El aviso informa las condiciones iniciales y anuncia una revisión final; el correo aporta observaciones para mejorar esa evaluación. Ambos apuntan a orientar el funcionamiento y la evaluación del piloto.' },
    { id:'q33', correcta:'B', explicacion:'El Documento A presenta condiciones de partida (horario, requisitos, duración); el Documento B responde con ajustes y preguntas concretas (horario nocturno, fecha de mantención, recargas vs. botellas).' },
    { id:'q34', correcta:'D', explicacion:'La junta vecinal lo pide explícitamente: "publicar la fecha de cada mantención en la misma estación", porque saber que existe un filtro no dice cuándo fue revisado.' },
    { id:'q35', correcta:'A', explicacion:'El correo lo explica: "una botella puede rellenarse varias veces", así que el número de recargas y la cantidad de botellas evitadas no son la misma cifra.' },
    { id:'q36', correcta:'C', explicacion:'Para saber si el horario (08:00–20:00) responde al uso real hace falta un registro de actividades y recargas por franja horaria, no el precio de otras estaciones ni el diseño visual.' }
  ]
};
