'use strict';
// Herramienta de planificación: no modifica motor, API, cuentas ni sitio publicado.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const dir=__dirname;
const rarity={common:{name:'Común',color:'#9BA5B0',symbol:'●',count:24,copyLimit:2,essence:5,craft:20},uncommon:{name:'Poco común',color:'#60CF89',symbol:'◆',count:16,copyLimit:2,essence:10,craft:40},rare:{name:'Rara',color:'#56AAFF',symbol:'✦',count:10,copyLimit:2,essence:25,craft:100},epic:{name:'Épica',color:'#BD7AFF',symbol:'✶',count:6,copyLimit:2,essence:60,craft:240},legendary:{name:'Legendaria',color:'#FFBC46',symbol:'★',count:4,copyLimit:1,essence:150,craft:600}};
const cards=[];
const effect=(op,value,scope='self',trigger='play',extra={})=>({op,value,scope,trigger,...extra});
function add(id,name,family,rare,cost,stats,effects,text,artSubject,role,counter){
 const card={number:cards.length+1,id,name,family,rarity:rare,mana:cost,copyLimit:rarity[rare].copyLimit,stats,effects,text,artId:id,artSubject,role,counter,target:effects.find(e=>['directDamage','freeze','destroySupport','equip'].includes(e.op))?.scope||'none',testId:'CARD-'+String(cards.length+1).padStart(2,'0')};cards.push(card);return card;
}
const ally=(id,name,r,c,a,h,keywords,enter,text,subject,role,counter)=>add(id,name,'Aliado',r,c,{attack:a,hp:h,keywords},enter,text,subject,role,counter);
// Comunes: 24. Los valores v2 sustituyen el borrador previo; no alteran reglas v1.
ally('guardian','Guardiana del umbral','common',2,2,5,['custodia'],[],'Custodia. Fuerza 2, vida 5.','adult woman with bronze armor and a broad shield','Defensa','Daño de área o un atacante de fuerza alta.');
ally('exploradora','Exploradora del paso','common',1,2,3,[],[],'Fuerza 2, vida 3. Ataca desde tu siguiente turno.','adult woman with a green cloak and a brass compass','Presión temprana','Llama reveladora o un defensor de mayor vida.');
ally('centinela','Centinela de bronce','common',3,4,7,[],[],'Fuerza 4, vida 7. Ataca desde tu siguiente turno.','adult man in weathered bronze armor','Amenaza resistente','Congelación, equipo rival o daño combinado.');
ally('testigo','Testigo del sendero','common',2,3,5,[],[effect('attackBonus',1,'summoned','enter',{condition:'citedThisTurn'})],'Fuerza 3, vida 5. Si ya citaste este turno, entra con 1 fuerza adicional.','adult man carrying a covered lantern on a forest path','Sinergia de lectura','Custodia o daño antes de que ataque.');
add('fuego','Llama reveladora','Hechizo','common',1,{},[effect('directDamage',3,'enemyGuarded')],'Inflige 3 de daño a un objetivo rival. Respeta Custodia.','one curling amber flame','Daño eficiente','Escudo o Custodia.');
add('escudo','Sello protector','Hechizo','common',1,{},[effect('shield',5)],'Tu refugio obtiene 5 de escudo hasta el inicio de tu próximo turno.','a round teal magical seal','Protección','Esperar su expiración o usar daño superior al escudo.');
add('cura','Luz reparadora','Hechizo','common',1,{},[effect('heal',4)],'Recupera 4 de vida de tu refugio, sin superar 32.','a turquoise healing orb','Recuperación','Presión sostenida; no protege aliados.');
add('fuente','Consulta las fuentes','Hechizo','common',1,{},[effect('draw',2)],'Roba 2 cartas. Tu mano admite hasta 8.','a closed book with two floating sheets','Selección de recursos','No aporta vida, protección ni daño inmediato.');
add('armadura','Armadura de argumentos','Reliquia','common',1,{},[effect('equip',0,'ownAlly','play',{attack:1,hp:2})],'Equipa un aliado: obtiene 1 de fuerza y 2 de vida. Máximo 2 reliquias por aliado.','bronze chest armor with teal inlays','Mejora equilibrada','Eliminar o congelar al aliado equipado.');
add('cita','Cita viva','Lectura','common',0,{},[effect('mana',1),effect('shield',1),effect('draw',1)],'Cita un fragmento y explica su relación: gana 1 maná, 1 de escudo y roba 1 carta. Una lectura por turno.','a parchment connected to a luminous thread','Preparación de combinaciones','Su límite por turno y la mano máxima impiden cadenas ilimitadas.');
ally('mensajera','Mensajera del alba','common',1,1,2,[],[effect('draw',1,'self','enter')],'Fuerza 1, vida 2. Al entrar, roba 1 carta.','young adult woman with short auburn hair and copper satchel','Reemplazo de mano','Daño de área; resistencia reducida.');
ally('vigia','Vigía de la muralla','common',1,1,4,['custodia'],[],'Custodia. Fuerza 1, vida 4.','older dark-skinned man with wooden round shield','Defensa temprana','Daño dirigido de 4 o un ataque fuerte.');
ally('aprendiz','Aprendiz de runas','common',1,3,2,[],[],'Fuerza 3, vida 2. Ataca desde tu siguiente turno.','young adult man with curly black hair holding a violet rune','Ataque frágil','Chispa combinada o un defensor.');
ally('cartografa','Cartógrafa del valle','common',2,2,4,[],[effect('shield',2,'self','enter')],'Fuerza 2, vida 4. Al entrar, obtén 2 de escudo.','woman with silver braid, parchment map and brass compass','Desarrollo con defensa','Estadísticas moderadas; el escudo no la protege.');
ally('lancero','Lancero del puente','common',2,5,2,[],[],'Fuerza 5, vida 2. Ataca desde tu siguiente turno.','armored man with a long silver spear on mossy bridge','Eliminar unidades resistentes','Daño pequeño antes de que ataque.');
ally('medica','Médica del bosque','common',2,2,4,[],[effect('heal',2,'self','enter')],'Fuerza 2, vida 4. Al entrar, recupera 2 de vida de tu refugio.','adult woman with dark curly hair and medicinal herb satchel','Recuperación con presencia','Ataque sostenido; curación limitada.');
add('destello','Destello del alba','Hechizo','common',1,{},[effect('directDamage',2,'enemyGuarded'),effect('shield',1)],'Inflige 2 de daño a un objetivo rival y obtén 1 de escudo. Respeta Custodia.','white sunburst over dark valley','Intercambio defensivo','Objetivos de vida superior a 2.');
add('brisa','Brisa del archivo','Hechizo','common',1,{},[effect('draw',1),effect('shield',2)],'Roba 1 carta y obtén 2 de escudo.','teal wind around a closed leather book','Preparación defensiva','No desarrolla aliados ni inflige daño.');
add('velo','Velo de piedra','Hechizo','common',2,{},[effect('shield',10)],'Obtén 10 de escudo hasta el inicio de tu próximo turno.','floating stone fragments forming an arc','Resistir un ataque intenso','Esperar; desaparece al comenzar el turno propio.');
add('chispa','Chispa del debate','Hechizo','common',1,{},[effect('areaDamage',1,'enemyAllies')],'Inflige 1 de daño a cada aliado rival. Atraviesa Custodia.','golden sparks over dark stone','Limpiar aliados debilitados','Aliados resistentes y fila vacía.');
add('braceros','Brazales del camino','Reliquia','common',1,{},[effect('equip',0,'ownAlly','play',{attack:0,hp:4})],'Equipa un aliado: obtiene 4 de vida, sin aumentar su fuerza.','steel bracers with emerald inlays','Resistencia','Congelación; el aliado mantiene su fuerza original.');
add('botas','Botas del viajero','Reliquia','common',1,{},[effect('equip',0,'ownAlly','play',{attack:2,hp:1})],'Equipa un aliado: obtiene 2 de fuerza y 1 de vida. No concede Prontitud.','dark leather traveling boots','Presión','Daño de área o eliminación del portador.');
add('cotejo','Cotejo de fuentes','Lectura','common',0,{},[effect('mana',1),effect('shield',3)],'Cita y explica un fragmento: gana 1 maná y 3 de escudo. Comparte el límite de una lectura por turno.','two parchment fragments joined by teal thread','Preparación defensiva','No roba cartas y comparte límite con Cita viva.');
add('pregunta','Pregunta del lector','Lectura','common',0,{},[effect('draw',2)],'Cita y explica un fragmento: roba 2 cartas. Comparte el límite de una lectura por turno.','crystal prism over open book','Selección','No concede maná; la mano sigue limitada a 8.');
// Poco comunes: 16.
ally('cronista','Cronista de las mareas','uncommon',2,2,3,[],[effect('draw',1,'self','enter')],'Fuerza 2, vida 3. Al entrar, roba 1 carta.','adult man in blue cloak with covered scroll','Desarrollo y robo','Resistencia inferior a aliados sin robo del mismo coste.');
ally('bibliotecario','Custodio del archivo','uncommon',3,1,6,['custodia'],[effect('draw',1,'self','enter')],'Custodia. Fuerza 1, vida 6. Al entrar, roba 1 carta.','older woman with silver hair holding a closed book','Defensa con robo','Fuerza baja y mayor coste.');
add('replica','Réplica fundada','Hechizo','uncommon',1,{},[effect('directDamage',1,'enemyGuarded','play',{citedBonus:3})],'Inflige 1 de daño; si ya citaste este turno, inflige 4. Respeta Custodia.','two narrow opposing beams of light','Daño condicionado','Sin cita tiene poco daño; Custodia limita objetivos.');
add('faro','Faro del criterio','Hechizo','uncommon',2,{},[effect('shield',6),effect('draw',1)],'Obtén 6 de escudo y roba 1 carta.','amber lighthouse over dark sea','Defensa y selección','El escudo expira y no protege aliados.');
ally('rastreador','Rastreador de huellas','uncommon',2,3,2,['prontitud'],[],'Prontitud. Fuerza 3, vida 2. Puede atacar al entrar.','adult ranger by glowing tracks','Ataque inmediato','Custodia y daño de respuesta; baja vida.');
ally('ballestera','Ballestera del paso','uncommon',2,4,4,[],[],'Fuerza 4, vida 4. Ataca desde tu siguiente turno.','adult woman with wooden crossbow in mountain pass','Ataque equilibrado','Daño combinado antes de su turno.');
ally('alquimista','Alquimista del rocío','uncommon',2,2,3,[],[effect('heal',2,'self','enter'),effect('shield',1,'self','enter')],'Fuerza 2, vida 3. Al entrar, recupera 2 de vida y obtén 1 de escudo.','older woman holding a turquoise flask','Recuperación mixta','Menor resistencia que un aliado sin beneficios.');
ally('lector','Lector de estrellas','uncommon',3,3,4,[],[effect('draw',1,'self','enter')],'Fuerza 3, vida 4. Al entrar, roba 1 carta.','adult man with brass astrolabe under stars','Robo con ataque','Coste 3 y vida 4 permiten intercambio.');
ally('defensora','Defensora del archivo','uncommon',3,3,7,['custodia'],[],'Custodia. Fuerza 3, vida 7.','strong woman with silver rectangular shield','Defensa robusta','Lanza, congelación o daño combinado.');
ally('herbolaria','Herbolaria de la ribera','uncommon',3,3,4,['vinculoVital'],[],'Fuerza 3, vida 4. Vínculo vital: al atacar, cura el daño efectivo que inflige.','woman in green cloak with luminous plants','Recuperación mediante combate','Destruirla antes de atacar o absorber con escudo.');
ally('espiritu','Espíritu del farol','uncommon',1,2,1,[],[effect('shield',3,'self','death')],'Fuerza 2, vida 1. Al caer, tu refugio obtiene 3 de escudo.','small amber flame spirit inside glass lantern','Defensa diferida','Solo deja escudo temporal; poca vida.');
ally('artesana','Artesana de cristal','uncommon',2,2,3,[],[effect('draw',1,'self','death')],'Fuerza 2, vida 3. Al caer, roba 1 carta.','adult woman with red braid carving teal crystal','Recuperación de mano diferida','Robo limitado por mano máxima; no activa al entrar.');
add('tormenta','Tormenta de páginas','Hechizo','uncommon',3,{},[effect('areaDamage',3,'enemyAllies')],'Inflige 3 de daño a cada aliado rival. Atraviesa Custodia.','blank parchment pages with violet lightning','Respuesta a filas amplias','Aliados de más de 3 de vida y juego de una sola unidad.');
add('purificar','Agua del manantial','Hechizo','uncommon',2,{},[effect('heal',8)],'Recupera 8 de vida de tu refugio, sin superar 32.','turquoise waterfall into stone basin','Recuperación concentrada','No elimina amenazas ni protege aliados.');
add('lanza','Lanza del testimonio','Reliquia','uncommon',2,{},[effect('equip',0,'ownAlly','play',{attack:3,hp:3})],'Equipa un aliado: obtiene 3 de fuerza y 3 de vida.','silver spear with sapphire inlays','Mejora ofensiva','Congelación y concentración de daño en el portador.');
add('totemroble','Tótem del roble','Tótem','uncommon',2,{charges:3},[effect('shield',2,'self','ownStart')],'Al empezar tus próximos 3 turnos, obtén 2 de escudo. Ocupa un apoyo.','wooden owl totem with moss and emerald light','Protección sostenida','Disolver el vínculo o presión que supere 2 de escudo.');
// Raras: 10.
add('relacion','Hilo de inferencia','Hechizo','rare',2,{},[effect('directDamage',4,'enemyGuarded','play',{citedBonus:2})],'Inflige 4 de daño; si ya citaste este turno, inflige 6. Respeta Custodia.','amber thread winding through teal mist','Daño condicionado','Escudo y Custodia; cuesta más que daño pequeño.');
add('contraste','Contraste de voces','Hechizo','rare',2,{},[effect('areaDamage',2,'enemyAllies')],'Inflige 2 de daño a cada aliado rival. Atraviesa Custodia.','two spectral masks facing each other','Respuesta a grupos frágiles','Aliados de vida alta.');
ally('arquero','Arquero de la cumbre','rare',3,4,3,['prontitud'],[],'Prontitud. Fuerza 4, vida 3. Puede atacar al entrar.','adult archer with blue cloak on snowy ridge','Ataque inmediato fuerte','Custodia con fuerza de respuesta y baja resistencia.');
ally('sabia','Sabia de los ecos','rare',4,2,7,['custodia'],[effect('draw',2,'self','enter')],'Custodia. Fuerza 2, vida 7. Al entrar, roba 2 cartas.','elderly dark-skinned woman with silver curls and orb','Defensa y mano de coste alto','Fuerza baja y coste 4; mano llena reduce valor.');
ally('golem','Gólem del archivo','rare',4,4,9,['custodia'],[],'Custodia. Fuerza 4, vida 9.','stone golem with bronze joints and teal crystal chest','Defensa pesada','Congelación, equipos o varios efectos de daño.');
ally('duelista','Duelista de las voces','rare',3,4,5,[],[effect('attackBonus',2,'summoned','enter',{condition:'citedThisTurn'})],'Fuerza 4, vida 5. Si ya citaste este turno, entra con 2 de fuerza adicional.','adult woman with two short silver blades','Presión condicionada','Eliminar antes de que ataque; requiere cita previa.');
add('desvincular','Disolver el vínculo','Hechizo','rare',2,{},[effect('destroySupport',1,'enemySupport')],'Destruye un tótem, artefacto o héroe rival. No afecta aliados ni reliquias.','one broken golden chain with bright sparks','Respuesta a permanentes','No tiene objetivo cuando el rival carece de apoyos.');
add('silencio','Silencio del invierno','Hechizo','rare',2,{},[effect('freeze',1,'enemyGuardedAlly')],'Un aliado rival pierde su próximo ataque de turno propio. Después tiene un turno de Deshielo. Respeta Custodia.','icy blue crystal around a feather','Control temporal','Deshielo impide congelación consecutiva; no elimina Custodia.');
add('lente','Lente de las fuentes','Artefacto','rare',2,{charges:3},[effect('draw',1,'self','ownStart')],'Al empezar tus próximos 3 turnos, roba 1 carta. Ocupa un apoyo.','brass magnifying lens over blank parchment','Robo diferido','Disolver el vínculo; no da efecto al entrar.');
add('mareas','Tótem de las mareas','Tótem','rare',2,{charges:3},[effect('heal',2,'self','ownStart')],'Al empezar tus próximos 3 turnos, recupera 2 de vida. Ocupa un apoyo.','blue stone dolphin totem with ocean spray','Recuperación diferida','Disolver el vínculo y daño concentrado.');
// Épicas: 6. Añaden combinaciones y no un multiplicador de rareza.
add('oraculo','Oráculo de obsidiana','Tótem','epic',3,{charges:3},[effect('draw',1,'self','ownStart'),effect('shield',1,'self','ownStart')],'Al empezar tus próximos 3 turnos, roba 1 carta y obtén 1 de escudo. Ocupa un apoyo.','obsidian raven statue on purple crystal pedestal','Robo con protección diferidos','Inversión inicial y destrucción de apoyo.');
add('eclipse','Eclipse de certezas','Hechizo','epic',4,{},[effect('areaDamage',4,'enemyAllies')],'Inflige 4 de daño a cada aliado rival. Atraviesa Custodia.','violet solar eclipse over black mountains','Limpieza costosa de fila','Una sola unidad resistente o fila vacía.');
add('sintesis','Síntesis luminosa','Hechizo','epic',3,{},[effect('directDamage',6,'enemyGuarded','play',{citedBonus:3})],'Inflige 6 de daño; si ya citaste este turno, inflige 9. Respeta Custodia.','three light streams joining a single silver beam','Daño condicionado de coste alto','Custodia, escudo e inversión de maná.');
add('estandarte','Estandarte del acuerdo','Reliquia','epic',3,{},[effect('equip',0,'ownAlly','play',{attack:3,hp:6})],'Equipa un aliado: obtiene 3 de fuerza y 6 de vida.','plain deep-purple banner on golden pole','Mejora de resistencia de coste alto','Congelación y daño de área; concentra recursos en un aliado.');
add('cristal','Cristal de memoria','Reliquia','epic',2,{},[effect('equip',0,'ownAlly','play',{attack:1,hp:1,keyword:'vinculoVital'})],'Equipa un aliado: obtiene 1 de fuerza, 1 de vida y Vínculo vital.','violet crystal heart with golden veins','Recuperación ligada a ataques','Escudo absorbe daño; congelación impide curación.');
add('reloj','Reloj de las decisiones','Artefacto','epic',3,{charges:3},[effect('mana',1,'self','ownStart'),effect('shield',1,'self','ownStart')],'Al empezar tus próximos 3 turnos, gana 1 maná temporal y 1 de escudo. Ocupa un apoyo.','brass hourglass with turquoise sand','Recursos diferidos','Coste inicial, tres usos y destrucción rival.');
// Legendarias: 4. Héroes únicos de poder 1 maná; el artefacto sigue siendo destruible.
add('heroGuardiana','Aurelia, guardiana del umbral','Héroe','legendary',3,{powerCost:1},[effect('shield',3,'self','power')],'Poder: paga 1 maná y obtén 3 de escudo, una vez por turno. Ocupa un apoyo. Un héroe por mazo.','regal adult woman with golden armor and radiant round shield','Defensa recurrente','Disolver el vínculo; cuesta 3 al entrar y no da efecto inmediato.');
add('heroCronista','Nereo, cronista del alba','Héroe','legendary',3,{powerCost:1},[effect('draw',1,'self','power')],'Poder: paga 1 maná y roba 1 carta, una vez por turno. Ocupa un apoyo. Un héroe por mazo.','regal older man with silver hair, gold quill and closed blue book','Selección recurrente','Destrucción del apoyo y mano máxima.');
add('heroExploradora','Iria, exploradora de ecos','Héroe','legendary',3,{powerCost:1},[effect('areaDamage',1,'enemyAllies','power')],'Poder: paga 1 maná e inflige 1 de daño a cada aliado rival, una vez por turno. Ocupa un apoyo. Un héroe por mazo.','regal adult woman with copper braids and amber crystal bow','Presión sobre grupos','Aliados resistentes, fila vacía y destrucción de apoyo.');
add('umbral','Portal del primer relato','Artefacto','legendary',4,{charges:3},[effect('heal',1,'self','ownStart'),effect('shield',2,'self','ownStart'),effect('mana',1,'self','ownStart')],'Al empezar tus próximos 3 turnos, recupera 1 de vida, obtén 2 de escudo y gana 1 maná temporal. Ocupa un apoyo.','golden circular portal above ancient stone threshold','Recuperación y recursos diferidos','Coste 4, tres activaciones y Disolver el vínculo.');
const artLegacy={fuego:'llama',escudo:'sello',fuente:'fuentes',cura:'cura',relacion:'relacion',replica:'replica',faro:'faro',contraste:'contraste'};for(const c of cards)c.artId=artLegacy[c.id]||c.id;
const starterIds=['guardian','exploradora','centinela','testigo','fuego','escudo','cura','fuente','armadura','cita','mensajera','vigia','aprendiz','cartografa','lancero','medica','destello','brisa','velo','chispa','braceros','botas','cotejo','pregunta','cronista','bibliotecario','replica','faro','relacion','contraste'];
const presets={
 guardian:{name:'La guardiana',focus:'Custodia, recuperación y equipos',cards:['guardian','guardian','vigia','bibliotecario','centinela','exploradora','medica','heroGuardiana','totemroble','escudo','cura','faro','fuego','armadura','braceros','cita','cotejo','fuente']},
 cronista:{name:'El cronista',focus:'Robo y daño condicionado por citas',cards:['cronista','cronista','bibliotecario','guardian','testigo','mensajera','heroCronista','lente','fuego','replica','relacion','contraste','fuente','brisa','cura','cita','cita','pregunta']},
 exploradora:{name:'La exploradora',focus:'Presión y Prontitud',cards:['exploradora','exploradora','testigo','centinela','aprendiz','ballestera','rastreador','arquero','heroExploradora','fuego','replica','chispa','botas','armadura','escudo','cura','cita','cotejo']}
};
const collectionPresets={
 guardian:{name:'La guardiana',cards:['guardian','guardian','bibliotecario','bibliotecario','centinela','exploradora','escudo','escudo','cura','fuego','fuego','armadura','armadura','cita','cita','fuente','replica','faro']},
 cronista:{name:'El cronista',cards:['cronista','cronista','bibliotecario','guardian','testigo','exploradora','fuego','fuego','relacion','relacion','cita','cita','fuente','fuente','replica','escudo','cura','contraste']},
 exploradora:{name:'La exploradora',cards:['exploradora','exploradora','testigo','testigo','centinela','centinela','guardian','cronista','fuego','fuego','armadura','armadura','cita','cita','replica','escudo','cura','contraste']}
};
const byId=Object.fromEntries(cards.map(c=>[c.id,c]));
const spec={schemaVersion:1,designVersion:'umbral-diseno-2.0',status:'design_only',language:'es-CL',createdOn:'2026-10-07',engineVersion:'umbral-duelo-2.0',academicVersion:'umbral-1',catalogVersion:'umbral-coleccion-2.0',rarities:rarity,rules:{deckSize:18,alliesMin:6,alliesMax:10,readingMin:1,readingMax:3,cheapMin:6,expensiveMax:4,legendaryMax:2,heroesMax:1,refugeHp:32,shieldCap:16,baseManaStart:3,baseManaCap:6,manaCap:8,handCap:8,allySlots:3,supportSlots:2,relicSlotsPerAlly:2,allyAttackCap:9,allyHpCap:14,ownTurnsMax:12,initialHand:5,mulliganMax:2,secondPlayerInitialShield:2,discardHandAtEnd:true,readingPlaysPerOwnTurn:1,supportCharges:3},pack:{size:5,priceGold:100,regularSlots:4,ordinaryWeights:{common:60,uncommon:25,rare:10,epic:4,legendary:1},fifthWeights:{rare:85,epic:12,legendary:3},uniformWithinRarity:true,allowDuplicateWithinPack:true,pityRule:'none',welcomePacks:3},economy:{startingGold:0,startingEssence:0,starterIds,starterCopies:2,missionGold:30,submitGold:60,missionCount:3,oneCreditPerSessionMission:true,craftUsesEssenceOnly:true,convertOnlyExcessCopies:true,trade:false,purchaseWithRealMoney:false},modes:{class:{name:'Duelo de aula',allCardsLoaned:true,ranked:true,mutableDecks:true},friendly:{name:'Duelo de colección',ownedOnly:true,ranked:false},training:{name:'Entrenamiento',save:false,ranked:false}},presets,cards};
spec.collectionPresets=collectionPresets;
let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++;};
check(cards.length===60,'60 cartas');check(new Set(cards.map(c=>c.id)).size===60,'IDs únicos');check(new Set(cards.map(c=>c.artId)).size===60,'Arte único por carta');
const families={Aliado:24,Hechizo:18,Reliquia:6,'Tótem':3,Artefacto:3,'Héroe':3,Lectura:3};for(const [f,n]of Object.entries(families))check(cards.filter(c=>c.family===f).length===n,'Total '+f);
for(const [r,v]of Object.entries(rarity))check(cards.filter(c=>c.rarity===r).length===v.count,'Total '+r);
const ops=new Set(['attackBonus','directDamage','shield','heal','draw','equip','mana','areaDamage','destroySupport','freeze']);
for(const c of cards){check(c.mana>=0&&c.mana<=4,'Coste '+c.id);check(c.text.length>15&&c.role&&c.counter&&c.artSubject,'Ficha '+c.id);check(c.copyLimit===rarity[c.rarity].copyLimit,'Copias '+c.id);check(c.family==='Aliado'||c.effects.length>0,'Efecto '+c.id);for(const e of c.effects){check(ops.has(e.op),'Operación '+c.id);check(['play','enter','death','ownStart','power'].includes(e.trigger),'Momento '+c.id);check(Number.isInteger(e.value)&&e.value>=0,'Valor '+c.id);}if(c.family==='Aliado')check(c.stats.attack>0&&c.stats.hp>0,'Stats '+c.id);if(['Tótem','Artefacto'].includes(c.family))check(c.stats.charges===3&&c.effects.every(e=>e.trigger==='ownStart'),'Duración '+c.id);if(c.family==='Héroe')check(c.rarity==='legendary'&&c.stats.powerCost===1,'Héroe '+c.id);}
check(starterIds.length===30&&new Set(starterIds).size===30,'30 iniciales');check(starterIds.every(id=>byId[id]),'Iniciales válidas');check(Object.values(spec.pack.ordinaryWeights).reduce((a,b)=>a+b,0)===100,'Pesos ordinarios');check(Object.values(spec.pack.fifthWeights).reduce((a,b)=>a+b,0)===100,'Pesos quinta');
const deckReports=[];
for(const [id,p] of Object.entries(presets)){const cs=p.cards.map(id=>byId[id]);check(cs.every(Boolean),'IDs mazo '+id);check(cs.length===18,'18 mazo '+id);const counts={};for(const card of cs)counts[card.id]=(counts[card.id]||0)+1;check(Object.entries(counts).every(([cid,n])=>n<=byId[cid].copyLimit),'Copias mazo '+id);const ally=cs.filter(c=>c.family==='Aliado').length,reading=cs.filter(c=>c.family==='Lectura').length,cheap=cs.filter(c=>c.mana<=2).length,expensive=cs.filter(c=>c.mana>=4).length,hero=cs.filter(c=>c.family==='Héroe').length,legend=cs.filter(c=>c.rarity==='legendary').length;check(ally>=6&&ally<=10,'Aliados mazo '+id);check(reading>=1&&reading<=3,'Lecturas mazo '+id);check(cheap>=6&&expensive<=4,'Curva mazo '+id);check(hero<=1&&legend<=2,'Únicas mazo '+id);deckReports.push({id,allies:ally,reading,cheap,expensive,hero,legend,averageMana:cs.reduce((n,c)=>n+c.mana,0)/18,curve:Object.fromEntries([0,1,2,3,4].map(n=>[n,cs.filter(c=>c.mana===n).length]))});}
const legendaryChance=1-Math.pow(.99,4)*.97;
const collectionDeckReports=[];
for(const [id,p] of Object.entries(collectionPresets)){const cs=p.cards.map(cid=>byId[cid]),freq={};for(const cid of p.cards)freq[cid]=(freq[cid]||0)+1;check(cs.length===18&&cs.every(Boolean),'Colección IDs '+id);check(p.cards.every(cid=>starterIds.includes(cid)),'Propiedad inicial '+id);check(Object.entries(freq).every(([cid,n])=>n<=byId[cid].copyLimit),'Colección copias '+id);const allies=cs.filter(c=>c.family==='Aliado').length,reading=cs.filter(c=>c.family==='Lectura').length;check(allies>=6&&allies<=10&&reading>=1&&reading<=3,'Colección familias '+id);check(cs.filter(c=>c.mana<=2).length>=6&&cs.filter(c=>c.mana>=4).length<=4,'Colección curva '+id);check(cs.filter(c=>c.rarity==='legendary').length<=2&&cs.filter(c=>c.family==='Héroe').length<=1,'Colección únicas '+id);collectionDeckReports.push({id,allies,reading,averageMana:cs.reduce((n,c)=>n+c.mana,0)/18});}
const fullCollectionCopies=Object.values(rarity).reduce((n,r)=>n+r.count*r.copyLimit,0);
const ordinaryEssence=Object.entries(spec.pack.ordinaryWeights).reduce((n,[r,p])=>n+p/100*rarity[r].essence,0),fifthEssence=Object.entries(spec.pack.fifthWeights).reduce((n,[r,p])=>n+p/100*rarity[r].essence,0);
const odds=Object.entries(rarity).map(([id,r])=>({rarity:id,ordinaryPerSpecificCard:(spec.pack.ordinaryWeights[id]||0)/r.count/100,fifthPerSpecificCard:(spec.pack.fifthWeights[id]||0)/r.count/100}));
check(fullCollectionCopies===116,'116 copias útiles');
fs.writeFileSync(path.join(dir,'DISENO_CARTAS_60.json'),JSON.stringify(spec,null,2)+'\n');
const lines=['# Catálogo completo: 60 cartas','',`Diseño cerrado ${spec.designVersion}. Estas fichas describen la ampliación; no son el catálogo operativo publicado. No reemplazar automáticamente cartas de duelos v1.`, '', 'Los límites globales y el orden de resolución están en [plan completo](../PLAN_COLECCION_2_COMPLETO.md). Todas las cifras son valores de diseño sujetos al protocolo de calibración antes de liberar un motor nuevo.',''];
for(const c of cards){const r=rarity[c.rarity];lines.push(`## ${String(c.number).padStart(2,'0')}. ${c.name}`, '', `- ID estable: \`${c.id}\`. Familia: ${c.family}. Rareza: ${r.name}, color ${r.color}. Máximo por mazo: ${c.copyLimit}.`, `- Coste: ${c.mana} maná.${c.family==='Aliado'?` Fuerza ${c.stats.attack}; vida ${c.stats.hp}; palabras clave: ${c.stats.keywords.join(', ')||'ninguna'}.`:''}${c.stats.charges?` Duración: ${c.stats.charges} activaciones propias.`:''}${c.stats.powerCost?` Poder: ${c.stats.powerCost} maná; una vez por turno.`:''}`,`- Texto visible: «${c.text}»`,`- Objetivo de selección: \`${c.target}\`; se valida antes de consumir carta o maná.`,`- Papel: ${c.role}. Respuesta rival o límite: ${c.counter}.`,`- Ilustración: sujeto original «${c.artSubject}»; archivo público previsto \`assets/${c.artId}.webp\`.`,`- Prueba obligatoria: \`${c.testId}\`: efecto exacto, rechazo de objetivo/coste inválido sin mutación, evento visual y texto coincidentes.`, '', 'Operaciones, en orden:', '', '```json',JSON.stringify(c.effects,null,2),'```','');}
lines.push('## Mazos iniciales de aula','', 'Disponibles por préstamo en modo aula para todos, incluidos los héroes. El modo colección exige propiedad; puede usar los tres mazos v1 iniciales, que sí quedan cubiertos por los 30 IDs de bienvenida.','');
for(const d of deckReports){const p=presets[d.id];const freq={};for(const cid of p.cards)freq[cid]=(freq[cid]||0)+1;lines.push(`### ${p.name}`, '',p.focus+'.', '', '| Carta | Copias | Maná |','|---|---:|---:|',...Object.entries(freq).map(([id,n])=>`| ${byId[id].name} | ${n} | ${byId[id].mana} |`),'',`18 cartas; ${d.allies} aliados; ${d.reading} lecturas; coste medio ${d.averageMana.toFixed(2)}. Curva 0/1/2/3/4: ${Object.values(d.curve).join('/')}.`,'');}
lines.push('## Mazos iniciales de colección','', 'Listas originales preservadas; valores de cartas v2 al crear una sala v2. Cada copia está cubierta por la bienvenida y cada lista valida los límites nuevos.','');
for(const d of collectionDeckReports){const freq={};for(const cid of collectionPresets[d.id].cards)freq[cid]=(freq[cid]||0)+1;lines.push('### '+collectionPresets[d.id].name+' — colección','','| Carta | Copias | Maná |','|---|---:|---:|',...Object.entries(freq).map(([cid,n])=>`| ${byId[cid].name} | ${n} | ${byId[cid].mana} |`),'',`18 cartas; ${d.allies} aliados; ${d.reading} lecturas; coste medio ${d.averageMana.toFixed(2)}.`,'');}
fs.writeFileSync(path.join(dir,'CATALOGO_60.md'),lines.join('\n'));
fs.writeFileSync(path.join(dir,'AUDITORIA_DISENO.json'),JSON.stringify({checkedAt:new Date().toISOString(),checks,scope:'Consistencia documental y numérica; no prueba el motor v2 ni su balance jugado.',cards:60,families,rarities:Object.fromEntries(Object.entries(rarity).map(([id,r])=>[id,r.count])),starterTypes:30,starterCopies:60,fullCollectionCopies,legendaryAtLeastOnePerPack:legendaryChance,perSpecificCard:odds,essencePerPackWithFullCollection:4*ordinaryEssence+fifthEssence,deckReports},null,2)+'\n');
console.log(JSON.stringify({checks,cards:60,fullCollectionCopies,legendaryChance,deckReports},null,2));
