(function(){'use strict';const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let auth,data;
 async function api(action,body){const token=await auth.currentUser.getIdToken(),r=await fetch('/api/paes?action='+action,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo consultar.');return d;}
 function render(){const course=$('course').value,rows=data.rows.filter(r=>r.curso===course);$('publication').textContent=data.publication.cursos?.[course]?'Pauta publicada.':'Pauta privada; cada estudiante ve su resumen al entregar.';
  $('rows').innerHTML=rows.length?rows.map((r,i)=>`<tr><td>${esc(r.nombre)}</td><td>${r.resetAt?'Reabierta':r.submitted&&r.completada?'Completada':'En progreso'}</td><td>${r.performance?`${r.performance.correct}/${r.performance.total}`:'Pendiente'}</td><td>${r.performance?`${r.performance.paesEstimate.points} puntos`:'Pendiente'}</td><td>${r.strikes||0}/3</td><td><button type="button" data-detail="${i}">Ver</button> <button type="button" data-reset="${i}">Reabrir</button></td></tr>`).join(''):'<tr><td colspan="6">Sin intentos para este curso.</td></tr>';
  $('keys').textContent=Object.entries(data.keys).map(([g,qs])=>`${g==='regular'?'Recorrido completo':'Recorrido con apoyo'}\n\n`+qs.map(q=>`${q.id}. ${q.text}\n${q.options.map((o,i)=>'ABCD'[i]+'. '+o).join('\n')}\n${q.skill} · Tarea ${q.task}\nClave ${q.key}: ${q.reason}\nEvidencia: ${q.evidence}\n${q.failures.map((f,i)=>f?'ABCD'[i]+': '+f:'').filter(Boolean).join('\n')}`).join('\n\n')).join('\n\n');
  document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const r=rows[Number(b.dataset.detail)];$('detail').hidden=false;const previous=r.archivedAttempt,summary=r.performance?`PAES referencial: ${r.performance.paesEstimate.points} puntos (${r.performance.correct}/${r.performance.total} aciertos). Proyección CEST a ${r.performance.paesEstimate.equivalentCorrect}/60; no es puntaje oficial ni predicción.\n`:'';$('detail').textContent=`${r.nombre} · ${r.curso}\n${r.submitted&&r.completada?'Completada':'En progreso'} · ${r.endedBy==='time'?'Cierre al agotar 75 minutos':r.endedBy==='strikes'?'Cierre por strikes':r.endedBy==='student'?'Entrega del estudiante':'Sin entrega'}\n${summary}Strikes: ${r.strikes||0}\n${Object.values(r.incidents||{}).map(e=>`${new Date(e.at).toLocaleString('es-CL')} · ${e.reason}`).join('\n')}\n\nVersión: ${r.version||'Sin versión'}\n\nRespuestas (códigos de alternativa originales): ${JSON.stringify(r.answers||{})}\n\nPauta de este intento:\n${(r.review||[]).map(q=>q.id+': '+q.text+'\n'+q.options.map((o,i)=>'ABCD'[i]+'. '+o).join('\n')+'\nClave '+q.key+' | '+q.reason).join('\n\n')}\n\nReflexiones opcionales:\n${Object.entries(r.reflection||{}).map(([k,v])=>k+': '+v).join('\n')}\n${previous?'\nIntento anterior conservado: '+JSON.stringify(previous):''}`;});
  document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>perform(async()=>{const r=rows[Number(b.dataset.reset)];if(!confirm('¿Reabrir este intento? Se conserva su registro anterior; el estudiante deberá recargar.'))return;await api('admin-mini-reset',{uid:r.uid,sessionId:r.sessionId});await refresh();}));
 }
 async function refresh(){data=await api('admin-mini-list');$('privatePanel').hidden=false;$('adminLogin').hidden=true;$('adminStatus').textContent='Panel actualizado';render();}
 async function perform(fn){try{await fn();}catch(e){$('adminStatus').textContent=e.message;}}
 $('adminLogin').onsubmit=e=>{e.preventDefault();perform(async()=>{({auth}=await PaesStudentSession.client());await auth.signInWithEmailAndPassword($('email').value,$('adminPassword').value);$('adminPassword').value='';await refresh();});};$('course').onchange=render;$('refresh').onclick=()=>perform(refresh);
 for(const [id,published]of [['publish',true],['hideResults',false]])$(id).onclick=()=>perform(async()=>{await api('admin-mini-release',{curso:$('course').value,published});await refresh();});
 perform(async()=>{({auth}=await PaesStudentSession.client());if(auth.currentUser)await refresh();});
})();
