(async function(){
 'use strict';
 const $=id=>document.getElementById(id),guided=location.pathname.endsWith('guiada.html'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const mobile=matchMedia('(pointer:coarse)').matches||/Android|iPhone|iPad/i.test(navigator.userAgent);
 MiniIntegrity.protectSelection($('workspace'));
 let session,activity,identity,form={},preview=false,resetAt=null,attempt={answers:{},reflection:{}},saveQueue=Promise.resolve(),saveTimer,revision=0,busy=false,running=false,guard=null,section=1,step=0,pending=[];
 let clockServer=0,clockLocal=0,timerLoop=null,timeExpired=false,lastExpiryTry=-Infinity;
 function tickTime(){
  const visible=!preview&&Number.isFinite(attempt.expiresAt);$('timer').hidden=!visible;if(!visible||done()){$('timer').hidden=true;return;}
  const seconds=Math.max(0,Math.ceil((attempt.expiresAt-(clockServer+performance.now()-clockLocal))/1000));
  $('timer').textContent=`Tiempo restante: ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('timer').classList.toggle('timeWarning',seconds<=300);
  if(seconds===0){if(!timeExpired){timeExpired=true;running=false;clearTimeout(saveTimer);guard?.destroy();guard=null;window.speechSynthesis?.cancel();document.body.classList.remove('obscured');$('guard').hidden=true;$('workspace').querySelectorAll('[data-answer],textarea').forEach(el=>el.disabled=true);section=4;update();if(!$('workspace').hidden){render();$('closing').scrollIntoView({block:'start'});}$('submitStatus').textContent='Tiempo agotado. Enviando las respuestas guardadas…';}
   if(!busy&&performance.now()-lastExpiryTry>=5000){lastExpiryTry=performance.now();submit();}
  }
 }
 function startTimer(){clearInterval(timerLoop);timeExpired=false;lastExpiryTry=-Infinity;tickTime();if(!done()&&!preview&&attempt.expiresAt)timerLoop=setInterval(tickTime,1000);}
 const done=()=>attempt.submitted===true&&attempt.completada===true;
 const key=()=>`paes-mini:${identity.uid}:${activity.sessionId}:${activity.version}:${resetAt||0}${attempt.integrityEpoch?':strikes-'+attempt.integrityEpoch:''}`;
 const payload=()=>({version:activity.version,resetAt,integrityEpoch:attempt.integrityEpoch||0,answers:{...attempt.answers},reflection:{...attempt.reflection}});
 function accessWait(work){let timer;return Promise.race([work,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('La conexión está demorando. Revisa tu internet y vuelve a ingresar.')),20000);})]).finally(()=>clearTimeout(timer));}
 async function api(action,data){const token=await session.user.getIdToken(),r=await fetch('/api/paes?action='+action+'&mode='+(guided?'guided':'regular'),{method:data?'POST':'GET',headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});const json=await r.json();if(!r.ok)throw Object.assign(new Error(json.error||'No se pudo guardar.'),{status:r.status});if(Number.isFinite(json.serverNow)){clockServer=json.serverNow;clockLocal=performance.now();}return json;}
 function store(){try{localStorage.setItem(key(),JSON.stringify({...payload(),pending,localUpdatedAt:Date.now()}));}catch(_){$('saveStatus').textContent='No se pudo conservar la copia local. Mantén esta página abierta.';}}
 function update(){const n=activity.questions.filter(q=>attempt.answers[q.id]).length;$('progress').textContent=`${n} de ${activity.questions.length} respondidas`;$('strikes').textContent=preview?'Vista docente · sin registro':`Strikes: ${Math.min(3,(attempt.strikes||0)+pending.length)} de 3`;$('submit').disabled=preview||busy||done();$('submit').textContent=preview?'Vista docente · sin entrega':done()?'Miniensayo entregado':busy?'Entregando…':'Entregar miniensayo';}
 async function load(restoreLocal=false){const previousEpoch=attempt.integrityEpoch||0,d=await api('mini-state');if(d.redirect){location.replace(d.redirect);return false;}identity=d.identity;activity=d.activity;form=d.form||{};preview=d.preview===true;resetAt=d.resetAt;attempt=d.attempt||{answers:{},reflection:{}};if(previousEpoch!==(attempt.integrityEpoch||0))pending=[];
  if(restoreLocal&&!done()){try{const local=JSON.parse(localStorage.getItem(key())||'null');if(local){pending=(local.pending||[]).filter(e=>!attempt.incidents?.[e.eventId]);if(local.localUpdatedAt>(attempt.updatedAt||0)){attempt.answers=local.answers||{};attempt.reflection=local.reflection||{};}}}catch(_){}}
  if(done()){pending=[];running=false;try{localStorage.removeItem(key());}catch(_){}guard?.destroy();guard=null;document.body.classList.remove('obscured');$('guard').hidden=true;}
  $('identity').textContent=identity.nombre+' · '+identity.curso;$('readyIdentity').textContent=$('identity').textContent;document.querySelectorAll('[data-time-limit]').forEach(el=>el.textContent=activity.timeLimitMinutes+' minutos');$('courseSchedule').hidden=identity.curso!=='4A-HC';update();startTimer();return true;
 }
 function tabs(){const parts=guided?[[1,'Lectura y preguntas'],[4,'Revisión y entrega']]:[[1,'Texto 1'],[2,'Texto 2'],[3,'Texto 3'],[4,'Revisión y entrega']];$('tabs').innerHTML=parts.map(([n,title])=>`<button type="button" data-tab="${n}" ${section===n?'aria-current="page"':''}>${title}</button>`).join('');$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{section=Number(b.dataset.tab);render();});}
 function tableMarkup(t){if(!t.table)return '';const b=t.table;return `<div class="tableWrap"><table><caption>${esc(b.caption)}</caption><thead><tr>${b.headers.map(v=>`<th scope="col">${esc(v)}</th>`).join('')}</tr></thead><tbody>${b.rows.map(row=>`<tr><th scope="row">${esc(row[0])}</th>${row.slice(1).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="source">${esc(b.note)}</p>`;}
 function questionMarkup(q){const ordering=guided?['A','B','C','D']:form[q.id]||['A','B','C','D'];const review=attempt.review?.find(x=>x.id===q.id);return `<article class="question" id="${q.id}"><h3>${q.id.slice(1)}. ${esc(q.text)}</h3><div role="group" aria-label="Pregunta ${q.id.slice(1)}">${ordering.map((original,i)=>`<button type="button" class="option${review&&original===review.key?' correct':''}${review&&attempt.answers[q.id]===original&&original!==review.key?' wrong':''}" data-answer="${original}" data-q="${q.id}" aria-pressed="${attempt.answers[q.id]===original}" ${done()||busy||timeExpired?'disabled':''}><span class="letter">${'ABCD'[i]}</span><span>${esc(q.options[original.charCodeAt(0)-65])}</span></button>`).join('')}</div>${review?`<p class="feedback">${esc(review.reason)}</p>`:''}</article>`;}
 function render(){tabs();$('reading').hidden=section===4;$('closing').hidden=section!==4;if(section===4){closing();return;}
  const t=activity.texts.find(t=>t.id===section)||activity.texts[0],qs=activity.questions.filter(q=>q.textId===t.id),shown=guided?[qs[Math.min(step,qs.length-1)]]:qs;
  $('reading').innerHTML=`${guided?'<div class="steps"><span>1 · Escucha o lee</span><span>2 · Busca una pista</span><span>3 · Elige y revisa</span></div><div class="next"><button type="button" id="listen">Escuchar lectura y pregunta</button><button type="button" id="stopAudio">Detener audio</button></div>':''}<div class="layout"><article class="reading"><p class="eyebrow">Texto ${t.id} · ${esc(t.genre)}</p><h2>${esc(t.title)}</h2>${t.paragraphs.map((p,i)=>`<p><span class="pn">${i+1}</span>${esc(p)}</p>${t.table?.after===i+1?tableMarkup(t):''}`).join('')}<p class="source">Texto original de Estudia CEST para este miniensayo. ${t.table?'Estudio y datos ficticios.':''}</p></article><div>${shown.map(questionMarkup).join('')}</div></div><div class="next">${guided?`<button type="button" id="previous" ${step===0?'disabled':''}>Anterior</button><span>Pregunta ${step+1} de ${qs.length}</span>`:''}<button id="next" type="button" class="primary">${guided?(step<qs.length-1?'Siguiente pregunta':'Revisar y entregar'):(section<3?'Siguiente texto':'Revisar y entregar')}</button></div>`;
  $('reading').querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(done()||busy||timeExpired)return;attempt.answers[b.dataset.q]=b.dataset.answer;changed();render();});
  $('next').onclick=()=>{window.speechSynthesis?.cancel();if(guided&&step<qs.length-1)step++;else section=guided?4:section+1;render();$('tabs').scrollIntoView({block:'start'});};
  if(guided){$('previous').onclick=()=>{window.speechSynthesis?.cancel();step=Math.max(0,step-1);render();};$('listen').onclick=()=>{window.speechSynthesis?.cancel();const q=shown[0],speech=new SpeechSynthesisUtterance(t.title+'. '+t.paragraphs.join(' ')+' Pregunta '+(step+1)+'. '+q.text+'. '+q.options.map((o,i)=>'ABCD'[i]+'. '+o).join('. '));speech.lang='es-CL';speech.rate=.85;window.speechSynthesis?.speak(speech);};$('stopAudio').onclick=()=>window.speechSynthesis?.cancel();}
 }
 function closing(){const answered=activity.questions.filter(q=>attempt.answers[q.id]).length;$('summary').textContent=done()?'Completada · Entrega confirmada':`${answered} de ${activity.questions.length} respondidas. ${activity.questions.length-answered} sin respuesta.`;
  $('answerMap').innerHTML=activity.questions.map(q=>`<button type="button" class="${attempt.answers[q.id]?'marked':''}" data-jump="${q.id}" aria-label="Pregunta ${q.id.slice(1)}, ${attempt.answers[q.id]?'respondida':'sin respuesta'}">${q.id.slice(1)}${attempt.answers[q.id]?' ✓':''}</button>`).join('');$('answerMap').querySelectorAll('button').forEach(b=>b.onclick=()=>{const q=activity.questions.find(q=>q.id===b.dataset.jump);section=q.textId;step=activity.questions.indexOf(q);render();$(q.id)?.scrollIntoView({block:'center'});});
  document.querySelectorAll('[data-reflection]').forEach(el=>{el.value=attempt.reflection?.[el.dataset.reflection]||'';el.disabled=done()||busy||timeExpired;});$('delivery').hidden=!done();
  $('results').hidden=!attempt.performance;$('results').innerHTML=scoreMarkup()+(attempt.result?`<h2>Revisión publicada</h2>${Object.entries(attempt.result.skills).map(([s,v])=>`<p>${esc(s)}: ${v.correct} de ${v.total}</p>`).join('')}<p>Vuelve a cada lectura para revisar sus fundamentos.</p>`:'');
  update();
 }
 function scoreMarkup(){const p=attempt.performance;if(!p)return '';const e=p.paesEstimate;return `<h2>Puntaje PAES referencial</h2><p class="scorePoints">${e.points} puntos</p><p>${p.correct} de ${p.total} aciertos · ${p.percentage.toLocaleString('es-CL')} %</p><p class="scoreNote">Estimación de práctica. No es un puntaje oficial ni una predicción de tu resultado PAES.${guided?' Este recorrido tiene seis preguntas y no se compara con el miniensayo completo.':''}</p><details><summary>Cómo se obtuvo</summary><p>Se proyecta tu proporción de aciertos a 60 preguntas: ${p.correct}/${p.total} × 60, redondeada a ${e.equivalentCorrect}. Ese valor se consulta en la <a href="${esc(e.source)}" target="_blank" rel="noopener">tabla oficial DEMRE de Competencia Lectora, Admisión 2027</a>. La proyección es una aproximación de Estudia CEST: este miniensayo no está equiparado a la PAES.</p></details>`;}
 function changed(){if(timeExpired||done())return;if(preview){update();$('saveStatus').textContent='Vista docente: selecciones de prueba sin guardar.';return;}revision++;store();update();clearTimeout(saveTimer);$('saveStatus').textContent='Cambios pendientes';saveTimer=setTimeout(queueSave,650);}
 function queueSave(){if(done()||busy||!running)return saveQueue;const p=payload(),v=revision;$('saveStatus').textContent='Guardando…';saveQueue=saveQueue.catch(()=>{}).then(async()=>{try{const r=await api('mini-save',p);if(r.attempt.submitted&&r.attempt.completada){attempt=r.attempt;await confirmDelivery();return;}attempt.updatedAt=r.attempt.updatedAt;attempt.strikes=r.attempt.strikes;attempt.timerStartedAt=r.attempt.timerStartedAt;attempt.expiresAt=r.attempt.expiresAt;attempt.timeLimitMinutes=r.attempt.timeLimitMinutes;tickTime();if(v===revision)$('saveStatus').textContent='Avance guardado';}catch(e){if(e.status===409){await load();render();}else $('saveStatus').textContent='Error al guardar. Avance conservado; reintenta la entrega.';}});return saveQueue;}
 function onBlock(blocked,reason){if(!running||done())return;const locked=(attempt.strikes||0)+pending.length>=3;blocked=blocked||locked;$('guard').hidden=!blocked;document.body.classList.toggle('obscured',blocked);if(blocked){$('guardText').textContent=locked?'Tercer strike. El intento se cerró; se están enviando tus respuestas. Si falla la conexión, pulsa el botón para reintentar.':reason==='hidden'?'Regresa a esta pestaña.':reason==='blur'?'Esta ventana perdió el foco. Vuelve dentro de cinco segundos.':'Restaura la pantalla completa y usa una sola ventana. Si la reducción continúa cinco segundos, se registrará un strike.';}}
 function incident(e){if(done()||!running||(attempt.strikes||0)+pending.length>=3)return;pending.push({...e,...payload()});store();update();onBlock(true,e.reason);$('saveStatus').textContent='Salida registrada. Al tercer strike se entrega el intento.';clearTimeout(saveTimer);flushIncidents().catch(()=>{});}
 function flushIncidents(){saveQueue=saveQueue.catch(()=>{}).then(async()=>{while(pending.length&&!done()){const e=pending[0];try{const r=await api('mini-incident',e);pending.shift();attempt.strikes=r.attempt.strikes;attempt.incidents=r.attempt.incidents;if(r.attempt.submitted&&r.attempt.completada){attempt=r.attempt;await confirmDelivery();return;}store();update();$('guardStatus').textContent=`Strike ${attempt.strikes} de 3. Vuelve para continuar.`;}catch(error){if(error.status===409){await load();render();if(done()){await confirmDelivery();return;}store();update();$('guardStatus').textContent='Estado actualizado por el profesor. Puedes continuar.';guard?.check();return;}$('guardStatus').textContent='Sin conexión. La salida y tus respuestas se conservaron; se enviarán al recuperar conexión.';throw error;}}});return saveQueue;}
 async function begin(){if(busy)return;busy=true;$('begin').disabled=true;
  try{if(!preview&&!done()&&!mobile&&document.fullscreenEnabled&&!document.fullscreenElement)await document.documentElement.requestFullscreen();if(!preview&&!done()){await saveQueue;await flushIncidents();if(!done()){const r=await api('mini-start',payload());attempt=r.attempt.submitted&&r.attempt.completada?r.attempt:{...r.attempt,answers:attempt.answers,reflection:attempt.reflection};running=!done();if(running)guard=MiniIntegrity.create({active:()=>running&&!done(),onBlock,onIncident:incident,screenRequired:!mobile&&document.fullscreenEnabled,mobile});}}
   $('entry').hidden=true;$('ready').hidden=true;$('workspace').hidden=false;section=done()?4:1;render();startTimer();$('saveStatus').textContent=preview?'Vista docente: puedes recorrer las lecturas y probar alternativas sin crear un intento.':done()?'Entrega confirmada':'Avance recuperado';if(!done()&&Object.keys(attempt.answers||{}).length)changed();if(done())await confirmDelivery();
  }catch(e){$('readyStatus').textContent=e.name==='NotAllowedError'?'Permite la pantalla completa y vuelve a comenzar.':e.message;}finally{busy=false;$('begin').disabled=false;if(!$('workspace').hidden)render();guard?.check();}
 }
 async function confirmDelivery(){await load();if(!attempt||attempt.completada !== true||attempt.submitted !== true)throw new Error('La entrega aún no está confirmada. Reintenta.');running=false;guard?.destroy();guard=null;window.speechSynthesis?.cancel();document.body.classList.remove('obscured');$('guard').hidden=true;$('workspace').hidden=false;$('entry').hidden=true;$('ready').hidden=true;section=4;render();$('saveStatus').textContent='Entrega confirmada';$('submitStatus').textContent='Entrega confirmada';$('confirmedMessage').textContent=attempt.endedBy==='time'?`Se agotaron los ${attempt.timeLimitMinutes||activity.timeLimitMinutes} minutos. Las respuestas guardadas quedaron entregadas y el intento aparece como Completada.`:attempt.endedBy==='strikes'?'El tercer strike cerró el intento. Las respuestas disponibles quedaron guardadas y aparecerá como Completada. El profesor revisará las incidencias.':'Tu trabajo quedó guardado y aparecerá como Completada.';$('confirmedScore').innerHTML=scoreMarkup();if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});if(!$('confirmation').open)$('confirmation').showModal();}
 async function submit(){if(busy||done())return;busy=true;clearTimeout(saveTimer);update();$('submitStatus').textContent='Entregando…';
  try{await saveQueue;await flushIncidents();if(!done())try{await api('mini-submit',payload());}catch(e){if(e.status!==409)throw e;}await confirmDelivery();}
  catch(e){$('submitStatus').textContent=e.message+' Tu avance se conserva. Puedes reintentar.';store();}finally{busy=false;update();guard?.check();}
 }
 async function enter(){if($('enter').disabled)return;$('enter').disabled=true;$('entryStatus').textContent='Recuperando tu sesión…';try{session=await accessWait(MiniSession.restore());if(!session){$('entryStatus').textContent='';$('login').showModal();return;}$('entryStatus').textContent='Abriendo el miniensayo…';if(await accessWait(load(true))){$('entry').hidden=true;if(done()){await confirmDelivery();return;}$('ready').hidden=false;}}catch(e){$('entryStatus').textContent=PaesStudentSession.errorMessage(e);}finally{$('enter').disabled=false;}}
 $('enter').onclick=enter;$('begin').onclick=begin;$('submit').onclick=submit;
 $('loginForm').onsubmit=async e=>{e.preventDefault();$('loginStatus').textContent='Ingresando…';try{session=await MiniSession.signIn($('rut').value,$('password').value);$('password').value='';if(await load(true)){$('login').close();$('entry').hidden=true;if(done())await confirmDelivery();else $('ready').hidden=false;}}catch(e){$('loginStatus').textContent=PaesStudentSession.errorMessage(e);}};
 $('cancelLogin').onclick=()=>$('login').close();$('closeConfirmation').onclick=()=>$('confirmation').close();
 document.querySelectorAll('[data-reflection]').forEach(el=>el.oninput=()=>{if(done()||busy||timeExpired)return;attempt.reflection[el.dataset.reflection]=el.value;changed();});
 $('recover').onclick=async()=>{if(timeExpired){await submit();return;}try{guard?.suspend();if(!mobile&&document.fullscreenEnabled&&!document.fullscreenElement)await document.documentElement.requestFullscreen();await flushIncidents();guard?.check();}catch(e){$('guardStatus').textContent=e.message;}};
 window.addEventListener('online',()=>{if(running&&!done()){flushIncidents().then(queueSave).catch(()=>{});}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)window.speechSynthesis?.cancel();});
 window.addEventListener('beforeunload',()=>{if(identity&&!done())store();});
})();
